<?php

/**
 * Notas filter form base class.
 *
 * @package    alternativa
 * @subpackage filter
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 24171 2009-11-19 16:37:50Z Kris.Wallsmith $
 */
abstract class BaseNotasFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id_inscripcion'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'gestion_id'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cod_distrito'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'distrito'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cod_ue'                     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desc_ue'                    => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'codigo_rude'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'carnet_identidad'           => new sfWidgetFormFilterInput(),
      'paterno'                    => new sfWidgetFormFilterInput(),
      'materno'                    => new sfWidgetFormFilterInput(),
      'nombre'                     => new sfWidgetFormFilterInput(),
      'fecha_nacimiento'           => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'genero'                     => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'nivel_id'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desc_nivel'                 => new sfWidgetFormFilterInput(),
      'id_grado'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desc_grado'                 => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'paralelo'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desc_abrv'                  => new sfWidgetFormFilterInput(),
      'estado_matricula_inicio_id' => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'matricula_inicio'           => new sfWidgetFormFilterInput(),
      'matricula_fin'              => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desc_estado_matricula'      => new sfWidgetFormFilterInput(),
      'cod_org_curr'               => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desc_modalidad'             => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'cod_dependencia'            => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'desc_dependencia'           => new sfWidgetFormFilterInput(),
      'm101'                       => new sfWidgetFormFilterInput(),
      'pt101'                      => new sfWidgetFormFilterInput(),
      'st101'                      => new sfWidgetFormFilterInput(),
      'tt101'                      => new sfWidgetFormFilterInput(),
      'pa101'                      => new sfWidgetFormFilterInput(),
      're101'                      => new sfWidgetFormFilterInput(),
      'pf101'                      => new sfWidgetFormFilterInput(),
      'm102'                       => new sfWidgetFormFilterInput(),
      'pt102'                      => new sfWidgetFormFilterInput(),
      'st102'                      => new sfWidgetFormFilterInput(),
      'tt102'                      => new sfWidgetFormFilterInput(),
      'pa102'                      => new sfWidgetFormFilterInput(),
      're102'                      => new sfWidgetFormFilterInput(),
      'pf102'                      => new sfWidgetFormFilterInput(),
      'm103'                       => new sfWidgetFormFilterInput(),
      'pt103'                      => new sfWidgetFormFilterInput(),
      'st103'                      => new sfWidgetFormFilterInput(),
      'tt103'                      => new sfWidgetFormFilterInput(),
      'pa103'                      => new sfWidgetFormFilterInput(),
      're103'                      => new sfWidgetFormFilterInput(),
      'pf103'                      => new sfWidgetFormFilterInput(),
      'm104'                       => new sfWidgetFormFilterInput(),
      'pt104'                      => new sfWidgetFormFilterInput(),
      'st104'                      => new sfWidgetFormFilterInput(),
      'tt104'                      => new sfWidgetFormFilterInput(),
      'pa104'                      => new sfWidgetFormFilterInput(),
      're104'                      => new sfWidgetFormFilterInput(),
      'pf104'                      => new sfWidgetFormFilterInput(),
      'm105'                       => new sfWidgetFormFilterInput(),
      'pt105'                      => new sfWidgetFormFilterInput(),
      'st105'                      => new sfWidgetFormFilterInput(),
      'tt105'                      => new sfWidgetFormFilterInput(),
      'pa105'                      => new sfWidgetFormFilterInput(),
      're105'                      => new sfWidgetFormFilterInput(),
      'pf105'                      => new sfWidgetFormFilterInput(),
      'm106'                       => new sfWidgetFormFilterInput(),
      'pt106'                      => new sfWidgetFormFilterInput(),
      'st106'                      => new sfWidgetFormFilterInput(),
      'tt106'                      => new sfWidgetFormFilterInput(),
      'pa106'                      => new sfWidgetFormFilterInput(),
      're106'                      => new sfWidgetFormFilterInput(),
      'pf106'                      => new sfWidgetFormFilterInput(),
      'm107'                       => new sfWidgetFormFilterInput(),
      'pt107'                      => new sfWidgetFormFilterInput(),
      'st107'                      => new sfWidgetFormFilterInput(),
      'tt107'                      => new sfWidgetFormFilterInput(),
      'pa107'                      => new sfWidgetFormFilterInput(),
      're107'                      => new sfWidgetFormFilterInput(),
      'pf107'                      => new sfWidgetFormFilterInput(),
      'm201'                       => new sfWidgetFormFilterInput(),
      'pt201'                      => new sfWidgetFormFilterInput(),
      'st201'                      => new sfWidgetFormFilterInput(),
      'tt201'                      => new sfWidgetFormFilterInput(),
      'pa201'                      => new sfWidgetFormFilterInput(),
      're201'                      => new sfWidgetFormFilterInput(),
      'pf201'                      => new sfWidgetFormFilterInput(),
      'm202'                       => new sfWidgetFormFilterInput(),
      'pt202'                      => new sfWidgetFormFilterInput(),
      'st202'                      => new sfWidgetFormFilterInput(),
      'tt202'                      => new sfWidgetFormFilterInput(),
      'pa202'                      => new sfWidgetFormFilterInput(),
      're202'                      => new sfWidgetFormFilterInput(),
      'pf202'                      => new sfWidgetFormFilterInput(),
      'm203'                       => new sfWidgetFormFilterInput(),
      'pt203'                      => new sfWidgetFormFilterInput(),
      'st203'                      => new sfWidgetFormFilterInput(),
      'tt203'                      => new sfWidgetFormFilterInput(),
      'pa203'                      => new sfWidgetFormFilterInput(),
      're203'                      => new sfWidgetFormFilterInput(),
      'pf203'                      => new sfWidgetFormFilterInput(),
      'm204'                       => new sfWidgetFormFilterInput(),
      'pt204'                      => new sfWidgetFormFilterInput(),
      'st204'                      => new sfWidgetFormFilterInput(),
      'tt204'                      => new sfWidgetFormFilterInput(),
      'pa204'                      => new sfWidgetFormFilterInput(),
      're204'                      => new sfWidgetFormFilterInput(),
      'pf204'                      => new sfWidgetFormFilterInput(),
      'm205'                       => new sfWidgetFormFilterInput(),
      'pt205'                      => new sfWidgetFormFilterInput(),
      'st205'                      => new sfWidgetFormFilterInput(),
      'tt205'                      => new sfWidgetFormFilterInput(),
      'pa205'                      => new sfWidgetFormFilterInput(),
      're205'                      => new sfWidgetFormFilterInput(),
      'pf205'                      => new sfWidgetFormFilterInput(),
      'm206'                       => new sfWidgetFormFilterInput(),
      'pt206'                      => new sfWidgetFormFilterInput(),
      'st206'                      => new sfWidgetFormFilterInput(),
      'tt206'                      => new sfWidgetFormFilterInput(),
      'pa206'                      => new sfWidgetFormFilterInput(),
      're206'                      => new sfWidgetFormFilterInput(),
      'pf206'                      => new sfWidgetFormFilterInput(),
      'm207'                       => new sfWidgetFormFilterInput(),
      'pt207'                      => new sfWidgetFormFilterInput(),
      'st207'                      => new sfWidgetFormFilterInput(),
      'tt207'                      => new sfWidgetFormFilterInput(),
      'pa207'                      => new sfWidgetFormFilterInput(),
      're207'                      => new sfWidgetFormFilterInput(),
      'pf207'                      => new sfWidgetFormFilterInput(),
      'm208'                       => new sfWidgetFormFilterInput(),
      'pt208'                      => new sfWidgetFormFilterInput(),
      'st208'                      => new sfWidgetFormFilterInput(),
      'tt208'                      => new sfWidgetFormFilterInput(),
      'pa208'                      => new sfWidgetFormFilterInput(),
      're208'                      => new sfWidgetFormFilterInput(),
      'pf208'                      => new sfWidgetFormFilterInput(),
      'm209'                       => new sfWidgetFormFilterInput(),
      'pt209'                      => new sfWidgetFormFilterInput(),
      'st209'                      => new sfWidgetFormFilterInput(),
      'tt209'                      => new sfWidgetFormFilterInput(),
      'pa209'                      => new sfWidgetFormFilterInput(),
      're209'                      => new sfWidgetFormFilterInput(),
      'pf209'                      => new sfWidgetFormFilterInput(),
      'm210'                       => new sfWidgetFormFilterInput(),
      'pt210'                      => new sfWidgetFormFilterInput(),
      'st210'                      => new sfWidgetFormFilterInput(),
      'tt210'                      => new sfWidgetFormFilterInput(),
      'pa210'                      => new sfWidgetFormFilterInput(),
      're210'                      => new sfWidgetFormFilterInput(),
      'pf210'                      => new sfWidgetFormFilterInput(),
      'm211'                       => new sfWidgetFormFilterInput(),
      'pt211'                      => new sfWidgetFormFilterInput(),
      'st211'                      => new sfWidgetFormFilterInput(),
      'tt211'                      => new sfWidgetFormFilterInput(),
      'pa211'                      => new sfWidgetFormFilterInput(),
      're211'                      => new sfWidgetFormFilterInput(),
      'pf211'                      => new sfWidgetFormFilterInput(),
      'm212'                       => new sfWidgetFormFilterInput(),
      'pt212'                      => new sfWidgetFormFilterInput(),
      'st212'                      => new sfWidgetFormFilterInput(),
      'tt212'                      => new sfWidgetFormFilterInput(),
      'pa212'                      => new sfWidgetFormFilterInput(),
      're212'                      => new sfWidgetFormFilterInput(),
      'pf212'                      => new sfWidgetFormFilterInput(),
      'm213'                       => new sfWidgetFormFilterInput(),
      'pt213'                      => new sfWidgetFormFilterInput(),
      'st213'                      => new sfWidgetFormFilterInput(),
      'tt213'                      => new sfWidgetFormFilterInput(),
      'pa213'                      => new sfWidgetFormFilterInput(),
      're213'                      => new sfWidgetFormFilterInput(),
      'pf213'                      => new sfWidgetFormFilterInput(),
      'm221'                       => new sfWidgetFormFilterInput(),
      'pt221'                      => new sfWidgetFormFilterInput(),
      'st221'                      => new sfWidgetFormFilterInput(),
      'tt221'                      => new sfWidgetFormFilterInput(),
      'pa221'                      => new sfWidgetFormFilterInput(),
      're221'                      => new sfWidgetFormFilterInput(),
      'pf221'                      => new sfWidgetFormFilterInput(),
      'm222'                       => new sfWidgetFormFilterInput(),
      'pt222'                      => new sfWidgetFormFilterInput(),
      'st222'                      => new sfWidgetFormFilterInput(),
      'tt222'                      => new sfWidgetFormFilterInput(),
      'pa222'                      => new sfWidgetFormFilterInput(),
      're222'                      => new sfWidgetFormFilterInput(),
      'pf222'                      => new sfWidgetFormFilterInput(),
      'm301'                       => new sfWidgetFormFilterInput(),
      'pt301'                      => new sfWidgetFormFilterInput(),
      'st301'                      => new sfWidgetFormFilterInput(),
      'tt301'                      => new sfWidgetFormFilterInput(),
      'pa301'                      => new sfWidgetFormFilterInput(),
      're301'                      => new sfWidgetFormFilterInput(),
      'pf301'                      => new sfWidgetFormFilterInput(),
      'm302'                       => new sfWidgetFormFilterInput(),
      'pt302'                      => new sfWidgetFormFilterInput(),
      'st302'                      => new sfWidgetFormFilterInput(),
      'tt302'                      => new sfWidgetFormFilterInput(),
      'pa302'                      => new sfWidgetFormFilterInput(),
      're302'                      => new sfWidgetFormFilterInput(),
      'pf302'                      => new sfWidgetFormFilterInput(),
      'm303'                       => new sfWidgetFormFilterInput(),
      'pt303'                      => new sfWidgetFormFilterInput(),
      'st303'                      => new sfWidgetFormFilterInput(),
      'tt303'                      => new sfWidgetFormFilterInput(),
      'pa303'                      => new sfWidgetFormFilterInput(),
      're303'                      => new sfWidgetFormFilterInput(),
      'pf303'                      => new sfWidgetFormFilterInput(),
      'm304'                       => new sfWidgetFormFilterInput(),
      'pt304'                      => new sfWidgetFormFilterInput(),
      'st304'                      => new sfWidgetFormFilterInput(),
      'tt304'                      => new sfWidgetFormFilterInput(),
      'pa304'                      => new sfWidgetFormFilterInput(),
      're304'                      => new sfWidgetFormFilterInput(),
      'pf304'                      => new sfWidgetFormFilterInput(),
      'm305'                       => new sfWidgetFormFilterInput(),
      'pt305'                      => new sfWidgetFormFilterInput(),
      'st305'                      => new sfWidgetFormFilterInput(),
      'tt305'                      => new sfWidgetFormFilterInput(),
      'pa305'                      => new sfWidgetFormFilterInput(),
      're305'                      => new sfWidgetFormFilterInput(),
      'pf305'                      => new sfWidgetFormFilterInput(),
      'm306'                       => new sfWidgetFormFilterInput(),
      'pt306'                      => new sfWidgetFormFilterInput(),
      'st306'                      => new sfWidgetFormFilterInput(),
      'tt306'                      => new sfWidgetFormFilterInput(),
      'pa306'                      => new sfWidgetFormFilterInput(),
      're306'                      => new sfWidgetFormFilterInput(),
      'pf306'                      => new sfWidgetFormFilterInput(),
      'm307'                       => new sfWidgetFormFilterInput(),
      'pt307'                      => new sfWidgetFormFilterInput(),
      'st307'                      => new sfWidgetFormFilterInput(),
      'tt307'                      => new sfWidgetFormFilterInput(),
      'pa307'                      => new sfWidgetFormFilterInput(),
      're307'                      => new sfWidgetFormFilterInput(),
      'pf307'                      => new sfWidgetFormFilterInput(),
      'm308'                       => new sfWidgetFormFilterInput(),
      'pt308'                      => new sfWidgetFormFilterInput(),
      'st308'                      => new sfWidgetFormFilterInput(),
      'tt308'                      => new sfWidgetFormFilterInput(),
      'pa308'                      => new sfWidgetFormFilterInput(),
      're308'                      => new sfWidgetFormFilterInput(),
      'pf308'                      => new sfWidgetFormFilterInput(),
      'm309'                       => new sfWidgetFormFilterInput(),
      'pt309'                      => new sfWidgetFormFilterInput(),
      'st309'                      => new sfWidgetFormFilterInput(),
      'tt309'                      => new sfWidgetFormFilterInput(),
      'pa309'                      => new sfWidgetFormFilterInput(),
      're309'                      => new sfWidgetFormFilterInput(),
      'pf309'                      => new sfWidgetFormFilterInput(),
      'm310'                       => new sfWidgetFormFilterInput(),
      'pt310'                      => new sfWidgetFormFilterInput(),
      'st310'                      => new sfWidgetFormFilterInput(),
      'tt310'                      => new sfWidgetFormFilterInput(),
      'pa310'                      => new sfWidgetFormFilterInput(),
      're310'                      => new sfWidgetFormFilterInput(),
      'pf310'                      => new sfWidgetFormFilterInput(),
      'm311'                       => new sfWidgetFormFilterInput(),
      'pt311'                      => new sfWidgetFormFilterInput(),
      'st311'                      => new sfWidgetFormFilterInput(),
      'tt311'                      => new sfWidgetFormFilterInput(),
      'pa311'                      => new sfWidgetFormFilterInput(),
      're311'                      => new sfWidgetFormFilterInput(),
      'pf311'                      => new sfWidgetFormFilterInput(),
      'm312'                       => new sfWidgetFormFilterInput(),
      'pt312'                      => new sfWidgetFormFilterInput(),
      'st312'                      => new sfWidgetFormFilterInput(),
      'tt312'                      => new sfWidgetFormFilterInput(),
      'pa312'                      => new sfWidgetFormFilterInput(),
      're312'                      => new sfWidgetFormFilterInput(),
      'pf312'                      => new sfWidgetFormFilterInput(),
      'm313'                       => new sfWidgetFormFilterInput(),
      'pt313'                      => new sfWidgetFormFilterInput(),
      'st313'                      => new sfWidgetFormFilterInput(),
      'tt313'                      => new sfWidgetFormFilterInput(),
      'pa313'                      => new sfWidgetFormFilterInput(),
      're313'                      => new sfWidgetFormFilterInput(),
      'pf313'                      => new sfWidgetFormFilterInput(),
      'm314'                       => new sfWidgetFormFilterInput(),
      'pt314'                      => new sfWidgetFormFilterInput(),
      'st314'                      => new sfWidgetFormFilterInput(),
      'tt314'                      => new sfWidgetFormFilterInput(),
      'pa314'                      => new sfWidgetFormFilterInput(),
      're314'                      => new sfWidgetFormFilterInput(),
      'pf314'                      => new sfWidgetFormFilterInput(),
      'm315'                       => new sfWidgetFormFilterInput(),
      'pt315'                      => new sfWidgetFormFilterInput(),
      'st315'                      => new sfWidgetFormFilterInput(),
      'tt315'                      => new sfWidgetFormFilterInput(),
      'pa315'                      => new sfWidgetFormFilterInput(),
      're315'                      => new sfWidgetFormFilterInput(),
      'pf315'                      => new sfWidgetFormFilterInput(),
      'm316'                       => new sfWidgetFormFilterInput(),
      'pt316'                      => new sfWidgetFormFilterInput(),
      'st316'                      => new sfWidgetFormFilterInput(),
      'tt316'                      => new sfWidgetFormFilterInput(),
      'pa316'                      => new sfWidgetFormFilterInput(),
      're316'                      => new sfWidgetFormFilterInput(),
      'pf316'                      => new sfWidgetFormFilterInput(),
      'm317'                       => new sfWidgetFormFilterInput(),
      'pt317'                      => new sfWidgetFormFilterInput(),
      'st317'                      => new sfWidgetFormFilterInput(),
      'tt317'                      => new sfWidgetFormFilterInput(),
      'pa317'                      => new sfWidgetFormFilterInput(),
      're317'                      => new sfWidgetFormFilterInput(),
      'pf317'                      => new sfWidgetFormFilterInput(),
      'm318'                       => new sfWidgetFormFilterInput(),
      'pt318'                      => new sfWidgetFormFilterInput(),
      'st318'                      => new sfWidgetFormFilterInput(),
      'tt318'                      => new sfWidgetFormFilterInput(),
      'pa318'                      => new sfWidgetFormFilterInput(),
      're318'                      => new sfWidgetFormFilterInput(),
      'pf318'                      => new sfWidgetFormFilterInput(),
      'm319'                       => new sfWidgetFormFilterInput(),
      'pt319'                      => new sfWidgetFormFilterInput(),
      'st319'                      => new sfWidgetFormFilterInput(),
      'tt319'                      => new sfWidgetFormFilterInput(),
      'pa319'                      => new sfWidgetFormFilterInput(),
      're319'                      => new sfWidgetFormFilterInput(),
      'pf319'                      => new sfWidgetFormFilterInput(),
      'm320'                       => new sfWidgetFormFilterInput(),
      'pt320'                      => new sfWidgetFormFilterInput(),
      'st320'                      => new sfWidgetFormFilterInput(),
      'tt320'                      => new sfWidgetFormFilterInput(),
      'pa320'                      => new sfWidgetFormFilterInput(),
      're320'                      => new sfWidgetFormFilterInput(),
      'pf320'                      => new sfWidgetFormFilterInput(),
      'm321'                       => new sfWidgetFormFilterInput(),
      'pt321'                      => new sfWidgetFormFilterInput(),
      'st321'                      => new sfWidgetFormFilterInput(),
      'tt321'                      => new sfWidgetFormFilterInput(),
      'pa321'                      => new sfWidgetFormFilterInput(),
      're321'                      => new sfWidgetFormFilterInput(),
      'pf321'                      => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'id_inscripcion'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gestion_id'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cod_distrito'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'distrito'                   => new sfValidatorPass(array('required' => false)),
      'cod_ue'                     => new sfValidatorPass(array('required' => false)),
      'desc_ue'                    => new sfValidatorPass(array('required' => false)),
      'codigo_rude'                => new sfValidatorPass(array('required' => false)),
      'carnet_identidad'           => new sfValidatorPass(array('required' => false)),
      'paterno'                    => new sfValidatorPass(array('required' => false)),
      'materno'                    => new sfValidatorPass(array('required' => false)),
      'nombre'                     => new sfValidatorPass(array('required' => false)),
      'fecha_nacimiento'           => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'genero'                     => new sfValidatorPass(array('required' => false)),
      'nivel_id'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'desc_nivel'                 => new sfValidatorPass(array('required' => false)),
      'id_grado'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'desc_grado'                 => new sfValidatorPass(array('required' => false)),
      'paralelo'                   => new sfValidatorPass(array('required' => false)),
      'desc_abrv'                  => new sfValidatorPass(array('required' => false)),
      'estado_matricula_inicio_id' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'matricula_inicio'           => new sfValidatorPass(array('required' => false)),
      'matricula_fin'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'desc_estado_matricula'      => new sfValidatorPass(array('required' => false)),
      'cod_org_curr'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'desc_modalidad'             => new sfValidatorPass(array('required' => false)),
      'cod_dependencia'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'desc_dependencia'           => new sfValidatorPass(array('required' => false)),
      'm101'                       => new sfValidatorPass(array('required' => false)),
      'pt101'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st101'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt101'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa101'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're101'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf101'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm102'                       => new sfValidatorPass(array('required' => false)),
      'pt102'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st102'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt102'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa102'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're102'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf102'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm103'                       => new sfValidatorPass(array('required' => false)),
      'pt103'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st103'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt103'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa103'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're103'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf103'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm104'                       => new sfValidatorPass(array('required' => false)),
      'pt104'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st104'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt104'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa104'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're104'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf104'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm105'                       => new sfValidatorPass(array('required' => false)),
      'pt105'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st105'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt105'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa105'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're105'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf105'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm106'                       => new sfValidatorPass(array('required' => false)),
      'pt106'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st106'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt106'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa106'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're106'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf106'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm107'                       => new sfValidatorPass(array('required' => false)),
      'pt107'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st107'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt107'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa107'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're107'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf107'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm201'                       => new sfValidatorPass(array('required' => false)),
      'pt201'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st201'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt201'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa201'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're201'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf201'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm202'                       => new sfValidatorPass(array('required' => false)),
      'pt202'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st202'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt202'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa202'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're202'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf202'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm203'                       => new sfValidatorPass(array('required' => false)),
      'pt203'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st203'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt203'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa203'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're203'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf203'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm204'                       => new sfValidatorPass(array('required' => false)),
      'pt204'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st204'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt204'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa204'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're204'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf204'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm205'                       => new sfValidatorPass(array('required' => false)),
      'pt205'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st205'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt205'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa205'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're205'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf205'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm206'                       => new sfValidatorPass(array('required' => false)),
      'pt206'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st206'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt206'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa206'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're206'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf206'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm207'                       => new sfValidatorPass(array('required' => false)),
      'pt207'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st207'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt207'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa207'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're207'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf207'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm208'                       => new sfValidatorPass(array('required' => false)),
      'pt208'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st208'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt208'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa208'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're208'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf208'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm209'                       => new sfValidatorPass(array('required' => false)),
      'pt209'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st209'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt209'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa209'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're209'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf209'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm210'                       => new sfValidatorPass(array('required' => false)),
      'pt210'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st210'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt210'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa210'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're210'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf210'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm211'                       => new sfValidatorPass(array('required' => false)),
      'pt211'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st211'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt211'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa211'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're211'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf211'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm212'                       => new sfValidatorPass(array('required' => false)),
      'pt212'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st212'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt212'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa212'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're212'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf212'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm213'                       => new sfValidatorPass(array('required' => false)),
      'pt213'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st213'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt213'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa213'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're213'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf213'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm221'                       => new sfValidatorPass(array('required' => false)),
      'pt221'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st221'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt221'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa221'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're221'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf221'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm222'                       => new sfValidatorPass(array('required' => false)),
      'pt222'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st222'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt222'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa222'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're222'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf222'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm301'                       => new sfValidatorPass(array('required' => false)),
      'pt301'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st301'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt301'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa301'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're301'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf301'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm302'                       => new sfValidatorPass(array('required' => false)),
      'pt302'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st302'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt302'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa302'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're302'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf302'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm303'                       => new sfValidatorPass(array('required' => false)),
      'pt303'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st303'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt303'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa303'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're303'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf303'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm304'                       => new sfValidatorPass(array('required' => false)),
      'pt304'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st304'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt304'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa304'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're304'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf304'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm305'                       => new sfValidatorPass(array('required' => false)),
      'pt305'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st305'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt305'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa305'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're305'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf305'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm306'                       => new sfValidatorPass(array('required' => false)),
      'pt306'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st306'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt306'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa306'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're306'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf306'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm307'                       => new sfValidatorPass(array('required' => false)),
      'pt307'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st307'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt307'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa307'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're307'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf307'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm308'                       => new sfValidatorPass(array('required' => false)),
      'pt308'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st308'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt308'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa308'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're308'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf308'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm309'                       => new sfValidatorPass(array('required' => false)),
      'pt309'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st309'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt309'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa309'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're309'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf309'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm310'                       => new sfValidatorPass(array('required' => false)),
      'pt310'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st310'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt310'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa310'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're310'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf310'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm311'                       => new sfValidatorPass(array('required' => false)),
      'pt311'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st311'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt311'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa311'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're311'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf311'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm312'                       => new sfValidatorPass(array('required' => false)),
      'pt312'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st312'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt312'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa312'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're312'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf312'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm313'                       => new sfValidatorPass(array('required' => false)),
      'pt313'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st313'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt313'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa313'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're313'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf313'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm314'                       => new sfValidatorPass(array('required' => false)),
      'pt314'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st314'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt314'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa314'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're314'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf314'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm315'                       => new sfValidatorPass(array('required' => false)),
      'pt315'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st315'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt315'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa315'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're315'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf315'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm316'                       => new sfValidatorPass(array('required' => false)),
      'pt316'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st316'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt316'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa316'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're316'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf316'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm317'                       => new sfValidatorPass(array('required' => false)),
      'pt317'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st317'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt317'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa317'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're317'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf317'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm318'                       => new sfValidatorPass(array('required' => false)),
      'pt318'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st318'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt318'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa318'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're318'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf318'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm319'                       => new sfValidatorPass(array('required' => false)),
      'pt319'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st319'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt319'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa319'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're319'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf319'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm320'                       => new sfValidatorPass(array('required' => false)),
      'pt320'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st320'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt320'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa320'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're320'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf320'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'm321'                       => new sfValidatorPass(array('required' => false)),
      'pt321'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'st321'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tt321'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pa321'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      're321'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pf321'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
    ));

    $this->widgetSchema->setNameFormat('notas_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Notas';
  }

  public function getFields()
  {
    return array(
      'id'                         => 'Number',
      'id_inscripcion'             => 'Number',
      'gestion_id'                 => 'Number',
      'cod_distrito'               => 'Number',
      'distrito'                   => 'Text',
      'cod_ue'                     => 'Text',
      'desc_ue'                    => 'Text',
      'codigo_rude'                => 'Text',
      'carnet_identidad'           => 'Text',
      'paterno'                    => 'Text',
      'materno'                    => 'Text',
      'nombre'                     => 'Text',
      'fecha_nacimiento'           => 'Date',
      'genero'                     => 'Text',
      'nivel_id'                   => 'Number',
      'desc_nivel'                 => 'Text',
      'id_grado'                   => 'Number',
      'desc_grado'                 => 'Text',
      'paralelo'                   => 'Text',
      'desc_abrv'                  => 'Text',
      'estado_matricula_inicio_id' => 'Number',
      'matricula_inicio'           => 'Text',
      'matricula_fin'              => 'Number',
      'desc_estado_matricula'      => 'Text',
      'cod_org_curr'               => 'Number',
      'desc_modalidad'             => 'Text',
      'cod_dependencia'            => 'Number',
      'desc_dependencia'           => 'Text',
      'm101'                       => 'Text',
      'pt101'                      => 'Number',
      'st101'                      => 'Number',
      'tt101'                      => 'Number',
      'pa101'                      => 'Number',
      're101'                      => 'Number',
      'pf101'                      => 'Number',
      'm102'                       => 'Text',
      'pt102'                      => 'Number',
      'st102'                      => 'Number',
      'tt102'                      => 'Number',
      'pa102'                      => 'Number',
      're102'                      => 'Number',
      'pf102'                      => 'Number',
      'm103'                       => 'Text',
      'pt103'                      => 'Number',
      'st103'                      => 'Number',
      'tt103'                      => 'Number',
      'pa103'                      => 'Number',
      're103'                      => 'Number',
      'pf103'                      => 'Number',
      'm104'                       => 'Text',
      'pt104'                      => 'Number',
      'st104'                      => 'Number',
      'tt104'                      => 'Number',
      'pa104'                      => 'Number',
      're104'                      => 'Number',
      'pf104'                      => 'Number',
      'm105'                       => 'Text',
      'pt105'                      => 'Number',
      'st105'                      => 'Number',
      'tt105'                      => 'Number',
      'pa105'                      => 'Number',
      're105'                      => 'Number',
      'pf105'                      => 'Number',
      'm106'                       => 'Text',
      'pt106'                      => 'Number',
      'st106'                      => 'Number',
      'tt106'                      => 'Number',
      'pa106'                      => 'Number',
      're106'                      => 'Number',
      'pf106'                      => 'Number',
      'm107'                       => 'Text',
      'pt107'                      => 'Number',
      'st107'                      => 'Number',
      'tt107'                      => 'Number',
      'pa107'                      => 'Number',
      're107'                      => 'Number',
      'pf107'                      => 'Number',
      'm201'                       => 'Text',
      'pt201'                      => 'Number',
      'st201'                      => 'Number',
      'tt201'                      => 'Number',
      'pa201'                      => 'Number',
      're201'                      => 'Number',
      'pf201'                      => 'Number',
      'm202'                       => 'Text',
      'pt202'                      => 'Number',
      'st202'                      => 'Number',
      'tt202'                      => 'Number',
      'pa202'                      => 'Number',
      're202'                      => 'Number',
      'pf202'                      => 'Number',
      'm203'                       => 'Text',
      'pt203'                      => 'Number',
      'st203'                      => 'Number',
      'tt203'                      => 'Number',
      'pa203'                      => 'Number',
      're203'                      => 'Number',
      'pf203'                      => 'Number',
      'm204'                       => 'Text',
      'pt204'                      => 'Number',
      'st204'                      => 'Number',
      'tt204'                      => 'Number',
      'pa204'                      => 'Number',
      're204'                      => 'Number',
      'pf204'                      => 'Number',
      'm205'                       => 'Text',
      'pt205'                      => 'Number',
      'st205'                      => 'Number',
      'tt205'                      => 'Number',
      'pa205'                      => 'Number',
      're205'                      => 'Number',
      'pf205'                      => 'Number',
      'm206'                       => 'Text',
      'pt206'                      => 'Number',
      'st206'                      => 'Number',
      'tt206'                      => 'Number',
      'pa206'                      => 'Number',
      're206'                      => 'Number',
      'pf206'                      => 'Number',
      'm207'                       => 'Text',
      'pt207'                      => 'Number',
      'st207'                      => 'Number',
      'tt207'                      => 'Number',
      'pa207'                      => 'Number',
      're207'                      => 'Number',
      'pf207'                      => 'Number',
      'm208'                       => 'Text',
      'pt208'                      => 'Number',
      'st208'                      => 'Number',
      'tt208'                      => 'Number',
      'pa208'                      => 'Number',
      're208'                      => 'Number',
      'pf208'                      => 'Number',
      'm209'                       => 'Text',
      'pt209'                      => 'Number',
      'st209'                      => 'Number',
      'tt209'                      => 'Number',
      'pa209'                      => 'Number',
      're209'                      => 'Number',
      'pf209'                      => 'Number',
      'm210'                       => 'Text',
      'pt210'                      => 'Number',
      'st210'                      => 'Number',
      'tt210'                      => 'Number',
      'pa210'                      => 'Number',
      're210'                      => 'Number',
      'pf210'                      => 'Number',
      'm211'                       => 'Text',
      'pt211'                      => 'Number',
      'st211'                      => 'Number',
      'tt211'                      => 'Number',
      'pa211'                      => 'Number',
      're211'                      => 'Number',
      'pf211'                      => 'Number',
      'm212'                       => 'Text',
      'pt212'                      => 'Number',
      'st212'                      => 'Number',
      'tt212'                      => 'Number',
      'pa212'                      => 'Number',
      're212'                      => 'Number',
      'pf212'                      => 'Number',
      'm213'                       => 'Text',
      'pt213'                      => 'Number',
      'st213'                      => 'Number',
      'tt213'                      => 'Number',
      'pa213'                      => 'Number',
      're213'                      => 'Number',
      'pf213'                      => 'Number',
      'm221'                       => 'Text',
      'pt221'                      => 'Number',
      'st221'                      => 'Number',
      'tt221'                      => 'Number',
      'pa221'                      => 'Number',
      're221'                      => 'Number',
      'pf221'                      => 'Number',
      'm222'                       => 'Text',
      'pt222'                      => 'Number',
      'st222'                      => 'Number',
      'tt222'                      => 'Number',
      'pa222'                      => 'Number',
      're222'                      => 'Number',
      'pf222'                      => 'Number',
      'm301'                       => 'Text',
      'pt301'                      => 'Number',
      'st301'                      => 'Number',
      'tt301'                      => 'Number',
      'pa301'                      => 'Number',
      're301'                      => 'Number',
      'pf301'                      => 'Number',
      'm302'                       => 'Text',
      'pt302'                      => 'Number',
      'st302'                      => 'Number',
      'tt302'                      => 'Number',
      'pa302'                      => 'Number',
      're302'                      => 'Number',
      'pf302'                      => 'Number',
      'm303'                       => 'Text',
      'pt303'                      => 'Number',
      'st303'                      => 'Number',
      'tt303'                      => 'Number',
      'pa303'                      => 'Number',
      're303'                      => 'Number',
      'pf303'                      => 'Number',
      'm304'                       => 'Text',
      'pt304'                      => 'Number',
      'st304'                      => 'Number',
      'tt304'                      => 'Number',
      'pa304'                      => 'Number',
      're304'                      => 'Number',
      'pf304'                      => 'Number',
      'm305'                       => 'Text',
      'pt305'                      => 'Number',
      'st305'                      => 'Number',
      'tt305'                      => 'Number',
      'pa305'                      => 'Number',
      're305'                      => 'Number',
      'pf305'                      => 'Number',
      'm306'                       => 'Text',
      'pt306'                      => 'Number',
      'st306'                      => 'Number',
      'tt306'                      => 'Number',
      'pa306'                      => 'Number',
      're306'                      => 'Number',
      'pf306'                      => 'Number',
      'm307'                       => 'Text',
      'pt307'                      => 'Number',
      'st307'                      => 'Number',
      'tt307'                      => 'Number',
      'pa307'                      => 'Number',
      're307'                      => 'Number',
      'pf307'                      => 'Number',
      'm308'                       => 'Text',
      'pt308'                      => 'Number',
      'st308'                      => 'Number',
      'tt308'                      => 'Number',
      'pa308'                      => 'Number',
      're308'                      => 'Number',
      'pf308'                      => 'Number',
      'm309'                       => 'Text',
      'pt309'                      => 'Number',
      'st309'                      => 'Number',
      'tt309'                      => 'Number',
      'pa309'                      => 'Number',
      're309'                      => 'Number',
      'pf309'                      => 'Number',
      'm310'                       => 'Text',
      'pt310'                      => 'Number',
      'st310'                      => 'Number',
      'tt310'                      => 'Number',
      'pa310'                      => 'Number',
      're310'                      => 'Number',
      'pf310'                      => 'Number',
      'm311'                       => 'Text',
      'pt311'                      => 'Number',
      'st311'                      => 'Number',
      'tt311'                      => 'Number',
      'pa311'                      => 'Number',
      're311'                      => 'Number',
      'pf311'                      => 'Number',
      'm312'                       => 'Text',
      'pt312'                      => 'Number',
      'st312'                      => 'Number',
      'tt312'                      => 'Number',
      'pa312'                      => 'Number',
      're312'                      => 'Number',
      'pf312'                      => 'Number',
      'm313'                       => 'Text',
      'pt313'                      => 'Number',
      'st313'                      => 'Number',
      'tt313'                      => 'Number',
      'pa313'                      => 'Number',
      're313'                      => 'Number',
      'pf313'                      => 'Number',
      'm314'                       => 'Text',
      'pt314'                      => 'Number',
      'st314'                      => 'Number',
      'tt314'                      => 'Number',
      'pa314'                      => 'Number',
      're314'                      => 'Number',
      'pf314'                      => 'Number',
      'm315'                       => 'Text',
      'pt315'                      => 'Number',
      'st315'                      => 'Number',
      'tt315'                      => 'Number',
      'pa315'                      => 'Number',
      're315'                      => 'Number',
      'pf315'                      => 'Number',
      'm316'                       => 'Text',
      'pt316'                      => 'Number',
      'st316'                      => 'Number',
      'tt316'                      => 'Number',
      'pa316'                      => 'Number',
      're316'                      => 'Number',
      'pf316'                      => 'Number',
      'm317'                       => 'Text',
      'pt317'                      => 'Number',
      'st317'                      => 'Number',
      'tt317'                      => 'Number',
      'pa317'                      => 'Number',
      're317'                      => 'Number',
      'pf317'                      => 'Number',
      'm318'                       => 'Text',
      'pt318'                      => 'Number',
      'st318'                      => 'Number',
      'tt318'                      => 'Number',
      'pa318'                      => 'Number',
      're318'                      => 'Number',
      'pf318'                      => 'Number',
      'm319'                       => 'Text',
      'pt319'                      => 'Number',
      'st319'                      => 'Number',
      'tt319'                      => 'Number',
      'pa319'                      => 'Number',
      're319'                      => 'Number',
      'pf319'                      => 'Number',
      'm320'                       => 'Text',
      'pt320'                      => 'Number',
      'st320'                      => 'Number',
      'tt320'                      => 'Number',
      'pa320'                      => 'Number',
      're320'                      => 'Number',
      'pf320'                      => 'Number',
      'm321'                       => 'Text',
      'pt321'                      => 'Number',
      'st321'                      => 'Number',
      'tt321'                      => 'Number',
      'pa321'                      => 'Number',
      're321'                      => 'Number',
      'pf321'                      => 'Number',
    );
  }
}
