<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatPlaItems', 'doctrine');

/**
 * BaseDatPlaItems
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $servicio
 * @property string $item
 * @property integer $gestion_id
 * @property integer $cargo_id
 * @property string $programa
 * @property integer $horas
 * @property integer $mes
 * @property ClaCargo $ClaCargo
 * @property ClaGestion $ClaGestion
 * @property Doctrine_Collection $CtrPlaItems
 * @property Doctrine_Collection $CtrPlaItems_3
 * @property Doctrine_Collection $CtrPlaItems_4
 * @property Doctrine_Collection $RelAdministrativoItems
 * @property Doctrine_Collection $RelAdministrativoItems_2
 * @property Doctrine_Collection $RelAdministrativoItems_3
 * @property Doctrine_Collection $RelDocenteItems
 * @property Doctrine_Collection $RelDocenteItems_2
 * @property Doctrine_Collection $RelDocenteItems_3
 * 
 * @method string              getServicio()                 Returns the current record's "servicio" value
 * @method string              getItem()                     Returns the current record's "item" value
 * @method integer             getGestionId()                Returns the current record's "gestion_id" value
 * @method integer             getCargoId()                  Returns the current record's "cargo_id" value
 * @method string              getPrograma()                 Returns the current record's "programa" value
 * @method integer             getHoras()                    Returns the current record's "horas" value
 * @method integer             getMes()                      Returns the current record's "mes" value
 * @method ClaCargo            getClaCargo()                 Returns the current record's "ClaCargo" value
 * @method ClaGestion          getClaGestion()               Returns the current record's "ClaGestion" value
 * @method Doctrine_Collection getCtrPlaItems()              Returns the current record's "CtrPlaItems" collection
 * @method Doctrine_Collection getCtrPlaItems3()             Returns the current record's "CtrPlaItems_3" collection
 * @method Doctrine_Collection getCtrPlaItems4()             Returns the current record's "CtrPlaItems_4" collection
 * @method Doctrine_Collection getRelAdministrativoItems()   Returns the current record's "RelAdministrativoItems" collection
 * @method Doctrine_Collection getRelAdministrativoItems2()  Returns the current record's "RelAdministrativoItems_2" collection
 * @method Doctrine_Collection getRelAdministrativoItems3()  Returns the current record's "RelAdministrativoItems_3" collection
 * @method Doctrine_Collection getRelDocenteItems()          Returns the current record's "RelDocenteItems" collection
 * @method Doctrine_Collection getRelDocenteItems2()         Returns the current record's "RelDocenteItems_2" collection
 * @method Doctrine_Collection getRelDocenteItems3()         Returns the current record's "RelDocenteItems_3" collection
 * @method DatPlaItems         setServicio()                 Sets the current record's "servicio" value
 * @method DatPlaItems         setItem()                     Sets the current record's "item" value
 * @method DatPlaItems         setGestionId()                Sets the current record's "gestion_id" value
 * @method DatPlaItems         setCargoId()                  Sets the current record's "cargo_id" value
 * @method DatPlaItems         setPrograma()                 Sets the current record's "programa" value
 * @method DatPlaItems         setHoras()                    Sets the current record's "horas" value
 * @method DatPlaItems         setMes()                      Sets the current record's "mes" value
 * @method DatPlaItems         setClaCargo()                 Sets the current record's "ClaCargo" value
 * @method DatPlaItems         setClaGestion()               Sets the current record's "ClaGestion" value
 * @method DatPlaItems         setCtrPlaItems()              Sets the current record's "CtrPlaItems" collection
 * @method DatPlaItems         setCtrPlaItems3()             Sets the current record's "CtrPlaItems_3" collection
 * @method DatPlaItems         setCtrPlaItems4()             Sets the current record's "CtrPlaItems_4" collection
 * @method DatPlaItems         setRelAdministrativoItems()   Sets the current record's "RelAdministrativoItems" collection
 * @method DatPlaItems         setRelAdministrativoItems2()  Sets the current record's "RelAdministrativoItems_2" collection
 * @method DatPlaItems         setRelAdministrativoItems3()  Sets the current record's "RelAdministrativoItems_3" collection
 * @method DatPlaItems         setRelDocenteItems()          Sets the current record's "RelDocenteItems" collection
 * @method DatPlaItems         setRelDocenteItems2()         Sets the current record's "RelDocenteItems_2" collection
 * @method DatPlaItems         setRelDocenteItems3()         Sets the current record's "RelDocenteItems_3" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatPlaItems extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_pla_items');
        $this->hasColumn('servicio', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('item', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '5',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('cargo_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('programa', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('horas', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('mes', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaCargo', array(
             'local' => 'cargo_id',
             'foreign' => 'id_cargo'));

        $this->hasOne('ClaGestion', array(
             'local' => 'gestion_id',
             'foreign' => 'id_gestion'));

        $this->hasMany('CtrPlaItems', array(
             'local' => 'servicio',
             'foreign' => 'servicio'));

        $this->hasMany('CtrPlaItems as CtrPlaItems_3', array(
             'local' => 'item',
             'foreign' => 'item'));

        $this->hasMany('CtrPlaItems as CtrPlaItems_4', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasMany('RelAdministrativoItems', array(
             'local' => 'servicio',
             'foreign' => 'servicio'));

        $this->hasMany('RelAdministrativoItems as RelAdministrativoItems_2', array(
             'local' => 'item',
             'foreign' => 'item_id'));

        $this->hasMany('RelAdministrativoItems as RelAdministrativoItems_3', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasMany('RelDocenteItems', array(
             'local' => 'servicio',
             'foreign' => 'servicio'));

        $this->hasMany('RelDocenteItems as RelDocenteItems_2', array(
             'local' => 'item',
             'foreign' => 'item_id'));

        $this->hasMany('RelDocenteItems as RelDocenteItems_3', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));
    }
}