<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaIdioma', 'doctrine');

/**
 * BaseClaIdioma
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_idioma
 * @property string $desc_idioma
 * @property Doctrine_Collection $DatRdeDatosapoderado
 * @property Doctrine_Collection $DatRdeEstudiante
 * @property Doctrine_Collection $DatRdeSocioEconomico
 * @property Doctrine_Collection $DatRdeSocioEconomico_5
 * @property Doctrine_Collection $DatRdeSocioEconomico_6
 * @property Doctrine_Collection $DatRdeSocioEconomico_7
 * @property Doctrine_Collection $DatRdeSocioEconomico_8
 * @property Doctrine_Collection $DatRdeSocioEconomico_9
 * @property Doctrine_Collection $DatSieCurso
 * @property Doctrine_Collection $DatSieCurso_6
 * @property Doctrine_Collection $DatSieCurso_7
 * @property Doctrine_Collection $DatSieCurso_8
 * @property Doctrine_Collection $DatSieCurso_9
 * @property Doctrine_Collection $HisRdeEstudiante
 * @property Doctrine_Collection $HisRdeEstudianteIdioma
 * @property Doctrine_Collection $RelRdeEstudianteIdioma
 * @property Doctrine_Collection $SdatRdeDatosapoderado
 * @property Doctrine_Collection $SdatRdeSocioEconomico
 * @property Doctrine_Collection $SdatRdeSocioEconomico_5
 * @property Doctrine_Collection $SdatRdeSocioEconomico_6
 * @property Doctrine_Collection $SdatRdeSocioEconomico_7
 * @property Doctrine_Collection $SdatRdeSocioEconomico_8
 * @property Doctrine_Collection $SdatRdeSocioEconomico_9
 * @property Doctrine_Collection $SdatSieCurso
 * @property Doctrine_Collection $SdatSieCurso_6
 * @property Doctrine_Collection $SdatSieCurso_7
 * @property Doctrine_Collection $SdatSieCurso_8
 * @property Doctrine_Collection $SdatSieCurso_9
 * 
 * @method integer             getIdIdioma()                Returns the current record's "id_idioma" value
 * @method string              getDescIdioma()              Returns the current record's "desc_idioma" value
 * @method Doctrine_Collection getDatRdeDatosapoderado()    Returns the current record's "DatRdeDatosapoderado" collection
 * @method Doctrine_Collection getDatRdeEstudiante()        Returns the current record's "DatRdeEstudiante" collection
 * @method Doctrine_Collection getDatRdeSocioEconomico()    Returns the current record's "DatRdeSocioEconomico" collection
 * @method Doctrine_Collection getDatRdeSocioEconomico5()   Returns the current record's "DatRdeSocioEconomico_5" collection
 * @method Doctrine_Collection getDatRdeSocioEconomico6()   Returns the current record's "DatRdeSocioEconomico_6" collection
 * @method Doctrine_Collection getDatRdeSocioEconomico7()   Returns the current record's "DatRdeSocioEconomico_7" collection
 * @method Doctrine_Collection getDatRdeSocioEconomico8()   Returns the current record's "DatRdeSocioEconomico_8" collection
 * @method Doctrine_Collection getDatRdeSocioEconomico9()   Returns the current record's "DatRdeSocioEconomico_9" collection
 * @method Doctrine_Collection getDatSieCurso()             Returns the current record's "DatSieCurso" collection
 * @method Doctrine_Collection getDatSieCurso6()            Returns the current record's "DatSieCurso_6" collection
 * @method Doctrine_Collection getDatSieCurso7()            Returns the current record's "DatSieCurso_7" collection
 * @method Doctrine_Collection getDatSieCurso8()            Returns the current record's "DatSieCurso_8" collection
 * @method Doctrine_Collection getDatSieCurso9()            Returns the current record's "DatSieCurso_9" collection
 * @method Doctrine_Collection getHisRdeEstudiante()        Returns the current record's "HisRdeEstudiante" collection
 * @method Doctrine_Collection getHisRdeEstudianteIdioma()  Returns the current record's "HisRdeEstudianteIdioma" collection
 * @method Doctrine_Collection getRelRdeEstudianteIdioma()  Returns the current record's "RelRdeEstudianteIdioma" collection
 * @method Doctrine_Collection getSdatRdeDatosapoderado()   Returns the current record's "SdatRdeDatosapoderado" collection
 * @method Doctrine_Collection getSdatRdeSocioEconomico()   Returns the current record's "SdatRdeSocioEconomico" collection
 * @method Doctrine_Collection getSdatRdeSocioEconomico5()  Returns the current record's "SdatRdeSocioEconomico_5" collection
 * @method Doctrine_Collection getSdatRdeSocioEconomico6()  Returns the current record's "SdatRdeSocioEconomico_6" collection
 * @method Doctrine_Collection getSdatRdeSocioEconomico7()  Returns the current record's "SdatRdeSocioEconomico_7" collection
 * @method Doctrine_Collection getSdatRdeSocioEconomico8()  Returns the current record's "SdatRdeSocioEconomico_8" collection
 * @method Doctrine_Collection getSdatRdeSocioEconomico9()  Returns the current record's "SdatRdeSocioEconomico_9" collection
 * @method Doctrine_Collection getSdatSieCurso()            Returns the current record's "SdatSieCurso" collection
 * @method Doctrine_Collection getSdatSieCurso6()           Returns the current record's "SdatSieCurso_6" collection
 * @method Doctrine_Collection getSdatSieCurso7()           Returns the current record's "SdatSieCurso_7" collection
 * @method Doctrine_Collection getSdatSieCurso8()           Returns the current record's "SdatSieCurso_8" collection
 * @method Doctrine_Collection getSdatSieCurso9()           Returns the current record's "SdatSieCurso_9" collection
 * @method ClaIdioma           setIdIdioma()                Sets the current record's "id_idioma" value
 * @method ClaIdioma           setDescIdioma()              Sets the current record's "desc_idioma" value
 * @method ClaIdioma           setDatRdeDatosapoderado()    Sets the current record's "DatRdeDatosapoderado" collection
 * @method ClaIdioma           setDatRdeEstudiante()        Sets the current record's "DatRdeEstudiante" collection
 * @method ClaIdioma           setDatRdeSocioEconomico()    Sets the current record's "DatRdeSocioEconomico" collection
 * @method ClaIdioma           setDatRdeSocioEconomico5()   Sets the current record's "DatRdeSocioEconomico_5" collection
 * @method ClaIdioma           setDatRdeSocioEconomico6()   Sets the current record's "DatRdeSocioEconomico_6" collection
 * @method ClaIdioma           setDatRdeSocioEconomico7()   Sets the current record's "DatRdeSocioEconomico_7" collection
 * @method ClaIdioma           setDatRdeSocioEconomico8()   Sets the current record's "DatRdeSocioEconomico_8" collection
 * @method ClaIdioma           setDatRdeSocioEconomico9()   Sets the current record's "DatRdeSocioEconomico_9" collection
 * @method ClaIdioma           setDatSieCurso()             Sets the current record's "DatSieCurso" collection
 * @method ClaIdioma           setDatSieCurso6()            Sets the current record's "DatSieCurso_6" collection
 * @method ClaIdioma           setDatSieCurso7()            Sets the current record's "DatSieCurso_7" collection
 * @method ClaIdioma           setDatSieCurso8()            Sets the current record's "DatSieCurso_8" collection
 * @method ClaIdioma           setDatSieCurso9()            Sets the current record's "DatSieCurso_9" collection
 * @method ClaIdioma           setHisRdeEstudiante()        Sets the current record's "HisRdeEstudiante" collection
 * @method ClaIdioma           setHisRdeEstudianteIdioma()  Sets the current record's "HisRdeEstudianteIdioma" collection
 * @method ClaIdioma           setRelRdeEstudianteIdioma()  Sets the current record's "RelRdeEstudianteIdioma" collection
 * @method ClaIdioma           setSdatRdeDatosapoderado()   Sets the current record's "SdatRdeDatosapoderado" collection
 * @method ClaIdioma           setSdatRdeSocioEconomico()   Sets the current record's "SdatRdeSocioEconomico" collection
 * @method ClaIdioma           setSdatRdeSocioEconomico5()  Sets the current record's "SdatRdeSocioEconomico_5" collection
 * @method ClaIdioma           setSdatRdeSocioEconomico6()  Sets the current record's "SdatRdeSocioEconomico_6" collection
 * @method ClaIdioma           setSdatRdeSocioEconomico7()  Sets the current record's "SdatRdeSocioEconomico_7" collection
 * @method ClaIdioma           setSdatRdeSocioEconomico8()  Sets the current record's "SdatRdeSocioEconomico_8" collection
 * @method ClaIdioma           setSdatRdeSocioEconomico9()  Sets the current record's "SdatRdeSocioEconomico_9" collection
 * @method ClaIdioma           setSdatSieCurso()            Sets the current record's "SdatSieCurso" collection
 * @method ClaIdioma           setSdatSieCurso6()           Sets the current record's "SdatSieCurso_6" collection
 * @method ClaIdioma           setSdatSieCurso7()           Sets the current record's "SdatSieCurso_7" collection
 * @method ClaIdioma           setSdatSieCurso8()           Sets the current record's "SdatSieCurso_8" collection
 * @method ClaIdioma           setSdatSieCurso9()           Sets the current record's "SdatSieCurso_9" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaIdioma extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_idioma');
        $this->hasColumn('id_idioma', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('desc_idioma', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DatRdeDatosapoderado', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma_id'));

        $this->hasMany('DatRdeEstudiante', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma_materno_id'));

        $this->hasMany('DatRdeSocioEconomico', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma1_id'));

        $this->hasMany('DatRdeSocioEconomico as DatRdeSocioEconomico_5', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma2_id'));

        $this->hasMany('DatRdeSocioEconomico as DatRdeSocioEconomico_6', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma3_id'));

        $this->hasMany('DatRdeSocioEconomico as DatRdeSocioEconomico_7', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma4_id'));

        $this->hasMany('DatRdeSocioEconomico as DatRdeSocioEconomico_8', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma5_id'));

        $this->hasMany('DatRdeSocioEconomico as DatRdeSocioEconomico_9', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma6_id'));

        $this->hasMany('DatSieCurso', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma_mas_hablado'));

        $this->hasMany('DatSieCurso as DatSieCurso_6', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma_reg_hablado'));

        $this->hasMany('DatSieCurso as DatSieCurso_7', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma_men_hablado'));

        $this->hasMany('DatSieCurso as DatSieCurso_8', array(
             'local' => 'id_idioma',
             'foreign' => 'pri_len_ensenanza'));

        $this->hasMany('DatSieCurso as DatSieCurso_9', array(
             'local' => 'id_idioma',
             'foreign' => 'seg_len_ensenanza'));

        $this->hasMany('HisRdeEstudiante', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma_materno_id'));

        $this->hasMany('HisRdeEstudianteIdioma', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma_id'));

        $this->hasMany('RelRdeEstudianteIdioma', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma_id'));

        $this->hasMany('SdatRdeDatosapoderado', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma_id'));

        $this->hasMany('SdatRdeSocioEconomico', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma1_id'));

        $this->hasMany('SdatRdeSocioEconomico as SdatRdeSocioEconomico_5', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma2_id'));

        $this->hasMany('SdatRdeSocioEconomico as SdatRdeSocioEconomico_6', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma3_id'));

        $this->hasMany('SdatRdeSocioEconomico as SdatRdeSocioEconomico_7', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma4_id'));

        $this->hasMany('SdatRdeSocioEconomico as SdatRdeSocioEconomico_8', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma5_id'));

        $this->hasMany('SdatRdeSocioEconomico as SdatRdeSocioEconomico_9', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma6_id'));

        $this->hasMany('SdatSieCurso', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma_mas_hablado'));

        $this->hasMany('SdatSieCurso as SdatSieCurso_6', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma_reg_hablado'));

        $this->hasMany('SdatSieCurso as SdatSieCurso_7', array(
             'local' => 'id_idioma',
             'foreign' => 'idioma_men_hablado'));

        $this->hasMany('SdatSieCurso as SdatSieCurso_8', array(
             'local' => 'id_idioma',
             'foreign' => 'pri_len_ensenanza'));

        $this->hasMany('SdatSieCurso as SdatSieCurso_9', array(
             'local' => 'id_idioma',
             'foreign' => 'seg_len_ensenanza'));
    }
}