<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatRueAcreditacion', 'doctrine');

/**
 * BaseDatRueAcreditacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cod_ue_id
 * @property integer $acreditacion_id
 * @property DatRueUnidadEducativa $DatRueUnidadEducativa
 * 
 * @method string                getCodUeId()               Returns the current record's "cod_ue_id" value
 * @method integer               getAcreditacionId()        Returns the current record's "acreditacion_id" value
 * @method DatRueUnidadEducativa getDatRueUnidadEducativa() Returns the current record's "DatRueUnidadEducativa" value
 * @method DatRueAcreditacion    setCodUeId()               Sets the current record's "cod_ue_id" value
 * @method DatRueAcreditacion    setAcreditacionId()        Sets the current record's "acreditacion_id" value
 * @method DatRueAcreditacion    setDatRueUnidadEducativa() Sets the current record's "DatRueUnidadEducativa" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatRueAcreditacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_rue_acreditacion');
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('acreditacion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DatRueUnidadEducativa', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue'));
    }
}