<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TmpSlnFormal2011', 'doctrine');

/**
 * BaseTmpSlnFormal2011
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $gestion_id
 * @property string $cod_ue_id
 * @property string $codigo_rude_id
 * @property integer $id_inscripcion
 * @property integer $curso_oferta_id
 * @property integer $nivel_id
 * @property integer $ciclo_id
 * @property integer $grado_id
 * @property string $paralelo
 * @property integer $turno_id
 * @property integer $nivel_curso_oferta
 * @property integer $ciclo_curso_oferta
 * @property integer $grado_curso_oferta
 * @property string $paralelo_curso_oferta
 * @property integer $turno_curso_oferta
 * @property integer $primer_trimestre
 * @property integer $segundo_trimestre
 * @property integer $tercer_trimestre
 * @property integer $promedio_anual
 * @property integer $reforzamiento
 * @property integer $promedio_final
 * @property string $primer_eval
 * @property string $segundo_eval
 * @property string $tercer_eval
 * @property integer $primer_dias_trab
 * @property integer $segundo_dias_trab
 * @property integer $tercer_dias_trab
 * @property integer $reforzamiento_dias_trab
 * @property integer $primer_faltas_licencia
 * @property integer $segundo_faltas_licencia
 * @property integer $tecer_faltas_licencia
 * @property integer $primer_faltas_sin_licencia
 * @property integer $segundo_faltas_sin_licencia
 * @property integer $tercer_faltas_sin_licencia
 * @property timestamp $fecha_actualizacion
 * @property integer $usuario_id
 * 
 * @method integer          getId()                          Returns the current record's "id" value
 * @method integer          getGestionId()                   Returns the current record's "gestion_id" value
 * @method string           getCodUeId()                     Returns the current record's "cod_ue_id" value
 * @method string           getCodigoRudeId()                Returns the current record's "codigo_rude_id" value
 * @method integer          getIdInscripcion()               Returns the current record's "id_inscripcion" value
 * @method integer          getCursoOfertaId()               Returns the current record's "curso_oferta_id" value
 * @method integer          getNivelId()                     Returns the current record's "nivel_id" value
 * @method integer          getCicloId()                     Returns the current record's "ciclo_id" value
 * @method integer          getGradoId()                     Returns the current record's "grado_id" value
 * @method string           getParalelo()                    Returns the current record's "paralelo" value
 * @method integer          getTurnoId()                     Returns the current record's "turno_id" value
 * @method integer          getNivelCursoOferta()            Returns the current record's "nivel_curso_oferta" value
 * @method integer          getCicloCursoOferta()            Returns the current record's "ciclo_curso_oferta" value
 * @method integer          getGradoCursoOferta()            Returns the current record's "grado_curso_oferta" value
 * @method string           getParaleloCursoOferta()         Returns the current record's "paralelo_curso_oferta" value
 * @method integer          getTurnoCursoOferta()            Returns the current record's "turno_curso_oferta" value
 * @method integer          getPrimerTrimestre()             Returns the current record's "primer_trimestre" value
 * @method integer          getSegundoTrimestre()            Returns the current record's "segundo_trimestre" value
 * @method integer          getTercerTrimestre()             Returns the current record's "tercer_trimestre" value
 * @method integer          getPromedioAnual()               Returns the current record's "promedio_anual" value
 * @method integer          getReforzamiento()               Returns the current record's "reforzamiento" value
 * @method integer          getPromedioFinal()               Returns the current record's "promedio_final" value
 * @method string           getPrimerEval()                  Returns the current record's "primer_eval" value
 * @method string           getSegundoEval()                 Returns the current record's "segundo_eval" value
 * @method string           getTercerEval()                  Returns the current record's "tercer_eval" value
 * @method integer          getPrimerDiasTrab()              Returns the current record's "primer_dias_trab" value
 * @method integer          getSegundoDiasTrab()             Returns the current record's "segundo_dias_trab" value
 * @method integer          getTercerDiasTrab()              Returns the current record's "tercer_dias_trab" value
 * @method integer          getReforzamientoDiasTrab()       Returns the current record's "reforzamiento_dias_trab" value
 * @method integer          getPrimerFaltasLicencia()        Returns the current record's "primer_faltas_licencia" value
 * @method integer          getSegundoFaltasLicencia()       Returns the current record's "segundo_faltas_licencia" value
 * @method integer          getTecerFaltasLicencia()         Returns the current record's "tecer_faltas_licencia" value
 * @method integer          getPrimerFaltasSinLicencia()     Returns the current record's "primer_faltas_sin_licencia" value
 * @method integer          getSegundoFaltasSinLicencia()    Returns the current record's "segundo_faltas_sin_licencia" value
 * @method integer          getTercerFaltasSinLicencia()     Returns the current record's "tercer_faltas_sin_licencia" value
 * @method timestamp        getFechaActualizacion()          Returns the current record's "fecha_actualizacion" value
 * @method integer          getUsuarioId()                   Returns the current record's "usuario_id" value
 * @method TmpSlnFormal2011 setId()                          Sets the current record's "id" value
 * @method TmpSlnFormal2011 setGestionId()                   Sets the current record's "gestion_id" value
 * @method TmpSlnFormal2011 setCodUeId()                     Sets the current record's "cod_ue_id" value
 * @method TmpSlnFormal2011 setCodigoRudeId()                Sets the current record's "codigo_rude_id" value
 * @method TmpSlnFormal2011 setIdInscripcion()               Sets the current record's "id_inscripcion" value
 * @method TmpSlnFormal2011 setCursoOfertaId()               Sets the current record's "curso_oferta_id" value
 * @method TmpSlnFormal2011 setNivelId()                     Sets the current record's "nivel_id" value
 * @method TmpSlnFormal2011 setCicloId()                     Sets the current record's "ciclo_id" value
 * @method TmpSlnFormal2011 setGradoId()                     Sets the current record's "grado_id" value
 * @method TmpSlnFormal2011 setParalelo()                    Sets the current record's "paralelo" value
 * @method TmpSlnFormal2011 setTurnoId()                     Sets the current record's "turno_id" value
 * @method TmpSlnFormal2011 setNivelCursoOferta()            Sets the current record's "nivel_curso_oferta" value
 * @method TmpSlnFormal2011 setCicloCursoOferta()            Sets the current record's "ciclo_curso_oferta" value
 * @method TmpSlnFormal2011 setGradoCursoOferta()            Sets the current record's "grado_curso_oferta" value
 * @method TmpSlnFormal2011 setParaleloCursoOferta()         Sets the current record's "paralelo_curso_oferta" value
 * @method TmpSlnFormal2011 setTurnoCursoOferta()            Sets the current record's "turno_curso_oferta" value
 * @method TmpSlnFormal2011 setPrimerTrimestre()             Sets the current record's "primer_trimestre" value
 * @method TmpSlnFormal2011 setSegundoTrimestre()            Sets the current record's "segundo_trimestre" value
 * @method TmpSlnFormal2011 setTercerTrimestre()             Sets the current record's "tercer_trimestre" value
 * @method TmpSlnFormal2011 setPromedioAnual()               Sets the current record's "promedio_anual" value
 * @method TmpSlnFormal2011 setReforzamiento()               Sets the current record's "reforzamiento" value
 * @method TmpSlnFormal2011 setPromedioFinal()               Sets the current record's "promedio_final" value
 * @method TmpSlnFormal2011 setPrimerEval()                  Sets the current record's "primer_eval" value
 * @method TmpSlnFormal2011 setSegundoEval()                 Sets the current record's "segundo_eval" value
 * @method TmpSlnFormal2011 setTercerEval()                  Sets the current record's "tercer_eval" value
 * @method TmpSlnFormal2011 setPrimerDiasTrab()              Sets the current record's "primer_dias_trab" value
 * @method TmpSlnFormal2011 setSegundoDiasTrab()             Sets the current record's "segundo_dias_trab" value
 * @method TmpSlnFormal2011 setTercerDiasTrab()              Sets the current record's "tercer_dias_trab" value
 * @method TmpSlnFormal2011 setReforzamientoDiasTrab()       Sets the current record's "reforzamiento_dias_trab" value
 * @method TmpSlnFormal2011 setPrimerFaltasLicencia()        Sets the current record's "primer_faltas_licencia" value
 * @method TmpSlnFormal2011 setSegundoFaltasLicencia()       Sets the current record's "segundo_faltas_licencia" value
 * @method TmpSlnFormal2011 setTecerFaltasLicencia()         Sets the current record's "tecer_faltas_licencia" value
 * @method TmpSlnFormal2011 setPrimerFaltasSinLicencia()     Sets the current record's "primer_faltas_sin_licencia" value
 * @method TmpSlnFormal2011 setSegundoFaltasSinLicencia()    Sets the current record's "segundo_faltas_sin_licencia" value
 * @method TmpSlnFormal2011 setTercerFaltasSinLicencia()     Sets the current record's "tercer_faltas_sin_licencia" value
 * @method TmpSlnFormal2011 setFechaActualizacion()          Sets the current record's "fecha_actualizacion" value
 * @method TmpSlnFormal2011 setUsuarioId()                   Sets the current record's "usuario_id" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTmpSlnFormal2011 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tmp_sln_formal2011');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('codigo_rude_id', 'string', 18, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '18',
             ));
        $this->hasColumn('id_inscripcion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('curso_oferta_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('nivel_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('ciclo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('grado_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('paralelo', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('turno_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('nivel_curso_oferta', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('ciclo_curso_oferta', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('grado_curso_oferta', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('paralelo_curso_oferta', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('turno_curso_oferta', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('primer_trimestre', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('segundo_trimestre', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('tercer_trimestre', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('promedio_anual', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('reforzamiento', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('promedio_final', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('primer_eval', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '200',
             ));
        $this->hasColumn('segundo_eval', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '200',
             ));
        $this->hasColumn('tercer_eval', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '200',
             ));
        $this->hasColumn('primer_dias_trab', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('segundo_dias_trab', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('tercer_dias_trab', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('reforzamiento_dias_trab', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('primer_faltas_licencia', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('segundo_faltas_licencia', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('tecer_faltas_licencia', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('primer_faltas_sin_licencia', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('segundo_faltas_sin_licencia', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('tercer_faltas_sin_licencia', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('fecha_actualizacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}