<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatRueNivel', 'doctrine');

/**
 * BaseDatRueNivel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cod_ue_id
 * @property integer $nivel_id
 * @property integer $acreditacion_id
 * @property integer $certificado
 * @property ClaCicloAcreditacion $ClaCicloAcreditacion
 * @property ClaCicloAcreditacion $ClaCicloAcreditacion_2
 * @property DatRueUnidadEducativa $DatRueUnidadEducativa
 * @property Doctrine_Collection $DatSlnEstudios
 * @property Doctrine_Collection $DatSlnEstudios_2
 * 
 * @method string                getCodUeId()                Returns the current record's "cod_ue_id" value
 * @method integer               getNivelId()                Returns the current record's "nivel_id" value
 * @method integer               getAcreditacionId()         Returns the current record's "acreditacion_id" value
 * @method integer               getCertificado()            Returns the current record's "certificado" value
 * @method ClaCicloAcreditacion  getClaCicloAcreditacion()   Returns the current record's "ClaCicloAcreditacion" value
 * @method ClaCicloAcreditacion  getClaCicloAcreditacion2()  Returns the current record's "ClaCicloAcreditacion_2" value
 * @method DatRueUnidadEducativa getDatRueUnidadEducativa()  Returns the current record's "DatRueUnidadEducativa" value
 * @method Doctrine_Collection   getDatSlnEstudios()         Returns the current record's "DatSlnEstudios" collection
 * @method Doctrine_Collection   getDatSlnEstudios2()        Returns the current record's "DatSlnEstudios_2" collection
 * @method DatRueNivel           setCodUeId()                Sets the current record's "cod_ue_id" value
 * @method DatRueNivel           setNivelId()                Sets the current record's "nivel_id" value
 * @method DatRueNivel           setAcreditacionId()         Sets the current record's "acreditacion_id" value
 * @method DatRueNivel           setCertificado()            Sets the current record's "certificado" value
 * @method DatRueNivel           setClaCicloAcreditacion()   Sets the current record's "ClaCicloAcreditacion" value
 * @method DatRueNivel           setClaCicloAcreditacion2()  Sets the current record's "ClaCicloAcreditacion_2" value
 * @method DatRueNivel           setDatRueUnidadEducativa()  Sets the current record's "DatRueUnidadEducativa" value
 * @method DatRueNivel           setDatSlnEstudios()         Sets the current record's "DatSlnEstudios" collection
 * @method DatRueNivel           setDatSlnEstudios2()        Sets the current record's "DatSlnEstudios_2" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatRueNivel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_rue_nivel');
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('nivel_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('acreditacion_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('certificado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaCicloAcreditacion', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasOne('ClaCicloAcreditacion as ClaCicloAcreditacion_2', array(
             'local' => 'acreditacion_id',
             'foreign' => 'id_acreditacion'));

        $this->hasOne('DatRueUnidadEducativa', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue'));

        $this->hasMany('DatSlnEstudios', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue_id'));

        $this->hasMany('DatSlnEstudios as DatSlnEstudios_2', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));
    }
}