<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AuxCurso', 'doctrine');

/**
 * BaseAuxCurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cod_ue_id
 * @property integer $gestion_id
 * @property integer $nivel_id
 * @property integer $ciclo_id
 * @property integer $grado_id
 * @property string $paralelo
 * @property integer $turno_id
 * @property integer $consolidado
 * 
 * @method string   getCodUeId()     Returns the current record's "cod_ue_id" value
 * @method integer  getGestionId()   Returns the current record's "gestion_id" value
 * @method integer  getNivelId()     Returns the current record's "nivel_id" value
 * @method integer  getCicloId()     Returns the current record's "ciclo_id" value
 * @method integer  getGradoId()     Returns the current record's "grado_id" value
 * @method string   getParalelo()    Returns the current record's "paralelo" value
 * @method integer  getTurnoId()     Returns the current record's "turno_id" value
 * @method integer  getConsolidado() Returns the current record's "consolidado" value
 * @method AuxCurso setCodUeId()     Sets the current record's "cod_ue_id" value
 * @method AuxCurso setGestionId()   Sets the current record's "gestion_id" value
 * @method AuxCurso setNivelId()     Sets the current record's "nivel_id" value
 * @method AuxCurso setCicloId()     Sets the current record's "ciclo_id" value
 * @method AuxCurso setGradoId()     Sets the current record's "grado_id" value
 * @method AuxCurso setParalelo()    Sets the current record's "paralelo" value
 * @method AuxCurso setTurnoId()     Sets the current record's "turno_id" value
 * @method AuxCurso setConsolidado() Sets the current record's "consolidado" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAuxCurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aux_curso');
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('nivel_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('ciclo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('grado_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('paralelo', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('turno_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('consolidado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}