<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SeqInscripcionUe', 'doctrine');

/**
 * BaseSeqInscripcionUe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gestion_id
 * @property string $cod_ue_id
 * @property integer $numero_matricula
 * @property ClaGestion $ClaGestion
 * @property DatRueUnidadEducativa $DatRueUnidadEducativa
 * 
 * @method integer               getGestionId()             Returns the current record's "gestion_id" value
 * @method string                getCodUeId()               Returns the current record's "cod_ue_id" value
 * @method integer               getNumeroMatricula()       Returns the current record's "numero_matricula" value
 * @method ClaGestion            getClaGestion()            Returns the current record's "ClaGestion" value
 * @method DatRueUnidadEducativa getDatRueUnidadEducativa() Returns the current record's "DatRueUnidadEducativa" value
 * @method SeqInscripcionUe      setGestionId()             Sets the current record's "gestion_id" value
 * @method SeqInscripcionUe      setCodUeId()               Sets the current record's "cod_ue_id" value
 * @method SeqInscripcionUe      setNumeroMatricula()       Sets the current record's "numero_matricula" value
 * @method SeqInscripcionUe      setClaGestion()            Sets the current record's "ClaGestion" value
 * @method SeqInscripcionUe      setDatRueUnidadEducativa() Sets the current record's "DatRueUnidadEducativa" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSeqInscripcionUe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seq_inscripcion_ue');
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('numero_matricula', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaGestion', array(
             'local' => 'gestion_id',
             'foreign' => 'id_gestion'));

        $this->hasOne('DatRueUnidadEducativa', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue'));
    }
}