<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaCerrada', 'doctrine');

/**
 * BaseClaCerrada
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_cerrada
 * @property string $desc_cerrada
 * @property string $obs_cerrada
 * @property Doctrine_Collection $CtrSieUnidadEducativa
 * @property Doctrine_Collection $DatIfrJurisdiccionAdministrativa
 * @property Doctrine_Collection $DatRueUnidadEducativa
 * @property Doctrine_Collection $DatSieUnidadEducativa
 * @property Doctrine_Collection $SdatRueUnidadEducativa
 * 
 * @method integer             getCodCerrada()                       Returns the current record's "cod_cerrada" value
 * @method string              getDescCerrada()                      Returns the current record's "desc_cerrada" value
 * @method string              getObsCerrada()                       Returns the current record's "obs_cerrada" value
 * @method Doctrine_Collection getCtrSieUnidadEducativa()            Returns the current record's "CtrSieUnidadEducativa" collection
 * @method Doctrine_Collection getDatIfrJurisdiccionAdministrativa() Returns the current record's "DatIfrJurisdiccionAdministrativa" collection
 * @method Doctrine_Collection getDatRueUnidadEducativa()            Returns the current record's "DatRueUnidadEducativa" collection
 * @method Doctrine_Collection getDatSieUnidadEducativa()            Returns the current record's "DatSieUnidadEducativa" collection
 * @method Doctrine_Collection getSdatRueUnidadEducativa()           Returns the current record's "SdatRueUnidadEducativa" collection
 * @method ClaCerrada          setCodCerrada()                       Sets the current record's "cod_cerrada" value
 * @method ClaCerrada          setDescCerrada()                      Sets the current record's "desc_cerrada" value
 * @method ClaCerrada          setObsCerrada()                       Sets the current record's "obs_cerrada" value
 * @method ClaCerrada          setCtrSieUnidadEducativa()            Sets the current record's "CtrSieUnidadEducativa" collection
 * @method ClaCerrada          setDatIfrJurisdiccionAdministrativa() Sets the current record's "DatIfrJurisdiccionAdministrativa" collection
 * @method ClaCerrada          setDatRueUnidadEducativa()            Sets the current record's "DatRueUnidadEducativa" collection
 * @method ClaCerrada          setDatSieUnidadEducativa()            Sets the current record's "DatSieUnidadEducativa" collection
 * @method ClaCerrada          setSdatRueUnidadEducativa()           Sets the current record's "SdatRueUnidadEducativa" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaCerrada extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_cerrada');
        $this->hasColumn('cod_cerrada', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('desc_cerrada', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('obs_cerrada', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CtrSieUnidadEducativa', array(
             'local' => 'cod_cerrada',
             'foreign' => 'cod_cerrada_id'));

        $this->hasMany('DatIfrJurisdiccionAdministrativa', array(
             'local' => 'cod_cerrada',
             'foreign' => 'cod_cerrada_id'));

        $this->hasMany('DatRueUnidadEducativa', array(
             'local' => 'cod_cerrada',
             'foreign' => 'cod_cerrada_id'));

        $this->hasMany('DatSieUnidadEducativa', array(
             'local' => 'cod_cerrada',
             'foreign' => 'cod_cerrada_id'));

        $this->hasMany('SdatRueUnidadEducativa', array(
             'local' => 'cod_cerrada',
             'foreign' => 'cod_cerrada_id'));
    }
}