<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaTransporte', 'doctrine');

/**
 * BaseClaTransporte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_transporte
 * @property string $desc_transporte
 * @property Doctrine_Collection $DatRdeSocioEconomico
 * @property Doctrine_Collection $SdatRdeSocioEconomico
 * 
 * @method integer             getIdTransporte()          Returns the current record's "id_transporte" value
 * @method string              getDescTransporte()        Returns the current record's "desc_transporte" value
 * @method Doctrine_Collection getDatRdeSocioEconomico()  Returns the current record's "DatRdeSocioEconomico" collection
 * @method Doctrine_Collection getSdatRdeSocioEconomico() Returns the current record's "SdatRdeSocioEconomico" collection
 * @method ClaTransporte       setIdTransporte()          Sets the current record's "id_transporte" value
 * @method ClaTransporte       setDescTransporte()        Sets the current record's "desc_transporte" value
 * @method ClaTransporte       setDatRdeSocioEconomico()  Sets the current record's "DatRdeSocioEconomico" collection
 * @method ClaTransporte       setSdatRdeSocioEconomico() Sets the current record's "SdatRdeSocioEconomico" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaTransporte extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_transporte');
        $this->hasColumn('id_transporte', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('desc_transporte', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DatRdeSocioEconomico', array(
             'local' => 'id_transporte',
             'foreign' => 'transporte_id'));

        $this->hasMany('SdatRdeSocioEconomico', array(
             'local' => 'id_transporte',
             'foreign' => 'transporte_id'));
    }
}