<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaTraProceso', 'doctrine');

/**
 * BaseClaTraProceso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_proceso
 * @property integer $tramite_id
 * @property string $numero_proceso
 * @property string $desc_proceso
 * @property integer $tiempo_proceso
 * @property integer $tipo_proceso_id
 * @property integer $interaccion_sistema
 * @property ClaTipoProceso $ClaTipoProceso
 * @property ClaTraTramite $ClaTraTramite
 * @property Doctrine_Collection $AuxDplLegalizacion
 * @property Doctrine_Collection $ClaAcciones
 * @property Doctrine_Collection $CtrDplTramite
 * @property Doctrine_Collection $DatDplLegalizacion
 * @property Doctrine_Collection $DatTraSeguimiento
 * @property Doctrine_Collection $RelTraProceso
 * @property Doctrine_Collection $RelTraProceso_2
 * @property Doctrine_Collection $RelTraProcesoUsuario
 * @property Doctrine_Collection $RelTraRequisitos
 * @property Doctrine_Collection $RelTraUsuarioProceso
 * 
 * @method integer             getIdProceso()            Returns the current record's "id_proceso" value
 * @method integer             getTramiteId()            Returns the current record's "tramite_id" value
 * @method string              getNumeroProceso()        Returns the current record's "numero_proceso" value
 * @method string              getDescProceso()          Returns the current record's "desc_proceso" value
 * @method integer             getTiempoProceso()        Returns the current record's "tiempo_proceso" value
 * @method integer             getTipoProcesoId()        Returns the current record's "tipo_proceso_id" value
 * @method integer             getInteraccionSistema()   Returns the current record's "interaccion_sistema" value
 * @method ClaTipoProceso      getClaTipoProceso()       Returns the current record's "ClaTipoProceso" value
 * @method ClaTraTramite       getClaTraTramite()        Returns the current record's "ClaTraTramite" value
 * @method Doctrine_Collection getAuxDplLegalizacion()   Returns the current record's "AuxDplLegalizacion" collection
 * @method Doctrine_Collection getClaAcciones()          Returns the current record's "ClaAcciones" collection
 * @method Doctrine_Collection getCtrDplTramite()        Returns the current record's "CtrDplTramite" collection
 * @method Doctrine_Collection getDatDplLegalizacion()   Returns the current record's "DatDplLegalizacion" collection
 * @method Doctrine_Collection getDatTraSeguimiento()    Returns the current record's "DatTraSeguimiento" collection
 * @method Doctrine_Collection getRelTraProceso()        Returns the current record's "RelTraProceso" collection
 * @method Doctrine_Collection getRelTraProceso2()       Returns the current record's "RelTraProceso_2" collection
 * @method Doctrine_Collection getRelTraProcesoUsuario() Returns the current record's "RelTraProcesoUsuario" collection
 * @method Doctrine_Collection getRelTraRequisitos()     Returns the current record's "RelTraRequisitos" collection
 * @method Doctrine_Collection getRelTraUsuarioProceso() Returns the current record's "RelTraUsuarioProceso" collection
 * @method ClaTraProceso       setIdProceso()            Sets the current record's "id_proceso" value
 * @method ClaTraProceso       setTramiteId()            Sets the current record's "tramite_id" value
 * @method ClaTraProceso       setNumeroProceso()        Sets the current record's "numero_proceso" value
 * @method ClaTraProceso       setDescProceso()          Sets the current record's "desc_proceso" value
 * @method ClaTraProceso       setTiempoProceso()        Sets the current record's "tiempo_proceso" value
 * @method ClaTraProceso       setTipoProcesoId()        Sets the current record's "tipo_proceso_id" value
 * @method ClaTraProceso       setInteraccionSistema()   Sets the current record's "interaccion_sistema" value
 * @method ClaTraProceso       setClaTipoProceso()       Sets the current record's "ClaTipoProceso" value
 * @method ClaTraProceso       setClaTraTramite()        Sets the current record's "ClaTraTramite" value
 * @method ClaTraProceso       setAuxDplLegalizacion()   Sets the current record's "AuxDplLegalizacion" collection
 * @method ClaTraProceso       setClaAcciones()          Sets the current record's "ClaAcciones" collection
 * @method ClaTraProceso       setCtrDplTramite()        Sets the current record's "CtrDplTramite" collection
 * @method ClaTraProceso       setDatDplLegalizacion()   Sets the current record's "DatDplLegalizacion" collection
 * @method ClaTraProceso       setDatTraSeguimiento()    Sets the current record's "DatTraSeguimiento" collection
 * @method ClaTraProceso       setRelTraProceso()        Sets the current record's "RelTraProceso" collection
 * @method ClaTraProceso       setRelTraProceso2()       Sets the current record's "RelTraProceso_2" collection
 * @method ClaTraProceso       setRelTraProcesoUsuario() Sets the current record's "RelTraProcesoUsuario" collection
 * @method ClaTraProceso       setRelTraRequisitos()     Sets the current record's "RelTraRequisitos" collection
 * @method ClaTraProceso       setRelTraUsuarioProceso() Sets the current record's "RelTraUsuarioProceso" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaTraProceso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_tra_proceso');
        $this->hasColumn('id_proceso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('tramite_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('numero_proceso', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('desc_proceso', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('tiempo_proceso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('tipo_proceso_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('interaccion_sistema', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaTipoProceso', array(
             'local' => 'tipo_proceso_id',
             'foreign' => 'id_tipo_proceso'));

        $this->hasOne('ClaTraTramite', array(
             'local' => 'tramite_id',
             'foreign' => 'id_tramite'));

        $this->hasMany('AuxDplLegalizacion', array(
             'local' => 'id_proceso',
             'foreign' => 'proceso_id'));

        $this->hasMany('ClaAcciones', array(
             'local' => 'id_proceso',
             'foreign' => 'proceso_id'));

        $this->hasMany('CtrDplTramite', array(
             'local' => 'id_proceso',
             'foreign' => 'proceso_id'));

        $this->hasMany('DatDplLegalizacion', array(
             'local' => 'id_proceso',
             'foreign' => 'proceso_id'));

        $this->hasMany('DatTraSeguimiento', array(
             'local' => 'id_proceso',
             'foreign' => 'proceso_id'));

        $this->hasMany('RelTraProceso', array(
             'local' => 'id_proceso',
             'foreign' => 'proceso_id'));

        $this->hasMany('RelTraProceso as RelTraProceso_2', array(
             'local' => 'id_proceso',
             'foreign' => 'proceso_antecesor_id'));

        $this->hasMany('RelTraProcesoUsuario', array(
             'local' => 'id_proceso',
             'foreign' => 'proceso_id'));

        $this->hasMany('RelTraRequisitos', array(
             'local' => 'id_proceso',
             'foreign' => 'proceso_id'));

        $this->hasMany('RelTraUsuarioProceso', array(
             'local' => 'id_proceso',
             'foreign' => 'proceso_id'));
    }
}