<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaTurno', 'doctrine');

/**
 * BaseClaTurno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_turno
 * @property string $desc_turno
 * @property string $desc_abrv
 * @property Doctrine_Collection $CtrSieCurso
 * @property Doctrine_Collection $CtrSieUnidadEducativa
 * @property Doctrine_Collection $DatAltCursoTecnica
 * @property Doctrine_Collection $DatEspCurso
 * @property Doctrine_Collection $DatRueCursoTramite
 * @property Doctrine_Collection $DatRueUnidadEducativaTramite
 * @property Doctrine_Collection $DatSieCurso
 * @property Doctrine_Collection $DatSieUnidadEducativa
 * @property Doctrine_Collection $SdatRueUnidadEducativa
 * @property Doctrine_Collection $SdatSieCurso
 * @property Doctrine_Collection $SdatSieCursotecnica
 * 
 * @method integer             getIdTurno()                      Returns the current record's "id_turno" value
 * @method string              getDescTurno()                    Returns the current record's "desc_turno" value
 * @method string              getDescAbrv()                     Returns the current record's "desc_abrv" value
 * @method Doctrine_Collection getCtrSieCurso()                  Returns the current record's "CtrSieCurso" collection
 * @method Doctrine_Collection getCtrSieUnidadEducativa()        Returns the current record's "CtrSieUnidadEducativa" collection
 * @method Doctrine_Collection getDatAltCursoTecnica()           Returns the current record's "DatAltCursoTecnica" collection
 * @method Doctrine_Collection getDatEspCurso()                  Returns the current record's "DatEspCurso" collection
 * @method Doctrine_Collection getDatRueCursoTramite()           Returns the current record's "DatRueCursoTramite" collection
 * @method Doctrine_Collection getDatRueUnidadEducativaTramite() Returns the current record's "DatRueUnidadEducativaTramite" collection
 * @method Doctrine_Collection getDatSieCurso()                  Returns the current record's "DatSieCurso" collection
 * @method Doctrine_Collection getDatSieUnidadEducativa()        Returns the current record's "DatSieUnidadEducativa" collection
 * @method Doctrine_Collection getSdatRueUnidadEducativa()       Returns the current record's "SdatRueUnidadEducativa" collection
 * @method Doctrine_Collection getSdatSieCurso()                 Returns the current record's "SdatSieCurso" collection
 * @method Doctrine_Collection getSdatSieCursotecnica()          Returns the current record's "SdatSieCursotecnica" collection
 * @method ClaTurno            setIdTurno()                      Sets the current record's "id_turno" value
 * @method ClaTurno            setDescTurno()                    Sets the current record's "desc_turno" value
 * @method ClaTurno            setDescAbrv()                     Sets the current record's "desc_abrv" value
 * @method ClaTurno            setCtrSieCurso()                  Sets the current record's "CtrSieCurso" collection
 * @method ClaTurno            setCtrSieUnidadEducativa()        Sets the current record's "CtrSieUnidadEducativa" collection
 * @method ClaTurno            setDatAltCursoTecnica()           Sets the current record's "DatAltCursoTecnica" collection
 * @method ClaTurno            setDatEspCurso()                  Sets the current record's "DatEspCurso" collection
 * @method ClaTurno            setDatRueCursoTramite()           Sets the current record's "DatRueCursoTramite" collection
 * @method ClaTurno            setDatRueUnidadEducativaTramite() Sets the current record's "DatRueUnidadEducativaTramite" collection
 * @method ClaTurno            setDatSieCurso()                  Sets the current record's "DatSieCurso" collection
 * @method ClaTurno            setDatSieUnidadEducativa()        Sets the current record's "DatSieUnidadEducativa" collection
 * @method ClaTurno            setSdatRueUnidadEducativa()       Sets the current record's "SdatRueUnidadEducativa" collection
 * @method ClaTurno            setSdatSieCurso()                 Sets the current record's "SdatSieCurso" collection
 * @method ClaTurno            setSdatSieCursotecnica()          Sets the current record's "SdatSieCursotecnica" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaTurno extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_turno');
        $this->hasColumn('id_turno', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('desc_turno', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('desc_abrv', 'string', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CtrSieCurso', array(
             'local' => 'id_turno',
             'foreign' => 'turno_id'));

        $this->hasMany('CtrSieUnidadEducativa', array(
             'local' => 'id_turno',
             'foreign' => 'turno_id'));

        $this->hasMany('DatAltCursoTecnica', array(
             'local' => 'id_turno',
             'foreign' => 'turno_id'));

        $this->hasMany('DatEspCurso', array(
             'local' => 'id_turno',
             'foreign' => 'turno_id'));

        $this->hasMany('DatRueCursoTramite', array(
             'local' => 'id_turno',
             'foreign' => 'turno_id'));

        $this->hasMany('DatRueUnidadEducativaTramite', array(
             'local' => 'id_turno',
             'foreign' => 'turno_id'));

        $this->hasMany('DatSieCurso', array(
             'local' => 'id_turno',
             'foreign' => 'turno_id'));

        $this->hasMany('DatSieUnidadEducativa', array(
             'local' => 'id_turno',
             'foreign' => 'turno_id'));

        $this->hasMany('SdatRueUnidadEducativa', array(
             'local' => 'id_turno',
             'foreign' => 'turno_id'));

        $this->hasMany('SdatSieCurso', array(
             'local' => 'id_turno',
             'foreign' => 'turno_id'));

        $this->hasMany('SdatSieCursotecnica', array(
             'local' => 'id_turno',
             'foreign' => 'turno_id'));
    }
}