<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatAltCursoTecnica', 'doctrine');

/**
 * BaseDatAltCursoTecnica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cod_ue_id
 * @property integer $sub_cea_id
 * @property integer $gestion_id
 * @property integer $operativo_id
 * @property integer $periodo_id
 * @property integer $nivel_id
 * @property integer $ciclo_id
 * @property integer $grado_id
 * @property string $paralelo
 * @property integer $turno_id
 * @property integer $modalidad_ensenanza_id
 * @property integer $nro_materias
 * @property integer $consolidado
 * @property integer $curso_oferta_id
 * @property ClaGrado $ClaGrado
 * @property ClaGrado $ClaGrado_2
 * @property ClaGrado $ClaGrado_3
 * @property ClaModalidadEnsenanza $ClaModalidadEnsenanza
 * @property ClaTurno $ClaTurno
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa_7
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa_8
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa_9
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa_10
 * @property DatAltCursooferta $DatAltCursooferta
 * @property DatAltCursooferta $DatAltCursooferta_12
 * @property Doctrine_Collection $DatRdeInscripcionTecnica
 * @property Doctrine_Collection $DatRdeInscripcionTecnica_5
 * @property Doctrine_Collection $DatRdeInscripcionTecnica_6
 * @property Doctrine_Collection $DatRdeInscripcionTecnica_7
 * @property Doctrine_Collection $DatRdeInscripcionTecnica_8
 * @property Doctrine_Collection $DatRdeInscripcionTecnica_9
 * @property Doctrine_Collection $DatRdeInscripcionTecnica_10
 * @property Doctrine_Collection $DatRdeInscripcionTecnica_11
 * @property Doctrine_Collection $DatRdeInscripcionTecnica_12
 * @property Doctrine_Collection $DatRdeInscripcionTecnica_13
 * @property Doctrine_Collection $DatRdeInscripcionTecnica_14
 * 
 * @method string                getCodUeId()                     Returns the current record's "cod_ue_id" value
 * @method integer               getSubCeaId()                    Returns the current record's "sub_cea_id" value
 * @method integer               getGestionId()                   Returns the current record's "gestion_id" value
 * @method integer               getOperativoId()                 Returns the current record's "operativo_id" value
 * @method integer               getPeriodoId()                   Returns the current record's "periodo_id" value
 * @method integer               getNivelId()                     Returns the current record's "nivel_id" value
 * @method integer               getCicloId()                     Returns the current record's "ciclo_id" value
 * @method integer               getGradoId()                     Returns the current record's "grado_id" value
 * @method string                getParalelo()                    Returns the current record's "paralelo" value
 * @method integer               getTurnoId()                     Returns the current record's "turno_id" value
 * @method integer               getModalidadEnsenanzaId()        Returns the current record's "modalidad_ensenanza_id" value
 * @method integer               getNroMaterias()                 Returns the current record's "nro_materias" value
 * @method integer               getConsolidado()                 Returns the current record's "consolidado" value
 * @method integer               getCursoOfertaId()               Returns the current record's "curso_oferta_id" value
 * @method ClaGrado              getClaGrado()                    Returns the current record's "ClaGrado" value
 * @method ClaGrado              getClaGrado2()                   Returns the current record's "ClaGrado_2" value
 * @method ClaGrado              getClaGrado3()                   Returns the current record's "ClaGrado_3" value
 * @method ClaModalidadEnsenanza getClaModalidadEnsenanza()       Returns the current record's "ClaModalidadEnsenanza" value
 * @method ClaTurno              getClaTurno()                    Returns the current record's "ClaTurno" value
 * @method DatSieUnidadEducativa getDatSieUnidadEducativa()       Returns the current record's "DatSieUnidadEducativa" value
 * @method DatSieUnidadEducativa getDatSieUnidadEducativa7()      Returns the current record's "DatSieUnidadEducativa_7" value
 * @method DatSieUnidadEducativa getDatSieUnidadEducativa8()      Returns the current record's "DatSieUnidadEducativa_8" value
 * @method DatSieUnidadEducativa getDatSieUnidadEducativa9()      Returns the current record's "DatSieUnidadEducativa_9" value
 * @method DatSieUnidadEducativa getDatSieUnidadEducativa10()     Returns the current record's "DatSieUnidadEducativa_10" value
 * @method DatAltCursooferta     getDatAltCursooferta()           Returns the current record's "DatAltCursooferta" value
 * @method DatAltCursooferta     getDatAltCursooferta12()         Returns the current record's "DatAltCursooferta_12" value
 * @method Doctrine_Collection   getDatRdeInscripcionTecnica()    Returns the current record's "DatRdeInscripcionTecnica" collection
 * @method Doctrine_Collection   getDatRdeInscripcionTecnica5()   Returns the current record's "DatRdeInscripcionTecnica_5" collection
 * @method Doctrine_Collection   getDatRdeInscripcionTecnica6()   Returns the current record's "DatRdeInscripcionTecnica_6" collection
 * @method Doctrine_Collection   getDatRdeInscripcionTecnica7()   Returns the current record's "DatRdeInscripcionTecnica_7" collection
 * @method Doctrine_Collection   getDatRdeInscripcionTecnica8()   Returns the current record's "DatRdeInscripcionTecnica_8" collection
 * @method Doctrine_Collection   getDatRdeInscripcionTecnica9()   Returns the current record's "DatRdeInscripcionTecnica_9" collection
 * @method Doctrine_Collection   getDatRdeInscripcionTecnica10()  Returns the current record's "DatRdeInscripcionTecnica_10" collection
 * @method Doctrine_Collection   getDatRdeInscripcionTecnica11()  Returns the current record's "DatRdeInscripcionTecnica_11" collection
 * @method Doctrine_Collection   getDatRdeInscripcionTecnica12()  Returns the current record's "DatRdeInscripcionTecnica_12" collection
 * @method Doctrine_Collection   getDatRdeInscripcionTecnica13()  Returns the current record's "DatRdeInscripcionTecnica_13" collection
 * @method Doctrine_Collection   getDatRdeInscripcionTecnica14()  Returns the current record's "DatRdeInscripcionTecnica_14" collection
 * @method DatAltCursoTecnica    setCodUeId()                     Sets the current record's "cod_ue_id" value
 * @method DatAltCursoTecnica    setSubCeaId()                    Sets the current record's "sub_cea_id" value
 * @method DatAltCursoTecnica    setGestionId()                   Sets the current record's "gestion_id" value
 * @method DatAltCursoTecnica    setOperativoId()                 Sets the current record's "operativo_id" value
 * @method DatAltCursoTecnica    setPeriodoId()                   Sets the current record's "periodo_id" value
 * @method DatAltCursoTecnica    setNivelId()                     Sets the current record's "nivel_id" value
 * @method DatAltCursoTecnica    setCicloId()                     Sets the current record's "ciclo_id" value
 * @method DatAltCursoTecnica    setGradoId()                     Sets the current record's "grado_id" value
 * @method DatAltCursoTecnica    setParalelo()                    Sets the current record's "paralelo" value
 * @method DatAltCursoTecnica    setTurnoId()                     Sets the current record's "turno_id" value
 * @method DatAltCursoTecnica    setModalidadEnsenanzaId()        Sets the current record's "modalidad_ensenanza_id" value
 * @method DatAltCursoTecnica    setNroMaterias()                 Sets the current record's "nro_materias" value
 * @method DatAltCursoTecnica    setConsolidado()                 Sets the current record's "consolidado" value
 * @method DatAltCursoTecnica    setCursoOfertaId()               Sets the current record's "curso_oferta_id" value
 * @method DatAltCursoTecnica    setClaGrado()                    Sets the current record's "ClaGrado" value
 * @method DatAltCursoTecnica    setClaGrado2()                   Sets the current record's "ClaGrado_2" value
 * @method DatAltCursoTecnica    setClaGrado3()                   Sets the current record's "ClaGrado_3" value
 * @method DatAltCursoTecnica    setClaModalidadEnsenanza()       Sets the current record's "ClaModalidadEnsenanza" value
 * @method DatAltCursoTecnica    setClaTurno()                    Sets the current record's "ClaTurno" value
 * @method DatAltCursoTecnica    setDatSieUnidadEducativa()       Sets the current record's "DatSieUnidadEducativa" value
 * @method DatAltCursoTecnica    setDatSieUnidadEducativa7()      Sets the current record's "DatSieUnidadEducativa_7" value
 * @method DatAltCursoTecnica    setDatSieUnidadEducativa8()      Sets the current record's "DatSieUnidadEducativa_8" value
 * @method DatAltCursoTecnica    setDatSieUnidadEducativa9()      Sets the current record's "DatSieUnidadEducativa_9" value
 * @method DatAltCursoTecnica    setDatSieUnidadEducativa10()     Sets the current record's "DatSieUnidadEducativa_10" value
 * @method DatAltCursoTecnica    setDatAltCursooferta()           Sets the current record's "DatAltCursooferta" value
 * @method DatAltCursoTecnica    setDatAltCursooferta12()         Sets the current record's "DatAltCursooferta_12" value
 * @method DatAltCursoTecnica    setDatRdeInscripcionTecnica()    Sets the current record's "DatRdeInscripcionTecnica" collection
 * @method DatAltCursoTecnica    setDatRdeInscripcionTecnica5()   Sets the current record's "DatRdeInscripcionTecnica_5" collection
 * @method DatAltCursoTecnica    setDatRdeInscripcionTecnica6()   Sets the current record's "DatRdeInscripcionTecnica_6" collection
 * @method DatAltCursoTecnica    setDatRdeInscripcionTecnica7()   Sets the current record's "DatRdeInscripcionTecnica_7" collection
 * @method DatAltCursoTecnica    setDatRdeInscripcionTecnica8()   Sets the current record's "DatRdeInscripcionTecnica_8" collection
 * @method DatAltCursoTecnica    setDatRdeInscripcionTecnica9()   Sets the current record's "DatRdeInscripcionTecnica_9" collection
 * @method DatAltCursoTecnica    setDatRdeInscripcionTecnica10()  Sets the current record's "DatRdeInscripcionTecnica_10" collection
 * @method DatAltCursoTecnica    setDatRdeInscripcionTecnica11()  Sets the current record's "DatRdeInscripcionTecnica_11" collection
 * @method DatAltCursoTecnica    setDatRdeInscripcionTecnica12()  Sets the current record's "DatRdeInscripcionTecnica_12" collection
 * @method DatAltCursoTecnica    setDatRdeInscripcionTecnica13()  Sets the current record's "DatRdeInscripcionTecnica_13" collection
 * @method DatAltCursoTecnica    setDatRdeInscripcionTecnica14()  Sets the current record's "DatRdeInscripcionTecnica_14" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatAltCursoTecnica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_alt_curso_tecnica');
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('sub_cea_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('operativo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('periodo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('nivel_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('ciclo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('grado_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('paralelo', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('turno_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('modalidad_ensenanza_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('nro_materias', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('consolidado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('curso_oferta_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaGrado', array(
             'local' => 'grado_id',
             'foreign' => 'id_grado'));

        $this->hasOne('ClaGrado as ClaGrado_2', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasOne('ClaGrado as ClaGrado_3', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasOne('ClaModalidadEnsenanza', array(
             'local' => 'modalidad_ensenanza_id',
             'foreign' => 'id_modalidad_ensenanza'));

        $this->hasOne('ClaTurno', array(
             'local' => 'turno_id',
             'foreign' => 'id_turno'));

        $this->hasOne('DatSieUnidadEducativa', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue_id'));

        $this->hasOne('DatSieUnidadEducativa as DatSieUnidadEducativa_7', array(
             'local' => 'periodo_id',
             'foreign' => 'periodo_id'));

        $this->hasOne('DatSieUnidadEducativa as DatSieUnidadEducativa_8', array(
             'local' => 'operativo_id',
             'foreign' => 'operativo_id'));

        $this->hasOne('DatSieUnidadEducativa as DatSieUnidadEducativa_9', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasOne('DatSieUnidadEducativa as DatSieUnidadEducativa_10', array(
             'local' => 'sub_cea_id',
             'foreign' => 'sub_cea'));

        $this->hasOne('DatAltCursooferta', array(
             'local' => 'curso_oferta_id',
             'foreign' => 'curso_oferta_id'));

        $this->hasOne('DatAltCursooferta as DatAltCursooferta_12', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue_id'));

        $this->hasMany('DatRdeInscripcionTecnica', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue_id'));

        $this->hasMany('DatRdeInscripcionTecnica as DatRdeInscripcionTecnica_5', array(
             'local' => 'periodo_id',
             'foreign' => 'periodo_id'));

        $this->hasMany('DatRdeInscripcionTecnica as DatRdeInscripcionTecnica_6', array(
             'local' => 'operativo_id',
             'foreign' => 'operativo_id'));

        $this->hasMany('DatRdeInscripcionTecnica as DatRdeInscripcionTecnica_7', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasMany('DatRdeInscripcionTecnica as DatRdeInscripcionTecnica_8', array(
             'local' => 'sub_cea_id',
             'foreign' => 'sub_cea_id'));

        $this->hasMany('DatRdeInscripcionTecnica as DatRdeInscripcionTecnica_9', array(
             'local' => 'grado_id',
             'foreign' => 'grado_id'));

        $this->hasMany('DatRdeInscripcionTecnica as DatRdeInscripcionTecnica_10', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasMany('DatRdeInscripcionTecnica as DatRdeInscripcionTecnica_11', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasMany('DatRdeInscripcionTecnica as DatRdeInscripcionTecnica_12', array(
             'local' => 'paralelo',
             'foreign' => 'paralelo'));

        $this->hasMany('DatRdeInscripcionTecnica as DatRdeInscripcionTecnica_13', array(
             'local' => 'turno_id',
             'foreign' => 'turno_id'));

        $this->hasMany('DatRdeInscripcionTecnica as DatRdeInscripcionTecnica_14', array(
             'local' => 'curso_oferta_id',
             'foreign' => 'curso_oferta_id'));
    }
}