<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VisPorcentajeConsolidadoDistrito', 'doctrine');

/**
 * BaseVisPorcentajeConsolidadoDistrito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $departamento_id
 * @property integer $cod_distrito
 * @property string $distrito
 * @property integer $consolidado
 * 
 * @method integer                          getId()              Returns the current record's "id" value
 * @method integer                          getDepartamentoId()  Returns the current record's "departamento_id" value
 * @method integer                          getCodDistrito()     Returns the current record's "cod_distrito" value
 * @method string                           getDistrito()        Returns the current record's "distrito" value
 * @method integer                          getConsolidado()     Returns the current record's "consolidado" value
 * @method VisPorcentajeConsolidadoDistrito setId()              Sets the current record's "id" value
 * @method VisPorcentajeConsolidadoDistrito setDepartamentoId()  Sets the current record's "departamento_id" value
 * @method VisPorcentajeConsolidadoDistrito setCodDistrito()     Sets the current record's "cod_distrito" value
 * @method VisPorcentajeConsolidadoDistrito setDistrito()        Sets the current record's "distrito" value
 * @method VisPorcentajeConsolidadoDistrito setConsolidado()     Sets the current record's "consolidado" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVisPorcentajeConsolidadoDistrito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vis_porcentaje_consolidado_distrito');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('departamento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('cod_distrito', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('distrito', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('consolidado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}