<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaObservacionInscripcion', 'doctrine');

/**
 * BaseClaObservacionInscripcion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_observacion
 * @property string $desc_observacion
 * @property Doctrine_Collection $CtrRdeInscripcion
 * @property Doctrine_Collection $DatRdeInscripcion
 * @property Doctrine_Collection $DatRueInscripcionTramite
 * @property Doctrine_Collection $HisRdeInscripcion
 * 
 * @method integer                   getIdObservacion()            Returns the current record's "id_observacion" value
 * @method string                    getDescObservacion()          Returns the current record's "desc_observacion" value
 * @method Doctrine_Collection       getCtrRdeInscripcion()        Returns the current record's "CtrRdeInscripcion" collection
 * @method Doctrine_Collection       getDatRdeInscripcion()        Returns the current record's "DatRdeInscripcion" collection
 * @method Doctrine_Collection       getDatRueInscripcionTramite() Returns the current record's "DatRueInscripcionTramite" collection
 * @method Doctrine_Collection       getHisRdeInscripcion()        Returns the current record's "HisRdeInscripcion" collection
 * @method ClaObservacionInscripcion setIdObservacion()            Sets the current record's "id_observacion" value
 * @method ClaObservacionInscripcion setDescObservacion()          Sets the current record's "desc_observacion" value
 * @method ClaObservacionInscripcion setCtrRdeInscripcion()        Sets the current record's "CtrRdeInscripcion" collection
 * @method ClaObservacionInscripcion setDatRdeInscripcion()        Sets the current record's "DatRdeInscripcion" collection
 * @method ClaObservacionInscripcion setDatRueInscripcionTramite() Sets the current record's "DatRueInscripcionTramite" collection
 * @method ClaObservacionInscripcion setHisRdeInscripcion()        Sets the current record's "HisRdeInscripcion" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaObservacionInscripcion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_observacion_inscripcion');
        $this->hasColumn('id_observacion', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('desc_observacion', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CtrRdeInscripcion', array(
             'local' => 'id_observacion',
             'foreign' => 'observacion_id'));

        $this->hasMany('DatRdeInscripcion', array(
             'local' => 'id_observacion',
             'foreign' => 'observacion_id'));

        $this->hasMany('DatRueInscripcionTramite', array(
             'local' => 'id_observacion',
             'foreign' => 'observacion_id'));

        $this->hasMany('HisRdeInscripcion', array(
             'local' => 'id_observacion',
             'foreign' => 'observacion_id'));
    }
}