<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaCargo', 'doctrine');

/**
 * BaseClaCargo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_cargo
 * @property string $desc_cargo
 * @property integer $tipo_cargo_id
 * @property integer $id_sie_cliente
 * @property ClaTipoCargo $ClaTipoCargo
 * @property Doctrine_Collection $CtrPlaItems
 * @property Doctrine_Collection $DatEdaEvento
 * @property Doctrine_Collection $DatPlaItems
 * @property Doctrine_Collection $DatSieAdministrativo
 * @property Doctrine_Collection $DatSieDocente
 * @property Doctrine_Collection $DatUsuUsuario
 * @property Doctrine_Collection $SdatSieAdministrativo
 * @property Doctrine_Collection $SdatSieDocente
 * 
 * @method integer             getIdCargo()               Returns the current record's "id_cargo" value
 * @method string              getDescCargo()             Returns the current record's "desc_cargo" value
 * @method integer             getTipoCargoId()           Returns the current record's "tipo_cargo_id" value
 * @method integer             getIdSieCliente()          Returns the current record's "id_sie_cliente" value
 * @method ClaTipoCargo        getClaTipoCargo()          Returns the current record's "ClaTipoCargo" value
 * @method Doctrine_Collection getCtrPlaItems()           Returns the current record's "CtrPlaItems" collection
 * @method Doctrine_Collection getDatEdaEvento()          Returns the current record's "DatEdaEvento" collection
 * @method Doctrine_Collection getDatPlaItems()           Returns the current record's "DatPlaItems" collection
 * @method Doctrine_Collection getDatSieAdministrativo()  Returns the current record's "DatSieAdministrativo" collection
 * @method Doctrine_Collection getDatSieDocente()         Returns the current record's "DatSieDocente" collection
 * @method Doctrine_Collection getDatUsuUsuario()         Returns the current record's "DatUsuUsuario" collection
 * @method Doctrine_Collection getSdatSieAdministrativo() Returns the current record's "SdatSieAdministrativo" collection
 * @method Doctrine_Collection getSdatSieDocente()        Returns the current record's "SdatSieDocente" collection
 * @method ClaCargo            setIdCargo()               Sets the current record's "id_cargo" value
 * @method ClaCargo            setDescCargo()             Sets the current record's "desc_cargo" value
 * @method ClaCargo            setTipoCargoId()           Sets the current record's "tipo_cargo_id" value
 * @method ClaCargo            setIdSieCliente()          Sets the current record's "id_sie_cliente" value
 * @method ClaCargo            setClaTipoCargo()          Sets the current record's "ClaTipoCargo" value
 * @method ClaCargo            setCtrPlaItems()           Sets the current record's "CtrPlaItems" collection
 * @method ClaCargo            setDatEdaEvento()          Sets the current record's "DatEdaEvento" collection
 * @method ClaCargo            setDatPlaItems()           Sets the current record's "DatPlaItems" collection
 * @method ClaCargo            setDatSieAdministrativo()  Sets the current record's "DatSieAdministrativo" collection
 * @method ClaCargo            setDatSieDocente()         Sets the current record's "DatSieDocente" collection
 * @method ClaCargo            setDatUsuUsuario()         Sets the current record's "DatUsuUsuario" collection
 * @method ClaCargo            setSdatSieAdministrativo() Sets the current record's "SdatSieAdministrativo" collection
 * @method ClaCargo            setSdatSieDocente()        Sets the current record's "SdatSieDocente" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaCargo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_cargo');
        $this->hasColumn('id_cargo', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('desc_cargo', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '150',
             ));
        $this->hasColumn('tipo_cargo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('id_sie_cliente', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaTipoCargo', array(
             'local' => 'tipo_cargo_id',
             'foreign' => 'id_tipo_cargo'));

        $this->hasMany('CtrPlaItems', array(
             'local' => 'id_cargo',
             'foreign' => 'cargo_id'));

        $this->hasMany('DatEdaEvento', array(
             'local' => 'id_cargo',
             'foreign' => 'cargo_id'));

        $this->hasMany('DatPlaItems', array(
             'local' => 'id_cargo',
             'foreign' => 'cargo_id'));

        $this->hasMany('DatSieAdministrativo', array(
             'local' => 'id_cargo',
             'foreign' => 'cargo_id'));

        $this->hasMany('DatSieDocente', array(
             'local' => 'id_cargo',
             'foreign' => 'cargo_id'));

        $this->hasMany('DatUsuUsuario', array(
             'local' => 'id_cargo',
             'foreign' => 'cargo_id'));

        $this->hasMany('SdatSieAdministrativo', array(
             'local' => 'id_cargo',
             'foreign' => 'cargo_id'));

        $this->hasMany('SdatSieDocente', array(
             'local' => 'id_cargo',
             'foreign' => 'cargo_id'));
    }
}