<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RelTraSeguimientoRequisito', 'doctrine');

/**
 * BaseRelTraSeguimientoRequisito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $seguimiento_id
 * @property integer $gestion_id
 * @property integer $requisito_id
 * @property string $valor
 * @property ClaRequisitos $ClaRequisitos
 * @property DatTraSeguimiento $DatTraSeguimiento
 * @property DatTraSeguimiento $DatTraSeguimiento_3
 * 
 * @method integer                    getSeguimientoId()       Returns the current record's "seguimiento_id" value
 * @method integer                    getGestionId()           Returns the current record's "gestion_id" value
 * @method integer                    getRequisitoId()         Returns the current record's "requisito_id" value
 * @method string                     getValor()               Returns the current record's "valor" value
 * @method ClaRequisitos              getClaRequisitos()       Returns the current record's "ClaRequisitos" value
 * @method DatTraSeguimiento          getDatTraSeguimiento()   Returns the current record's "DatTraSeguimiento" value
 * @method DatTraSeguimiento          getDatTraSeguimiento3()  Returns the current record's "DatTraSeguimiento_3" value
 * @method RelTraSeguimientoRequisito setSeguimientoId()       Sets the current record's "seguimiento_id" value
 * @method RelTraSeguimientoRequisito setGestionId()           Sets the current record's "gestion_id" value
 * @method RelTraSeguimientoRequisito setRequisitoId()         Sets the current record's "requisito_id" value
 * @method RelTraSeguimientoRequisito setValor()               Sets the current record's "valor" value
 * @method RelTraSeguimientoRequisito setClaRequisitos()       Sets the current record's "ClaRequisitos" value
 * @method RelTraSeguimientoRequisito setDatTraSeguimiento()   Sets the current record's "DatTraSeguimiento" value
 * @method RelTraSeguimientoRequisito setDatTraSeguimiento3()  Sets the current record's "DatTraSeguimiento_3" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRelTraSeguimientoRequisito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rel_tra_seguimiento_requisito');
        $this->hasColumn('seguimiento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('requisito_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('valor', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaRequisitos', array(
             'local' => 'requisito_id',
             'foreign' => 'id_requisito'));

        $this->hasOne('DatTraSeguimiento', array(
             'local' => 'seguimiento_id',
             'foreign' => 'id_seguimiento'));

        $this->hasOne('DatTraSeguimiento as DatTraSeguimiento_3', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));
    }
}