<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatSieDocente', 'doctrine');

/**
 * BaseDatSieDocente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ci_docente_id
 * @property integer $gestion_id
 * @property string $cod_ue_id
 * @property integer $periodo_id
 * @property integer $operativo_id
 * @property integer $sub_cea_id
 * @property integer $cargo_id
 * @property integer $mes
 * @property integer $financiamiento_id
 * @property ClaCargo $ClaCargo
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa_3
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa_4
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa_5
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa_6
 * @property ClaFinanciamiento $ClaFinanciamiento
 * @property DatSieDocenteadministrativo $DatSieDocenteadministrativo
 * @property Doctrine_Collection $DatSlnCursoOferta
 * @property Doctrine_Collection $DatSlnCursoOferta_16
 * @property Doctrine_Collection $DatSlnCursoOferta_17
 * @property Doctrine_Collection $DatSlnCursoOferta_18
 * @property Doctrine_Collection $DatSlnCursoOferta_19
 * @property Doctrine_Collection $DatSlnCursoOferta_20
 * @property Doctrine_Collection $RelDocenteItems
 * @property Doctrine_Collection $RelDocenteItems_5
 * @property Doctrine_Collection $RelDocenteItems_6
 * @property Doctrine_Collection $RelDocenteItems_7
 * @property Doctrine_Collection $RelDocenteItems_8
 * @property Doctrine_Collection $RelDocenteItems_9
 * 
 * @method integer                     getCiDocenteId()                 Returns the current record's "ci_docente_id" value
 * @method integer                     getGestionId()                   Returns the current record's "gestion_id" value
 * @method string                      getCodUeId()                     Returns the current record's "cod_ue_id" value
 * @method integer                     getPeriodoId()                   Returns the current record's "periodo_id" value
 * @method integer                     getOperativoId()                 Returns the current record's "operativo_id" value
 * @method integer                     getSubCeaId()                    Returns the current record's "sub_cea_id" value
 * @method integer                     getCargoId()                     Returns the current record's "cargo_id" value
 * @method integer                     getMes()                         Returns the current record's "mes" value
 * @method integer                     getFinanciamientoId()            Returns the current record's "financiamiento_id" value
 * @method ClaCargo                    getClaCargo()                    Returns the current record's "ClaCargo" value
 * @method DatSieUnidadEducativa       getDatSieUnidadEducativa()       Returns the current record's "DatSieUnidadEducativa" value
 * @method DatSieUnidadEducativa       getDatSieUnidadEducativa3()      Returns the current record's "DatSieUnidadEducativa_3" value
 * @method DatSieUnidadEducativa       getDatSieUnidadEducativa4()      Returns the current record's "DatSieUnidadEducativa_4" value
 * @method DatSieUnidadEducativa       getDatSieUnidadEducativa5()      Returns the current record's "DatSieUnidadEducativa_5" value
 * @method DatSieUnidadEducativa       getDatSieUnidadEducativa6()      Returns the current record's "DatSieUnidadEducativa_6" value
 * @method ClaFinanciamiento           getClaFinanciamiento()           Returns the current record's "ClaFinanciamiento" value
 * @method DatSieDocenteadministrativo getDatSieDocenteadministrativo() Returns the current record's "DatSieDocenteadministrativo" value
 * @method Doctrine_Collection         getDatSlnCursoOferta()           Returns the current record's "DatSlnCursoOferta" collection
 * @method Doctrine_Collection         getDatSlnCursoOferta16()         Returns the current record's "DatSlnCursoOferta_16" collection
 * @method Doctrine_Collection         getDatSlnCursoOferta17()         Returns the current record's "DatSlnCursoOferta_17" collection
 * @method Doctrine_Collection         getDatSlnCursoOferta18()         Returns the current record's "DatSlnCursoOferta_18" collection
 * @method Doctrine_Collection         getDatSlnCursoOferta19()         Returns the current record's "DatSlnCursoOferta_19" collection
 * @method Doctrine_Collection         getDatSlnCursoOferta20()         Returns the current record's "DatSlnCursoOferta_20" collection
 * @method Doctrine_Collection         getRelDocenteItems()             Returns the current record's "RelDocenteItems" collection
 * @method Doctrine_Collection         getRelDocenteItems5()            Returns the current record's "RelDocenteItems_5" collection
 * @method Doctrine_Collection         getRelDocenteItems6()            Returns the current record's "RelDocenteItems_6" collection
 * @method Doctrine_Collection         getRelDocenteItems7()            Returns the current record's "RelDocenteItems_7" collection
 * @method Doctrine_Collection         getRelDocenteItems8()            Returns the current record's "RelDocenteItems_8" collection
 * @method Doctrine_Collection         getRelDocenteItems9()            Returns the current record's "RelDocenteItems_9" collection
 * @method DatSieDocente               setCiDocenteId()                 Sets the current record's "ci_docente_id" value
 * @method DatSieDocente               setGestionId()                   Sets the current record's "gestion_id" value
 * @method DatSieDocente               setCodUeId()                     Sets the current record's "cod_ue_id" value
 * @method DatSieDocente               setPeriodoId()                   Sets the current record's "periodo_id" value
 * @method DatSieDocente               setOperativoId()                 Sets the current record's "operativo_id" value
 * @method DatSieDocente               setSubCeaId()                    Sets the current record's "sub_cea_id" value
 * @method DatSieDocente               setCargoId()                     Sets the current record's "cargo_id" value
 * @method DatSieDocente               setMes()                         Sets the current record's "mes" value
 * @method DatSieDocente               setFinanciamientoId()            Sets the current record's "financiamiento_id" value
 * @method DatSieDocente               setClaCargo()                    Sets the current record's "ClaCargo" value
 * @method DatSieDocente               setDatSieUnidadEducativa()       Sets the current record's "DatSieUnidadEducativa" value
 * @method DatSieDocente               setDatSieUnidadEducativa3()      Sets the current record's "DatSieUnidadEducativa_3" value
 * @method DatSieDocente               setDatSieUnidadEducativa4()      Sets the current record's "DatSieUnidadEducativa_4" value
 * @method DatSieDocente               setDatSieUnidadEducativa5()      Sets the current record's "DatSieUnidadEducativa_5" value
 * @method DatSieDocente               setDatSieUnidadEducativa6()      Sets the current record's "DatSieUnidadEducativa_6" value
 * @method DatSieDocente               setClaFinanciamiento()           Sets the current record's "ClaFinanciamiento" value
 * @method DatSieDocente               setDatSieDocenteadministrativo() Sets the current record's "DatSieDocenteadministrativo" value
 * @method DatSieDocente               setDatSlnCursoOferta()           Sets the current record's "DatSlnCursoOferta" collection
 * @method DatSieDocente               setDatSlnCursoOferta16()         Sets the current record's "DatSlnCursoOferta_16" collection
 * @method DatSieDocente               setDatSlnCursoOferta17()         Sets the current record's "DatSlnCursoOferta_17" collection
 * @method DatSieDocente               setDatSlnCursoOferta18()         Sets the current record's "DatSlnCursoOferta_18" collection
 * @method DatSieDocente               setDatSlnCursoOferta19()         Sets the current record's "DatSlnCursoOferta_19" collection
 * @method DatSieDocente               setDatSlnCursoOferta20()         Sets the current record's "DatSlnCursoOferta_20" collection
 * @method DatSieDocente               setRelDocenteItems()             Sets the current record's "RelDocenteItems" collection
 * @method DatSieDocente               setRelDocenteItems5()            Sets the current record's "RelDocenteItems_5" collection
 * @method DatSieDocente               setRelDocenteItems6()            Sets the current record's "RelDocenteItems_6" collection
 * @method DatSieDocente               setRelDocenteItems7()            Sets the current record's "RelDocenteItems_7" collection
 * @method DatSieDocente               setRelDocenteItems8()            Sets the current record's "RelDocenteItems_8" collection
 * @method DatSieDocente               setRelDocenteItems9()            Sets the current record's "RelDocenteItems_9" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatSieDocente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_sie_docente');
        $this->hasColumn('ci_docente_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('periodo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('operativo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('sub_cea_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('cargo_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('mes', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('financiamiento_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaCargo', array(
             'local' => 'cargo_id',
             'foreign' => 'id_cargo'));

        $this->hasOne('DatSieUnidadEducativa', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue_id'));

        $this->hasOne('DatSieUnidadEducativa as DatSieUnidadEducativa_3', array(
             'local' => 'periodo_id',
             'foreign' => 'periodo_id'));

        $this->hasOne('DatSieUnidadEducativa as DatSieUnidadEducativa_4', array(
             'local' => 'operativo_id',
             'foreign' => 'operativo_id'));

        $this->hasOne('DatSieUnidadEducativa as DatSieUnidadEducativa_5', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasOne('DatSieUnidadEducativa as DatSieUnidadEducativa_6', array(
             'local' => 'sub_cea_id',
             'foreign' => 'sub_cea'));

        $this->hasOne('ClaFinanciamiento', array(
             'local' => 'financiamiento_id',
             'foreign' => 'id_financiamiento'));

        $this->hasOne('DatSieDocenteadministrativo', array(
             'local' => 'ci_docente_id',
             'foreign' => 'ci'));

        $this->hasMany('DatSlnCursoOferta', array(
             'local' => 'ci_docente_id',
             'foreign' => 'docente_id'));

        $this->hasMany('DatSlnCursoOferta as DatSlnCursoOferta_16', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasMany('DatSlnCursoOferta as DatSlnCursoOferta_17', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue_id'));

        $this->hasMany('DatSlnCursoOferta as DatSlnCursoOferta_18', array(
             'local' => 'periodo_id',
             'foreign' => 'periodo_id'));

        $this->hasMany('DatSlnCursoOferta as DatSlnCursoOferta_19', array(
             'local' => 'operativo_id',
             'foreign' => 'operativo_id'));

        $this->hasMany('DatSlnCursoOferta as DatSlnCursoOferta_20', array(
             'local' => 'sub_cea_id',
             'foreign' => 'sub_cea_id'));

        $this->hasMany('RelDocenteItems', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasMany('RelDocenteItems as RelDocenteItems_5', array(
             'local' => 'ci_docente_id',
             'foreign' => 'ci_docente_id'));

        $this->hasMany('RelDocenteItems as RelDocenteItems_6', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue_id'));

        $this->hasMany('RelDocenteItems as RelDocenteItems_7', array(
             'local' => 'periodo_id',
             'foreign' => 'periodo_id'));

        $this->hasMany('RelDocenteItems as RelDocenteItems_8', array(
             'local' => 'operativo_id',
             'foreign' => 'operativo_id'));

        $this->hasMany('RelDocenteItems as RelDocenteItems_9', array(
             'local' => 'sub_cea_id',
             'foreign' => 'sub_cea_id'));
    }
}