<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RelTraUsuarioProceso', 'doctrine');

/**
 * BaseRelTraUsuarioProceso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $proceso_id
 * @property integer $gestion_id
 * @property integer $vigente
 * @property integer $grupo_id
 * @property ClaGestion $ClaGestion
 * @property ClaTraProceso $ClaTraProceso
 * @property DatUsuGrupo $DatUsuGrupo
 * 
 * @method integer              getProcesoId()     Returns the current record's "proceso_id" value
 * @method integer              getGestionId()     Returns the current record's "gestion_id" value
 * @method integer              getVigente()       Returns the current record's "vigente" value
 * @method integer              getGrupoId()       Returns the current record's "grupo_id" value
 * @method ClaGestion           getClaGestion()    Returns the current record's "ClaGestion" value
 * @method ClaTraProceso        getClaTraProceso() Returns the current record's "ClaTraProceso" value
 * @method DatUsuGrupo          getDatUsuGrupo()   Returns the current record's "DatUsuGrupo" value
 * @method RelTraUsuarioProceso setProcesoId()     Sets the current record's "proceso_id" value
 * @method RelTraUsuarioProceso setGestionId()     Sets the current record's "gestion_id" value
 * @method RelTraUsuarioProceso setVigente()       Sets the current record's "vigente" value
 * @method RelTraUsuarioProceso setGrupoId()       Sets the current record's "grupo_id" value
 * @method RelTraUsuarioProceso setClaGestion()    Sets the current record's "ClaGestion" value
 * @method RelTraUsuarioProceso setClaTraProceso() Sets the current record's "ClaTraProceso" value
 * @method RelTraUsuarioProceso setDatUsuGrupo()   Sets the current record's "DatUsuGrupo" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRelTraUsuarioProceso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rel_tra_usuario_proceso');
        $this->hasColumn('proceso_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('vigente', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('grupo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaGestion', array(
             'local' => 'gestion_id',
             'foreign' => 'id_gestion'));

        $this->hasOne('ClaTraProceso', array(
             'local' => 'proceso_id',
             'foreign' => 'id_proceso'));

        $this->hasOne('DatUsuGrupo', array(
             'local' => 'grupo_id',
             'foreign' => 'id'));
    }
}