<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CtrRdeTraslados', 'doctrine');

/**
 * BaseCtrRdeTraslados
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_traslado
 * @property timestamp $fecha_traslado
 * @property integer $inscripcion_id
 * @property integer $gestion_id
 * @property integer $usuario_id
 * @property integer $motivo_id
 * @property string $cod_ue_id_origen
 * @property ClaMotivo $ClaMotivo
 * @property DatRdeInscripcion $DatRdeInscripcion
 * @property DatRdeInscripcion $DatRdeInscripcion_3
 * @property DatUsuUsuario $DatUsuUsuario
 * @property DatRueUnidadEducativa $DatRueUnidadEducativa
 * 
 * @method integer               getIdTraslado()            Returns the current record's "id_traslado" value
 * @method timestamp             getFechaTraslado()         Returns the current record's "fecha_traslado" value
 * @method integer               getInscripcionId()         Returns the current record's "inscripcion_id" value
 * @method integer               getGestionId()             Returns the current record's "gestion_id" value
 * @method integer               getUsuarioId()             Returns the current record's "usuario_id" value
 * @method integer               getMotivoId()              Returns the current record's "motivo_id" value
 * @method string                getCodUeIdOrigen()         Returns the current record's "cod_ue_id_origen" value
 * @method ClaMotivo             getClaMotivo()             Returns the current record's "ClaMotivo" value
 * @method DatRdeInscripcion     getDatRdeInscripcion()     Returns the current record's "DatRdeInscripcion" value
 * @method DatRdeInscripcion     getDatRdeInscripcion3()    Returns the current record's "DatRdeInscripcion_3" value
 * @method DatUsuUsuario         getDatUsuUsuario()         Returns the current record's "DatUsuUsuario" value
 * @method DatRueUnidadEducativa getDatRueUnidadEducativa() Returns the current record's "DatRueUnidadEducativa" value
 * @method CtrRdeTraslados       setIdTraslado()            Sets the current record's "id_traslado" value
 * @method CtrRdeTraslados       setFechaTraslado()         Sets the current record's "fecha_traslado" value
 * @method CtrRdeTraslados       setInscripcionId()         Sets the current record's "inscripcion_id" value
 * @method CtrRdeTraslados       setGestionId()             Sets the current record's "gestion_id" value
 * @method CtrRdeTraslados       setUsuarioId()             Sets the current record's "usuario_id" value
 * @method CtrRdeTraslados       setMotivoId()              Sets the current record's "motivo_id" value
 * @method CtrRdeTraslados       setCodUeIdOrigen()         Sets the current record's "cod_ue_id_origen" value
 * @method CtrRdeTraslados       setClaMotivo()             Sets the current record's "ClaMotivo" value
 * @method CtrRdeTraslados       setDatRdeInscripcion()     Sets the current record's "DatRdeInscripcion" value
 * @method CtrRdeTraslados       setDatRdeInscripcion3()    Sets the current record's "DatRdeInscripcion_3" value
 * @method CtrRdeTraslados       setDatUsuUsuario()         Sets the current record's "DatUsuUsuario" value
 * @method CtrRdeTraslados       setDatRueUnidadEducativa() Sets the current record's "DatRueUnidadEducativa" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCtrRdeTraslados extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ctr_rde_traslados');
        $this->hasColumn('id_traslado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('fecha_traslado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('inscripcion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('motivo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('cod_ue_id_origen', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaMotivo', array(
             'local' => 'motivo_id',
             'foreign' => 'id_motivo'));

        $this->hasOne('DatRdeInscripcion', array(
             'local' => 'inscripcion_id',
             'foreign' => 'id_inscripcion'));

        $this->hasOne('DatRdeInscripcion as DatRdeInscripcion_3', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasOne('DatUsuUsuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));

        $this->hasOne('DatRueUnidadEducativa', array(
             'local' => 'cod_ue_id_origen',
             'foreign' => 'cod_ue'));
    }
}