<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatIfrJurisdiccionGeografica', 'doctrine');

/**
 * BaseDatIfrJurisdiccionGeografica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cod_le
 * @property string $localidad_id
 * @property integer $canton_id
 * @property integer $seccion_id
 * @property integer $provincia_id
 * @property integer $departamento_id
 * @property ClaLocalidad $ClaLocalidad
 * @property ClaLocalidad $ClaLocalidad_2
 * @property ClaLocalidad $ClaLocalidad_3
 * @property ClaLocalidad $ClaLocalidad_4
 * @property ClaLocalidad $ClaLocalidad_5
 * @property Doctrine_Collection $DatIfrJurisdiccionAdministrativa
 * @property Doctrine_Collection $DatIfrUnidadEducativa
 * @property Doctrine_Collection $DatNlcLocalEducativo
 * @property Doctrine_Collection $DatRueUnidadEducativa
 * 
 * @method string                       getCodLe()                            Returns the current record's "cod_le" value
 * @method string                       getLocalidadId()                      Returns the current record's "localidad_id" value
 * @method integer                      getCantonId()                         Returns the current record's "canton_id" value
 * @method integer                      getSeccionId()                        Returns the current record's "seccion_id" value
 * @method integer                      getProvinciaId()                      Returns the current record's "provincia_id" value
 * @method integer                      getDepartamentoId()                   Returns the current record's "departamento_id" value
 * @method ClaLocalidad                 getClaLocalidad()                     Returns the current record's "ClaLocalidad" value
 * @method ClaLocalidad                 getClaLocalidad2()                    Returns the current record's "ClaLocalidad_2" value
 * @method ClaLocalidad                 getClaLocalidad3()                    Returns the current record's "ClaLocalidad_3" value
 * @method ClaLocalidad                 getClaLocalidad4()                    Returns the current record's "ClaLocalidad_4" value
 * @method ClaLocalidad                 getClaLocalidad5()                    Returns the current record's "ClaLocalidad_5" value
 * @method Doctrine_Collection          getDatIfrJurisdiccionAdministrativa() Returns the current record's "DatIfrJurisdiccionAdministrativa" collection
 * @method Doctrine_Collection          getDatIfrUnidadEducativa()            Returns the current record's "DatIfrUnidadEducativa" collection
 * @method Doctrine_Collection          getDatNlcLocalEducativo()             Returns the current record's "DatNlcLocalEducativo" collection
 * @method Doctrine_Collection          getDatRueUnidadEducativa()            Returns the current record's "DatRueUnidadEducativa" collection
 * @method DatIfrJurisdiccionGeografica setCodLe()                            Sets the current record's "cod_le" value
 * @method DatIfrJurisdiccionGeografica setLocalidadId()                      Sets the current record's "localidad_id" value
 * @method DatIfrJurisdiccionGeografica setCantonId()                         Sets the current record's "canton_id" value
 * @method DatIfrJurisdiccionGeografica setSeccionId()                        Sets the current record's "seccion_id" value
 * @method DatIfrJurisdiccionGeografica setProvinciaId()                      Sets the current record's "provincia_id" value
 * @method DatIfrJurisdiccionGeografica setDepartamentoId()                   Sets the current record's "departamento_id" value
 * @method DatIfrJurisdiccionGeografica setClaLocalidad()                     Sets the current record's "ClaLocalidad" value
 * @method DatIfrJurisdiccionGeografica setClaLocalidad2()                    Sets the current record's "ClaLocalidad_2" value
 * @method DatIfrJurisdiccionGeografica setClaLocalidad3()                    Sets the current record's "ClaLocalidad_3" value
 * @method DatIfrJurisdiccionGeografica setClaLocalidad4()                    Sets the current record's "ClaLocalidad_4" value
 * @method DatIfrJurisdiccionGeografica setClaLocalidad5()                    Sets the current record's "ClaLocalidad_5" value
 * @method DatIfrJurisdiccionGeografica setDatIfrJurisdiccionAdministrativa() Sets the current record's "DatIfrJurisdiccionAdministrativa" collection
 * @method DatIfrJurisdiccionGeografica setDatIfrUnidadEducativa()            Sets the current record's "DatIfrUnidadEducativa" collection
 * @method DatIfrJurisdiccionGeografica setDatNlcLocalEducativo()             Sets the current record's "DatNlcLocalEducativo" collection
 * @method DatIfrJurisdiccionGeografica setDatRueUnidadEducativa()            Sets the current record's "DatRueUnidadEducativa" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatIfrJurisdiccionGeografica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_ifr_jurisdiccion_geografica');
        $this->hasColumn('cod_le', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('localidad_id', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('canton_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('seccion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('provincia_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('departamento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaLocalidad', array(
             'local' => 'localidad_id',
             'foreign' => 'id_localidad'));

        $this->hasOne('ClaLocalidad as ClaLocalidad_2', array(
             'local' => 'canton_id',
             'foreign' => 'canton_id'));

        $this->hasOne('ClaLocalidad as ClaLocalidad_3', array(
             'local' => 'seccion_id',
             'foreign' => 'seccion_id'));

        $this->hasOne('ClaLocalidad as ClaLocalidad_4', array(
             'local' => 'provincia_id',
             'foreign' => 'provincia_id'));

        $this->hasOne('ClaLocalidad as ClaLocalidad_5', array(
             'local' => 'departamento_id',
             'foreign' => 'departamento_id'));

        $this->hasMany('DatIfrJurisdiccionAdministrativa', array(
             'local' => 'cod_le',
             'foreign' => 'cod_le_id'));

        $this->hasMany('DatIfrUnidadEducativa', array(
             'local' => 'cod_le',
             'foreign' => 'cod_le_id'));

        $this->hasMany('DatNlcLocalEducativo', array(
             'local' => 'cod_le',
             'foreign' => 'cod_le_id'));

        $this->hasMany('DatRueUnidadEducativa', array(
             'local' => 'cod_le',
             'foreign' => 'cod_le_id'));
    }
}