<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VEstudianteEspecial', 'doctrine');

/**
 * BaseVEstudianteEspecial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $gestion_id
 * @property string $desc_departamento
 * @property integer $cod_distrito
 * @property string $distrito
 * @property string $cod_ue
 * @property string $desc_ue
 * @property string $desc_nivel
 * @property integer $id_ciclo
 * @property string $desc_ciclo
 * @property integer $id_grado
 * @property string $desc_grado
 * @property string $desc_turno
 * @property string $paralelo
 * @property string $discapacidad
 * @property string $codigo_rude
 * @property string $paterno
 * @property string $materno
 * @property string $nombre
 * @property date $fecha_nacimiento
 * @property string $genero
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getGestionId()         Returns the current record's "gestion_id" value
 * @method string              getDescDepartamento()  Returns the current record's "desc_departamento" value
 * @method integer             getCodDistrito()       Returns the current record's "cod_distrito" value
 * @method string              getDistrito()          Returns the current record's "distrito" value
 * @method string              getCodUe()             Returns the current record's "cod_ue" value
 * @method string              getDescUe()            Returns the current record's "desc_ue" value
 * @method string              getDescNivel()         Returns the current record's "desc_nivel" value
 * @method integer             getIdCiclo()           Returns the current record's "id_ciclo" value
 * @method string              getDescCiclo()         Returns the current record's "desc_ciclo" value
 * @method integer             getIdGrado()           Returns the current record's "id_grado" value
 * @method string              getDescGrado()         Returns the current record's "desc_grado" value
 * @method string              getDescTurno()         Returns the current record's "desc_turno" value
 * @method string              getParalelo()          Returns the current record's "paralelo" value
 * @method string              getDiscapacidad()      Returns the current record's "discapacidad" value
 * @method string              getCodigoRude()        Returns the current record's "codigo_rude" value
 * @method string              getPaterno()           Returns the current record's "paterno" value
 * @method string              getMaterno()           Returns the current record's "materno" value
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method date                getFechaNacimiento()   Returns the current record's "fecha_nacimiento" value
 * @method string              getGenero()            Returns the current record's "genero" value
 * @method VEstudianteEspecial setId()                Sets the current record's "id" value
 * @method VEstudianteEspecial setGestionId()         Sets the current record's "gestion_id" value
 * @method VEstudianteEspecial setDescDepartamento()  Sets the current record's "desc_departamento" value
 * @method VEstudianteEspecial setCodDistrito()       Sets the current record's "cod_distrito" value
 * @method VEstudianteEspecial setDistrito()          Sets the current record's "distrito" value
 * @method VEstudianteEspecial setCodUe()             Sets the current record's "cod_ue" value
 * @method VEstudianteEspecial setDescUe()            Sets the current record's "desc_ue" value
 * @method VEstudianteEspecial setDescNivel()         Sets the current record's "desc_nivel" value
 * @method VEstudianteEspecial setIdCiclo()           Sets the current record's "id_ciclo" value
 * @method VEstudianteEspecial setDescCiclo()         Sets the current record's "desc_ciclo" value
 * @method VEstudianteEspecial setIdGrado()           Sets the current record's "id_grado" value
 * @method VEstudianteEspecial setDescGrado()         Sets the current record's "desc_grado" value
 * @method VEstudianteEspecial setDescTurno()         Sets the current record's "desc_turno" value
 * @method VEstudianteEspecial setParalelo()          Sets the current record's "paralelo" value
 * @method VEstudianteEspecial setDiscapacidad()      Sets the current record's "discapacidad" value
 * @method VEstudianteEspecial setCodigoRude()        Sets the current record's "codigo_rude" value
 * @method VEstudianteEspecial setPaterno()           Sets the current record's "paterno" value
 * @method VEstudianteEspecial setMaterno()           Sets the current record's "materno" value
 * @method VEstudianteEspecial setNombre()            Sets the current record's "nombre" value
 * @method VEstudianteEspecial setFechaNacimiento()   Sets the current record's "fecha_nacimiento" value
 * @method VEstudianteEspecial setGenero()            Sets the current record's "genero" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVEstudianteEspecial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('v_estudiante_especial');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('desc_departamento', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('cod_distrito', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('distrito', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('cod_ue', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('desc_ue', 'string', 70, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '70',
             ));
        $this->hasColumn('desc_nivel', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('id_ciclo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('desc_ciclo', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('id_grado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('desc_grado', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('desc_turno', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('paralelo', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('discapacidad', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('codigo_rude', 'string', 18, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '18',
             ));
        $this->hasColumn('paterno', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('materno', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('fecha_nacimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1900-01-01',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('genero', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}