<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatRdaDocentesadministrativos', 'doctrine');

/**
 * BaseDatRdaDocentesadministrativos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rda
 * @property integer $ci
 * @property string $paterno
 * @property string $materno
 * @property string $nombre
 * @property string $fecha_nacimiento
 * @property string $genero
 * @property Doctrine_Collection $DatSieDocenteadministrativo
 * 
 * @method integer                       getRda()                         Returns the current record's "rda" value
 * @method integer                       getCi()                          Returns the current record's "ci" value
 * @method string                        getPaterno()                     Returns the current record's "paterno" value
 * @method string                        getMaterno()                     Returns the current record's "materno" value
 * @method string                        getNombre()                      Returns the current record's "nombre" value
 * @method string                        getFechaNacimiento()             Returns the current record's "fecha_nacimiento" value
 * @method string                        getGenero()                      Returns the current record's "genero" value
 * @method Doctrine_Collection           getDatSieDocenteadministrativo() Returns the current record's "DatSieDocenteadministrativo" collection
 * @method DatRdaDocentesadministrativos setRda()                         Sets the current record's "rda" value
 * @method DatRdaDocentesadministrativos setCi()                          Sets the current record's "ci" value
 * @method DatRdaDocentesadministrativos setPaterno()                     Sets the current record's "paterno" value
 * @method DatRdaDocentesadministrativos setMaterno()                     Sets the current record's "materno" value
 * @method DatRdaDocentesadministrativos setNombre()                      Sets the current record's "nombre" value
 * @method DatRdaDocentesadministrativos setFechaNacimiento()             Sets the current record's "fecha_nacimiento" value
 * @method DatRdaDocentesadministrativos setGenero()                      Sets the current record's "genero" value
 * @method DatRdaDocentesadministrativos setDatSieDocenteadministrativo() Sets the current record's "DatSieDocenteadministrativo" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatRdaDocentesadministrativos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_rda_docentesadministrativos');
        $this->hasColumn('rda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('ci', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('paterno', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('materno', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('fecha_nacimiento', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('genero', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DatSieDocenteadministrativo', array(
             'local' => 'rda',
             'foreign' => 'rda_id'));
    }
}