<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaEdaEstadoDesastre', 'doctrine');

/**
 * BaseClaEdaEstadoDesastre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_estado_desastre
 * @property string $desc_estado_desastre
 * @property Doctrine_Collection $DatEdaEvento
 * 
 * @method integer              getIdEstadoDesastre()     Returns the current record's "id_estado_desastre" value
 * @method string               getDescEstadoDesastre()   Returns the current record's "desc_estado_desastre" value
 * @method Doctrine_Collection  getDatEdaEvento()         Returns the current record's "DatEdaEvento" collection
 * @method ClaEdaEstadoDesastre setIdEstadoDesastre()     Sets the current record's "id_estado_desastre" value
 * @method ClaEdaEstadoDesastre setDescEstadoDesastre()   Sets the current record's "desc_estado_desastre" value
 * @method ClaEdaEstadoDesastre setDatEdaEvento()         Sets the current record's "DatEdaEvento" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaEdaEstadoDesastre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_eda_estado_desastre');
        $this->hasColumn('id_estado_desastre', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('desc_estado_desastre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '100',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DatEdaEvento', array(
             'local' => 'id_estado_desastre',
             'foreign' => 'estado_desastre_id'));
    }
}