<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaGrado', 'doctrine');

/**
 * BaseClaGrado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nivel_id
 * @property integer $ciclo_id
 * @property integer $id_grado
 * @property string $desc_grado
 * @property integer $edad_minima
 * @property integer $edad_maxima
 * @property integer $seguimiento
 * @property ClaCiclo $ClaCiclo
 * @property ClaCiclo $ClaCiclo_2
 * @property Doctrine_Collection $CtrSieCurso
 * @property Doctrine_Collection $CtrSieCurso_3
 * @property Doctrine_Collection $CtrSieCurso_4
 * @property Doctrine_Collection $DatAltCursoTecnica
 * @property Doctrine_Collection $DatAltCursoTecnica_2
 * @property Doctrine_Collection $DatAltCursoTecnica_3
 * @property Doctrine_Collection $DatEspCurso
 * @property Doctrine_Collection $DatEspCurso_2
 * @property Doctrine_Collection $DatEspCurso_3
 * @property Doctrine_Collection $DatRueCursoTramite
 * @property Doctrine_Collection $DatRueCursoTramite_2
 * @property Doctrine_Collection $DatRueCursoTramite_3
 * @property Doctrine_Collection $DatSieCurso
 * @property Doctrine_Collection $DatSieCurso_3
 * @property Doctrine_Collection $DatSieCurso_4
 * @property Doctrine_Collection $DatSieOfertaCurricular
 * @property Doctrine_Collection $DatSieOfertaCurricular_3
 * @property Doctrine_Collection $DatSieOfertaCurricular_4
 * @property Doctrine_Collection $SdatSieCurso
 * @property Doctrine_Collection $SdatSieCurso_3
 * @property Doctrine_Collection $SdatSieCurso_4
 * @property Doctrine_Collection $SdatSieCursoespecial
 * @property Doctrine_Collection $SdatSieCursoespecial_4
 * @property Doctrine_Collection $SdatSieCursoespecial_5
 * @property Doctrine_Collection $SdatSieCursotecnica
 * @property Doctrine_Collection $SdatSieCursotecnica_2
 * @property Doctrine_Collection $SdatSieCursotecnica_3
 * 
 * @method integer             getNivelId()                  Returns the current record's "nivel_id" value
 * @method integer             getCicloId()                  Returns the current record's "ciclo_id" value
 * @method integer             getIdGrado()                  Returns the current record's "id_grado" value
 * @method string              getDescGrado()                Returns the current record's "desc_grado" value
 * @method integer             getEdadMinima()               Returns the current record's "edad_minima" value
 * @method integer             getEdadMaxima()               Returns the current record's "edad_maxima" value
 * @method integer             getSeguimiento()              Returns the current record's "seguimiento" value
 * @method ClaCiclo            getClaCiclo()                 Returns the current record's "ClaCiclo" value
 * @method ClaCiclo            getClaCiclo2()                Returns the current record's "ClaCiclo_2" value
 * @method Doctrine_Collection getCtrSieCurso()              Returns the current record's "CtrSieCurso" collection
 * @method Doctrine_Collection getCtrSieCurso3()             Returns the current record's "CtrSieCurso_3" collection
 * @method Doctrine_Collection getCtrSieCurso4()             Returns the current record's "CtrSieCurso_4" collection
 * @method Doctrine_Collection getDatAltCursoTecnica()       Returns the current record's "DatAltCursoTecnica" collection
 * @method Doctrine_Collection getDatAltCursoTecnica2()      Returns the current record's "DatAltCursoTecnica_2" collection
 * @method Doctrine_Collection getDatAltCursoTecnica3()      Returns the current record's "DatAltCursoTecnica_3" collection
 * @method Doctrine_Collection getDatEspCurso()              Returns the current record's "DatEspCurso" collection
 * @method Doctrine_Collection getDatEspCurso2()             Returns the current record's "DatEspCurso_2" collection
 * @method Doctrine_Collection getDatEspCurso3()             Returns the current record's "DatEspCurso_3" collection
 * @method Doctrine_Collection getDatRueCursoTramite()       Returns the current record's "DatRueCursoTramite" collection
 * @method Doctrine_Collection getDatRueCursoTramite2()      Returns the current record's "DatRueCursoTramite_2" collection
 * @method Doctrine_Collection getDatRueCursoTramite3()      Returns the current record's "DatRueCursoTramite_3" collection
 * @method Doctrine_Collection getDatSieCurso()              Returns the current record's "DatSieCurso" collection
 * @method Doctrine_Collection getDatSieCurso3()             Returns the current record's "DatSieCurso_3" collection
 * @method Doctrine_Collection getDatSieCurso4()             Returns the current record's "DatSieCurso_4" collection
 * @method Doctrine_Collection getDatSieOfertaCurricular()   Returns the current record's "DatSieOfertaCurricular" collection
 * @method Doctrine_Collection getDatSieOfertaCurricular3()  Returns the current record's "DatSieOfertaCurricular_3" collection
 * @method Doctrine_Collection getDatSieOfertaCurricular4()  Returns the current record's "DatSieOfertaCurricular_4" collection
 * @method Doctrine_Collection getSdatSieCurso()             Returns the current record's "SdatSieCurso" collection
 * @method Doctrine_Collection getSdatSieCurso3()            Returns the current record's "SdatSieCurso_3" collection
 * @method Doctrine_Collection getSdatSieCurso4()            Returns the current record's "SdatSieCurso_4" collection
 * @method Doctrine_Collection getSdatSieCursoespecial()     Returns the current record's "SdatSieCursoespecial" collection
 * @method Doctrine_Collection getSdatSieCursoespecial4()    Returns the current record's "SdatSieCursoespecial_4" collection
 * @method Doctrine_Collection getSdatSieCursoespecial5()    Returns the current record's "SdatSieCursoespecial_5" collection
 * @method Doctrine_Collection getSdatSieCursotecnica()      Returns the current record's "SdatSieCursotecnica" collection
 * @method Doctrine_Collection getSdatSieCursotecnica2()     Returns the current record's "SdatSieCursotecnica_2" collection
 * @method Doctrine_Collection getSdatSieCursotecnica3()     Returns the current record's "SdatSieCursotecnica_3" collection
 * @method ClaGrado            setNivelId()                  Sets the current record's "nivel_id" value
 * @method ClaGrado            setCicloId()                  Sets the current record's "ciclo_id" value
 * @method ClaGrado            setIdGrado()                  Sets the current record's "id_grado" value
 * @method ClaGrado            setDescGrado()                Sets the current record's "desc_grado" value
 * @method ClaGrado            setEdadMinima()               Sets the current record's "edad_minima" value
 * @method ClaGrado            setEdadMaxima()               Sets the current record's "edad_maxima" value
 * @method ClaGrado            setSeguimiento()              Sets the current record's "seguimiento" value
 * @method ClaGrado            setClaCiclo()                 Sets the current record's "ClaCiclo" value
 * @method ClaGrado            setClaCiclo2()                Sets the current record's "ClaCiclo_2" value
 * @method ClaGrado            setCtrSieCurso()              Sets the current record's "CtrSieCurso" collection
 * @method ClaGrado            setCtrSieCurso3()             Sets the current record's "CtrSieCurso_3" collection
 * @method ClaGrado            setCtrSieCurso4()             Sets the current record's "CtrSieCurso_4" collection
 * @method ClaGrado            setDatAltCursoTecnica()       Sets the current record's "DatAltCursoTecnica" collection
 * @method ClaGrado            setDatAltCursoTecnica2()      Sets the current record's "DatAltCursoTecnica_2" collection
 * @method ClaGrado            setDatAltCursoTecnica3()      Sets the current record's "DatAltCursoTecnica_3" collection
 * @method ClaGrado            setDatEspCurso()              Sets the current record's "DatEspCurso" collection
 * @method ClaGrado            setDatEspCurso2()             Sets the current record's "DatEspCurso_2" collection
 * @method ClaGrado            setDatEspCurso3()             Sets the current record's "DatEspCurso_3" collection
 * @method ClaGrado            setDatRueCursoTramite()       Sets the current record's "DatRueCursoTramite" collection
 * @method ClaGrado            setDatRueCursoTramite2()      Sets the current record's "DatRueCursoTramite_2" collection
 * @method ClaGrado            setDatRueCursoTramite3()      Sets the current record's "DatRueCursoTramite_3" collection
 * @method ClaGrado            setDatSieCurso()              Sets the current record's "DatSieCurso" collection
 * @method ClaGrado            setDatSieCurso3()             Sets the current record's "DatSieCurso_3" collection
 * @method ClaGrado            setDatSieCurso4()             Sets the current record's "DatSieCurso_4" collection
 * @method ClaGrado            setDatSieOfertaCurricular()   Sets the current record's "DatSieOfertaCurricular" collection
 * @method ClaGrado            setDatSieOfertaCurricular3()  Sets the current record's "DatSieOfertaCurricular_3" collection
 * @method ClaGrado            setDatSieOfertaCurricular4()  Sets the current record's "DatSieOfertaCurricular_4" collection
 * @method ClaGrado            setSdatSieCurso()             Sets the current record's "SdatSieCurso" collection
 * @method ClaGrado            setSdatSieCurso3()            Sets the current record's "SdatSieCurso_3" collection
 * @method ClaGrado            setSdatSieCurso4()            Sets the current record's "SdatSieCurso_4" collection
 * @method ClaGrado            setSdatSieCursoespecial()     Sets the current record's "SdatSieCursoespecial" collection
 * @method ClaGrado            setSdatSieCursoespecial4()    Sets the current record's "SdatSieCursoespecial_4" collection
 * @method ClaGrado            setSdatSieCursoespecial5()    Sets the current record's "SdatSieCursoespecial_5" collection
 * @method ClaGrado            setSdatSieCursotecnica()      Sets the current record's "SdatSieCursotecnica" collection
 * @method ClaGrado            setSdatSieCursotecnica2()     Sets the current record's "SdatSieCursotecnica_2" collection
 * @method ClaGrado            setSdatSieCursotecnica3()     Sets the current record's "SdatSieCursotecnica_3" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaGrado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_grado');
        $this->hasColumn('nivel_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('ciclo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('id_grado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('desc_grado', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('edad_minima', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('edad_maxima', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('seguimiento', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaCiclo', array(
             'local' => 'ciclo_id',
             'foreign' => 'id_ciclo'));

        $this->hasOne('ClaCiclo as ClaCiclo_2', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasMany('CtrSieCurso', array(
             'local' => 'id_grado',
             'foreign' => 'grado_id'));

        $this->hasMany('CtrSieCurso as CtrSieCurso_3', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasMany('CtrSieCurso as CtrSieCurso_4', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasMany('DatAltCursoTecnica', array(
             'local' => 'id_grado',
             'foreign' => 'grado_id'));

        $this->hasMany('DatAltCursoTecnica as DatAltCursoTecnica_2', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasMany('DatAltCursoTecnica as DatAltCursoTecnica_3', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasMany('DatEspCurso', array(
             'local' => 'id_grado',
             'foreign' => 'grado_id'));

        $this->hasMany('DatEspCurso as DatEspCurso_2', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasMany('DatEspCurso as DatEspCurso_3', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasMany('DatRueCursoTramite', array(
             'local' => 'id_grado',
             'foreign' => 'grado_id'));

        $this->hasMany('DatRueCursoTramite as DatRueCursoTramite_2', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasMany('DatRueCursoTramite as DatRueCursoTramite_3', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasMany('DatSieCurso', array(
             'local' => 'id_grado',
             'foreign' => 'grado_id'));

        $this->hasMany('DatSieCurso as DatSieCurso_3', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasMany('DatSieCurso as DatSieCurso_4', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasMany('DatSieOfertaCurricular', array(
             'local' => 'id_grado',
             'foreign' => 'grado_id'));

        $this->hasMany('DatSieOfertaCurricular as DatSieOfertaCurricular_3', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasMany('DatSieOfertaCurricular as DatSieOfertaCurricular_4', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasMany('SdatSieCurso', array(
             'local' => 'id_grado',
             'foreign' => 'grado_id'));

        $this->hasMany('SdatSieCurso as SdatSieCurso_3', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasMany('SdatSieCurso as SdatSieCurso_4', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasMany('SdatSieCursoespecial', array(
             'local' => 'id_grado',
             'foreign' => 'grado_id'));

        $this->hasMany('SdatSieCursoespecial as SdatSieCursoespecial_4', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasMany('SdatSieCursoespecial as SdatSieCursoespecial_5', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasMany('SdatSieCursotecnica', array(
             'local' => 'id_grado',
             'foreign' => 'grado_id'));

        $this->hasMany('SdatSieCursotecnica as SdatSieCursotecnica_2', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasMany('SdatSieCursotecnica as SdatSieCursotecnica_3', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));
    }
}