<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SdatRdeInscripcion', 'doctrine');

/**
 * BaseSdatRdeInscripcion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $inscripcion_id
 * @property integer $gestion_id
 * @property string $codigo_rude_id
 * @property integer $num_matricula
 * @property string $cod_ue_id
 * @property integer $periodo_id
 * @property integer $sub_cea_id
 * @property integer $grado_id
 * @property integer $ciclo_id
 * @property integer $nivel_id
 * @property string $paralelo
 * @property integer $turno_id
 * @property integer $estado_matricula_inicio_id
 * @property integer $estado_matricula_fin_id
 * @property string $cod_ue_procedencia_id
 * @property integer $observacion_id
 * @property string $observacion
 * @property date $fecha_inscripcion
 * @property string $apreciacion_id
 * @property DatRdeEstudiante $DatRdeEstudiante
 * @property ClaEstadoMatricula $ClaEstadoMatricula
 * @property ClaEstadoMatricula $ClaEstadoMatricula_3
 * @property SdatSieCurso $SdatSieCurso
 * @property SdatSieCurso $SdatSieCurso_5
 * @property SdatSieCurso $SdatSieCurso_6
 * @property SdatSieCurso $SdatSieCurso_7
 * @property SdatSieCurso $SdatSieCurso_8
 * @property SdatSieCurso $SdatSieCurso_9
 * @property SdatSieCurso $SdatSieCurso_10
 * @property SdatSieCurso $SdatSieCurso_11
 * 
 * @method integer            getInscripcionId()              Returns the current record's "inscripcion_id" value
 * @method integer            getGestionId()                  Returns the current record's "gestion_id" value
 * @method string             getCodigoRudeId()               Returns the current record's "codigo_rude_id" value
 * @method integer            getNumMatricula()               Returns the current record's "num_matricula" value
 * @method string             getCodUeId()                    Returns the current record's "cod_ue_id" value
 * @method integer            getPeriodoId()                  Returns the current record's "periodo_id" value
 * @method integer            getSubCeaId()                   Returns the current record's "sub_cea_id" value
 * @method integer            getGradoId()                    Returns the current record's "grado_id" value
 * @method integer            getCicloId()                    Returns the current record's "ciclo_id" value
 * @method integer            getNivelId()                    Returns the current record's "nivel_id" value
 * @method string             getParalelo()                   Returns the current record's "paralelo" value
 * @method integer            getTurnoId()                    Returns the current record's "turno_id" value
 * @method integer            getEstadoMatriculaInicioId()    Returns the current record's "estado_matricula_inicio_id" value
 * @method integer            getEstadoMatriculaFinId()       Returns the current record's "estado_matricula_fin_id" value
 * @method string             getCodUeProcedenciaId()         Returns the current record's "cod_ue_procedencia_id" value
 * @method integer            getObservacionId()              Returns the current record's "observacion_id" value
 * @method string             getObservacion()                Returns the current record's "observacion" value
 * @method date               getFechaInscripcion()           Returns the current record's "fecha_inscripcion" value
 * @method string             getApreciacionId()              Returns the current record's "apreciacion_id" value
 * @method DatRdeEstudiante   getDatRdeEstudiante()           Returns the current record's "DatRdeEstudiante" value
 * @method ClaEstadoMatricula getClaEstadoMatricula()         Returns the current record's "ClaEstadoMatricula" value
 * @method ClaEstadoMatricula getClaEstadoMatricula3()        Returns the current record's "ClaEstadoMatricula_3" value
 * @method SdatSieCurso       getSdatSieCurso()               Returns the current record's "SdatSieCurso" value
 * @method SdatSieCurso       getSdatSieCurso5()              Returns the current record's "SdatSieCurso_5" value
 * @method SdatSieCurso       getSdatSieCurso6()              Returns the current record's "SdatSieCurso_6" value
 * @method SdatSieCurso       getSdatSieCurso7()              Returns the current record's "SdatSieCurso_7" value
 * @method SdatSieCurso       getSdatSieCurso8()              Returns the current record's "SdatSieCurso_8" value
 * @method SdatSieCurso       getSdatSieCurso9()              Returns the current record's "SdatSieCurso_9" value
 * @method SdatSieCurso       getSdatSieCurso10()             Returns the current record's "SdatSieCurso_10" value
 * @method SdatSieCurso       getSdatSieCurso11()             Returns the current record's "SdatSieCurso_11" value
 * @method SdatRdeInscripcion setInscripcionId()              Sets the current record's "inscripcion_id" value
 * @method SdatRdeInscripcion setGestionId()                  Sets the current record's "gestion_id" value
 * @method SdatRdeInscripcion setCodigoRudeId()               Sets the current record's "codigo_rude_id" value
 * @method SdatRdeInscripcion setNumMatricula()               Sets the current record's "num_matricula" value
 * @method SdatRdeInscripcion setCodUeId()                    Sets the current record's "cod_ue_id" value
 * @method SdatRdeInscripcion setPeriodoId()                  Sets the current record's "periodo_id" value
 * @method SdatRdeInscripcion setSubCeaId()                   Sets the current record's "sub_cea_id" value
 * @method SdatRdeInscripcion setGradoId()                    Sets the current record's "grado_id" value
 * @method SdatRdeInscripcion setCicloId()                    Sets the current record's "ciclo_id" value
 * @method SdatRdeInscripcion setNivelId()                    Sets the current record's "nivel_id" value
 * @method SdatRdeInscripcion setParalelo()                   Sets the current record's "paralelo" value
 * @method SdatRdeInscripcion setTurnoId()                    Sets the current record's "turno_id" value
 * @method SdatRdeInscripcion setEstadoMatriculaInicioId()    Sets the current record's "estado_matricula_inicio_id" value
 * @method SdatRdeInscripcion setEstadoMatriculaFinId()       Sets the current record's "estado_matricula_fin_id" value
 * @method SdatRdeInscripcion setCodUeProcedenciaId()         Sets the current record's "cod_ue_procedencia_id" value
 * @method SdatRdeInscripcion setObservacionId()              Sets the current record's "observacion_id" value
 * @method SdatRdeInscripcion setObservacion()                Sets the current record's "observacion" value
 * @method SdatRdeInscripcion setFechaInscripcion()           Sets the current record's "fecha_inscripcion" value
 * @method SdatRdeInscripcion setApreciacionId()              Sets the current record's "apreciacion_id" value
 * @method SdatRdeInscripcion setDatRdeEstudiante()           Sets the current record's "DatRdeEstudiante" value
 * @method SdatRdeInscripcion setClaEstadoMatricula()         Sets the current record's "ClaEstadoMatricula" value
 * @method SdatRdeInscripcion setClaEstadoMatricula3()        Sets the current record's "ClaEstadoMatricula_3" value
 * @method SdatRdeInscripcion setSdatSieCurso()               Sets the current record's "SdatSieCurso" value
 * @method SdatRdeInscripcion setSdatSieCurso5()              Sets the current record's "SdatSieCurso_5" value
 * @method SdatRdeInscripcion setSdatSieCurso6()              Sets the current record's "SdatSieCurso_6" value
 * @method SdatRdeInscripcion setSdatSieCurso7()              Sets the current record's "SdatSieCurso_7" value
 * @method SdatRdeInscripcion setSdatSieCurso8()              Sets the current record's "SdatSieCurso_8" value
 * @method SdatRdeInscripcion setSdatSieCurso9()              Sets the current record's "SdatSieCurso_9" value
 * @method SdatRdeInscripcion setSdatSieCurso10()             Sets the current record's "SdatSieCurso_10" value
 * @method SdatRdeInscripcion setSdatSieCurso11()             Sets the current record's "SdatSieCurso_11" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSdatRdeInscripcion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sdat_rde_inscripcion');
        $this->hasColumn('inscripcion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('codigo_rude_id', 'string', 18, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '18',
             ));
        $this->hasColumn('num_matricula', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('periodo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('sub_cea_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('grado_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('ciclo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('nivel_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('paralelo', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('turno_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('estado_matricula_inicio_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('estado_matricula_fin_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('cod_ue_procedencia_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('observacion_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('observacion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('fecha_inscripcion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('apreciacion_id', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DatRdeEstudiante', array(
             'local' => 'codigo_rude_id',
             'foreign' => 'codigo_rude'));

        $this->hasOne('ClaEstadoMatricula', array(
             'local' => 'estado_matricula_fin_id',
             'foreign' => 'id_estado_matricula'));

        $this->hasOne('ClaEstadoMatricula as ClaEstadoMatricula_3', array(
             'local' => 'estado_matricula_inicio_id',
             'foreign' => 'id_estado_matricula'));

        $this->hasOne('SdatSieCurso', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue_id'));

        $this->hasOne('SdatSieCurso as SdatSieCurso_5', array(
             'local' => 'periodo_id',
             'foreign' => 'periodo_id'));

        $this->hasOne('SdatSieCurso as SdatSieCurso_6', array(
             'local' => 'sub_cea_id',
             'foreign' => 'sub_cea_id'));

        $this->hasOne('SdatSieCurso as SdatSieCurso_7', array(
             'local' => 'grado_id',
             'foreign' => 'grado_id'));

        $this->hasOne('SdatSieCurso as SdatSieCurso_8', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasOne('SdatSieCurso as SdatSieCurso_9', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasOne('SdatSieCurso as SdatSieCurso_10', array(
             'local' => 'paralelo',
             'foreign' => 'paralelo'));

        $this->hasOne('SdatSieCurso as SdatSieCurso_11', array(
             'local' => 'turno_id',
             'foreign' => 'turno_id'));
    }
}