<?php

/**
 * TmpDiplomasImpresos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class TmpDiplomasImpresos extends BaseTmpDiplomasImpresos
{

}