<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/12 23:23:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sieweb',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
