<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/03/07 14:05:48
sfConfig::add(array(
  'mod_cea_crear_cursos_enabled' => true,
  'mod_cea_crear_cursos_view_class' => 'sfPHP',
));
