<?php

/**
 * Notas form base class.
 *
 * @method Notas getObject() Returns the current form's model object
 *
 * @package    alternativa
 * @subpackage form
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 24171 2009-11-19 16:37:50Z Kris.Wallsmith $
 */
abstract class BaseNotasForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id'                         => new sfWidgetFormInputHidden(),
      'id_inscripcion'             => new sfWidgetFormInputText(),
      'gestion_id'                 => new sfWidgetFormInputText(),
      'cod_distrito'               => new sfWidgetFormInputText(),
      'distrito'                   => new sfWidgetFormInputText(),
      'cod_ue'                     => new sfWidgetFormInputText(),
      'desc_ue'                    => new sfWidgetFormInputText(),
      'codigo_rude'                => new sfWidgetFormInputText(),
      'carnet_identidad'           => new sfWidgetFormInputText(),
      'paterno'                    => new sfWidgetFormInputText(),
      'materno'                    => new sfWidgetFormInputText(),
      'nombre'                     => new sfWidgetFormInputText(),
      'fecha_nacimiento'           => new sfWidgetFormDate(),
      'genero'                     => new sfWidgetFormInputText(),
      'nivel_id'                   => new sfWidgetFormInputText(),
      'desc_nivel'                 => new sfWidgetFormInputText(),
      'id_grado'                   => new sfWidgetFormInputText(),
      'desc_grado'                 => new sfWidgetFormInputText(),
      'paralelo'                   => new sfWidgetFormInputText(),
      'desc_abrv'                  => new sfWidgetFormInputText(),
      'estado_matricula_inicio_id' => new sfWidgetFormInputText(),
      'matricula_inicio'           => new sfWidgetFormInputText(),
      'matricula_fin'              => new sfWidgetFormInputText(),
      'desc_estado_matricula'      => new sfWidgetFormInputText(),
      'cod_org_curr'               => new sfWidgetFormInputText(),
      'desc_modalidad'             => new sfWidgetFormInputText(),
      'cod_dependencia'            => new sfWidgetFormInputText(),
      'desc_dependencia'           => new sfWidgetFormInputText(),
      'm101'                       => new sfWidgetFormInputText(),
      'pt101'                      => new sfWidgetFormInputText(),
      'st101'                      => new sfWidgetFormInputText(),
      'tt101'                      => new sfWidgetFormInputText(),
      'pa101'                      => new sfWidgetFormInputText(),
      're101'                      => new sfWidgetFormInputText(),
      'pf101'                      => new sfWidgetFormInputText(),
      'm102'                       => new sfWidgetFormInputText(),
      'pt102'                      => new sfWidgetFormInputText(),
      'st102'                      => new sfWidgetFormInputText(),
      'tt102'                      => new sfWidgetFormInputText(),
      'pa102'                      => new sfWidgetFormInputText(),
      're102'                      => new sfWidgetFormInputText(),
      'pf102'                      => new sfWidgetFormInputText(),
      'm103'                       => new sfWidgetFormInputText(),
      'pt103'                      => new sfWidgetFormInputText(),
      'st103'                      => new sfWidgetFormInputText(),
      'tt103'                      => new sfWidgetFormInputText(),
      'pa103'                      => new sfWidgetFormInputText(),
      're103'                      => new sfWidgetFormInputText(),
      'pf103'                      => new sfWidgetFormInputText(),
      'm104'                       => new sfWidgetFormInputText(),
      'pt104'                      => new sfWidgetFormInputText(),
      'st104'                      => new sfWidgetFormInputText(),
      'tt104'                      => new sfWidgetFormInputText(),
      'pa104'                      => new sfWidgetFormInputText(),
      're104'                      => new sfWidgetFormInputText(),
      'pf104'                      => new sfWidgetFormInputText(),
      'm105'                       => new sfWidgetFormInputText(),
      'pt105'                      => new sfWidgetFormInputText(),
      'st105'                      => new sfWidgetFormInputText(),
      'tt105'                      => new sfWidgetFormInputText(),
      'pa105'                      => new sfWidgetFormInputText(),
      're105'                      => new sfWidgetFormInputText(),
      'pf105'                      => new sfWidgetFormInputText(),
      'm106'                       => new sfWidgetFormInputText(),
      'pt106'                      => new sfWidgetFormInputText(),
      'st106'                      => new sfWidgetFormInputText(),
      'tt106'                      => new sfWidgetFormInputText(),
      'pa106'                      => new sfWidgetFormInputText(),
      're106'                      => new sfWidgetFormInputText(),
      'pf106'                      => new sfWidgetFormInputText(),
      'm107'                       => new sfWidgetFormInputText(),
      'pt107'                      => new sfWidgetFormInputText(),
      'st107'                      => new sfWidgetFormInputText(),
      'tt107'                      => new sfWidgetFormInputText(),
      'pa107'                      => new sfWidgetFormInputText(),
      're107'                      => new sfWidgetFormInputText(),
      'pf107'                      => new sfWidgetFormInputText(),
      'm201'                       => new sfWidgetFormInputText(),
      'pt201'                      => new sfWidgetFormInputText(),
      'st201'                      => new sfWidgetFormInputText(),
      'tt201'                      => new sfWidgetFormInputText(),
      'pa201'                      => new sfWidgetFormInputText(),
      're201'                      => new sfWidgetFormInputText(),
      'pf201'                      => new sfWidgetFormInputText(),
      'm202'                       => new sfWidgetFormInputText(),
      'pt202'                      => new sfWidgetFormInputText(),
      'st202'                      => new sfWidgetFormInputText(),
      'tt202'                      => new sfWidgetFormInputText(),
      'pa202'                      => new sfWidgetFormInputText(),
      're202'                      => new sfWidgetFormInputText(),
      'pf202'                      => new sfWidgetFormInputText(),
      'm203'                       => new sfWidgetFormInputText(),
      'pt203'                      => new sfWidgetFormInputText(),
      'st203'                      => new sfWidgetFormInputText(),
      'tt203'                      => new sfWidgetFormInputText(),
      'pa203'                      => new sfWidgetFormInputText(),
      're203'                      => new sfWidgetFormInputText(),
      'pf203'                      => new sfWidgetFormInputText(),
      'm204'                       => new sfWidgetFormInputText(),
      'pt204'                      => new sfWidgetFormInputText(),
      'st204'                      => new sfWidgetFormInputText(),
      'tt204'                      => new sfWidgetFormInputText(),
      'pa204'                      => new sfWidgetFormInputText(),
      're204'                      => new sfWidgetFormInputText(),
      'pf204'                      => new sfWidgetFormInputText(),
      'm205'                       => new sfWidgetFormInputText(),
      'pt205'                      => new sfWidgetFormInputText(),
      'st205'                      => new sfWidgetFormInputText(),
      'tt205'                      => new sfWidgetFormInputText(),
      'pa205'                      => new sfWidgetFormInputText(),
      're205'                      => new sfWidgetFormInputText(),
      'pf205'                      => new sfWidgetFormInputText(),
      'm206'                       => new sfWidgetFormInputText(),
      'pt206'                      => new sfWidgetFormInputText(),
      'st206'                      => new sfWidgetFormInputText(),
      'tt206'                      => new sfWidgetFormInputText(),
      'pa206'                      => new sfWidgetFormInputText(),
      're206'                      => new sfWidgetFormInputText(),
      'pf206'                      => new sfWidgetFormInputText(),
      'm207'                       => new sfWidgetFormInputText(),
      'pt207'                      => new sfWidgetFormInputText(),
      'st207'                      => new sfWidgetFormInputText(),
      'tt207'                      => new sfWidgetFormInputText(),
      'pa207'                      => new sfWidgetFormInputText(),
      're207'                      => new sfWidgetFormInputText(),
      'pf207'                      => new sfWidgetFormInputText(),
      'm208'                       => new sfWidgetFormInputText(),
      'pt208'                      => new sfWidgetFormInputText(),
      'st208'                      => new sfWidgetFormInputText(),
      'tt208'                      => new sfWidgetFormInputText(),
      'pa208'                      => new sfWidgetFormInputText(),
      're208'                      => new sfWidgetFormInputText(),
      'pf208'                      => new sfWidgetFormInputText(),
      'm209'                       => new sfWidgetFormInputText(),
      'pt209'                      => new sfWidgetFormInputText(),
      'st209'                      => new sfWidgetFormInputText(),
      'tt209'                      => new sfWidgetFormInputText(),
      'pa209'                      => new sfWidgetFormInputText(),
      're209'                      => new sfWidgetFormInputText(),
      'pf209'                      => new sfWidgetFormInputText(),
      'm210'                       => new sfWidgetFormInputText(),
      'pt210'                      => new sfWidgetFormInputText(),
      'st210'                      => new sfWidgetFormInputText(),
      'tt210'                      => new sfWidgetFormInputText(),
      'pa210'                      => new sfWidgetFormInputText(),
      're210'                      => new sfWidgetFormInputText(),
      'pf210'                      => new sfWidgetFormInputText(),
      'm211'                       => new sfWidgetFormInputText(),
      'pt211'                      => new sfWidgetFormInputText(),
      'st211'                      => new sfWidgetFormInputText(),
      'tt211'                      => new sfWidgetFormInputText(),
      'pa211'                      => new sfWidgetFormInputText(),
      're211'                      => new sfWidgetFormInputText(),
      'pf211'                      => new sfWidgetFormInputText(),
      'm212'                       => new sfWidgetFormInputText(),
      'pt212'                      => new sfWidgetFormInputText(),
      'st212'                      => new sfWidgetFormInputText(),
      'tt212'                      => new sfWidgetFormInputText(),
      'pa212'                      => new sfWidgetFormInputText(),
      're212'                      => new sfWidgetFormInputText(),
      'pf212'                      => new sfWidgetFormInputText(),
      'm213'                       => new sfWidgetFormInputText(),
      'pt213'                      => new sfWidgetFormInputText(),
      'st213'                      => new sfWidgetFormInputText(),
      'tt213'                      => new sfWidgetFormInputText(),
      'pa213'                      => new sfWidgetFormInputText(),
      're213'                      => new sfWidgetFormInputText(),
      'pf213'                      => new sfWidgetFormInputText(),
      'm221'                       => new sfWidgetFormInputText(),
      'pt221'                      => new sfWidgetFormInputText(),
      'st221'                      => new sfWidgetFormInputText(),
      'tt221'                      => new sfWidgetFormInputText(),
      'pa221'                      => new sfWidgetFormInputText(),
      're221'                      => new sfWidgetFormInputText(),
      'pf221'                      => new sfWidgetFormInputText(),
      'm222'                       => new sfWidgetFormInputText(),
      'pt222'                      => new sfWidgetFormInputText(),
      'st222'                      => new sfWidgetFormInputText(),
      'tt222'                      => new sfWidgetFormInputText(),
      'pa222'                      => new sfWidgetFormInputText(),
      're222'                      => new sfWidgetFormInputText(),
      'pf222'                      => new sfWidgetFormInputText(),
      'm301'                       => new sfWidgetFormInputText(),
      'pt301'                      => new sfWidgetFormInputText(),
      'st301'                      => new sfWidgetFormInputText(),
      'tt301'                      => new sfWidgetFormInputText(),
      'pa301'                      => new sfWidgetFormInputText(),
      're301'                      => new sfWidgetFormInputText(),
      'pf301'                      => new sfWidgetFormInputText(),
      'm302'                       => new sfWidgetFormInputText(),
      'pt302'                      => new sfWidgetFormInputText(),
      'st302'                      => new sfWidgetFormInputText(),
      'tt302'                      => new sfWidgetFormInputText(),
      'pa302'                      => new sfWidgetFormInputText(),
      're302'                      => new sfWidgetFormInputText(),
      'pf302'                      => new sfWidgetFormInputText(),
      'm303'                       => new sfWidgetFormInputText(),
      'pt303'                      => new sfWidgetFormInputText(),
      'st303'                      => new sfWidgetFormInputText(),
      'tt303'                      => new sfWidgetFormInputText(),
      'pa303'                      => new sfWidgetFormInputText(),
      're303'                      => new sfWidgetFormInputText(),
      'pf303'                      => new sfWidgetFormInputText(),
      'm304'                       => new sfWidgetFormInputText(),
      'pt304'                      => new sfWidgetFormInputText(),
      'st304'                      => new sfWidgetFormInputText(),
      'tt304'                      => new sfWidgetFormInputText(),
      'pa304'                      => new sfWidgetFormInputText(),
      're304'                      => new sfWidgetFormInputText(),
      'pf304'                      => new sfWidgetFormInputText(),
      'm305'                       => new sfWidgetFormInputText(),
      'pt305'                      => new sfWidgetFormInputText(),
      'st305'                      => new sfWidgetFormInputText(),
      'tt305'                      => new sfWidgetFormInputText(),
      'pa305'                      => new sfWidgetFormInputText(),
      're305'                      => new sfWidgetFormInputText(),
      'pf305'                      => new sfWidgetFormInputText(),
      'm306'                       => new sfWidgetFormInputText(),
      'pt306'                      => new sfWidgetFormInputText(),
      'st306'                      => new sfWidgetFormInputText(),
      'tt306'                      => new sfWidgetFormInputText(),
      'pa306'                      => new sfWidgetFormInputText(),
      're306'                      => new sfWidgetFormInputText(),
      'pf306'                      => new sfWidgetFormInputText(),
      'm307'                       => new sfWidgetFormInputText(),
      'pt307'                      => new sfWidgetFormInputText(),
      'st307'                      => new sfWidgetFormInputText(),
      'tt307'                      => new sfWidgetFormInputText(),
      'pa307'                      => new sfWidgetFormInputText(),
      're307'                      => new sfWidgetFormInputText(),
      'pf307'                      => new sfWidgetFormInputText(),
      'm308'                       => new sfWidgetFormInputText(),
      'pt308'                      => new sfWidgetFormInputText(),
      'st308'                      => new sfWidgetFormInputText(),
      'tt308'                      => new sfWidgetFormInputText(),
      'pa308'                      => new sfWidgetFormInputText(),
      're308'                      => new sfWidgetFormInputText(),
      'pf308'                      => new sfWidgetFormInputText(),
      'm309'                       => new sfWidgetFormInputText(),
      'pt309'                      => new sfWidgetFormInputText(),
      'st309'                      => new sfWidgetFormInputText(),
      'tt309'                      => new sfWidgetFormInputText(),
      'pa309'                      => new sfWidgetFormInputText(),
      're309'                      => new sfWidgetFormInputText(),
      'pf309'                      => new sfWidgetFormInputText(),
      'm310'                       => new sfWidgetFormInputText(),
      'pt310'                      => new sfWidgetFormInputText(),
      'st310'                      => new sfWidgetFormInputText(),
      'tt310'                      => new sfWidgetFormInputText(),
      'pa310'                      => new sfWidgetFormInputText(),
      're310'                      => new sfWidgetFormInputText(),
      'pf310'                      => new sfWidgetFormInputText(),
      'm311'                       => new sfWidgetFormInputText(),
      'pt311'                      => new sfWidgetFormInputText(),
      'st311'                      => new sfWidgetFormInputText(),
      'tt311'                      => new sfWidgetFormInputText(),
      'pa311'                      => new sfWidgetFormInputText(),
      're311'                      => new sfWidgetFormInputText(),
      'pf311'                      => new sfWidgetFormInputText(),
      'm312'                       => new sfWidgetFormInputText(),
      'pt312'                      => new sfWidgetFormInputText(),
      'st312'                      => new sfWidgetFormInputText(),
      'tt312'                      => new sfWidgetFormInputText(),
      'pa312'                      => new sfWidgetFormInputText(),
      're312'                      => new sfWidgetFormInputText(),
      'pf312'                      => new sfWidgetFormInputText(),
      'm313'                       => new sfWidgetFormInputText(),
      'pt313'                      => new sfWidgetFormInputText(),
      'st313'                      => new sfWidgetFormInputText(),
      'tt313'                      => new sfWidgetFormInputText(),
      'pa313'                      => new sfWidgetFormInputText(),
      're313'                      => new sfWidgetFormInputText(),
      'pf313'                      => new sfWidgetFormInputText(),
      'm314'                       => new sfWidgetFormInputText(),
      'pt314'                      => new sfWidgetFormInputText(),
      'st314'                      => new sfWidgetFormInputText(),
      'tt314'                      => new sfWidgetFormInputText(),
      'pa314'                      => new sfWidgetFormInputText(),
      're314'                      => new sfWidgetFormInputText(),
      'pf314'                      => new sfWidgetFormInputText(),
      'm315'                       => new sfWidgetFormInputText(),
      'pt315'                      => new sfWidgetFormInputText(),
      'st315'                      => new sfWidgetFormInputText(),
      'tt315'                      => new sfWidgetFormInputText(),
      'pa315'                      => new sfWidgetFormInputText(),
      're315'                      => new sfWidgetFormInputText(),
      'pf315'                      => new sfWidgetFormInputText(),
      'm316'                       => new sfWidgetFormInputText(),
      'pt316'                      => new sfWidgetFormInputText(),
      'st316'                      => new sfWidgetFormInputText(),
      'tt316'                      => new sfWidgetFormInputText(),
      'pa316'                      => new sfWidgetFormInputText(),
      're316'                      => new sfWidgetFormInputText(),
      'pf316'                      => new sfWidgetFormInputText(),
      'm317'                       => new sfWidgetFormInputText(),
      'pt317'                      => new sfWidgetFormInputText(),
      'st317'                      => new sfWidgetFormInputText(),
      'tt317'                      => new sfWidgetFormInputText(),
      'pa317'                      => new sfWidgetFormInputText(),
      're317'                      => new sfWidgetFormInputText(),
      'pf317'                      => new sfWidgetFormInputText(),
      'm318'                       => new sfWidgetFormInputText(),
      'pt318'                      => new sfWidgetFormInputText(),
      'st318'                      => new sfWidgetFormInputText(),
      'tt318'                      => new sfWidgetFormInputText(),
      'pa318'                      => new sfWidgetFormInputText(),
      're318'                      => new sfWidgetFormInputText(),
      'pf318'                      => new sfWidgetFormInputText(),
      'm319'                       => new sfWidgetFormInputText(),
      'pt319'                      => new sfWidgetFormInputText(),
      'st319'                      => new sfWidgetFormInputText(),
      'tt319'                      => new sfWidgetFormInputText(),
      'pa319'                      => new sfWidgetFormInputText(),
      're319'                      => new sfWidgetFormInputText(),
      'pf319'                      => new sfWidgetFormInputText(),
      'm320'                       => new sfWidgetFormInputText(),
      'pt320'                      => new sfWidgetFormInputText(),
      'st320'                      => new sfWidgetFormInputText(),
      'tt320'                      => new sfWidgetFormInputText(),
      'pa320'                      => new sfWidgetFormInputText(),
      're320'                      => new sfWidgetFormInputText(),
      'pf320'                      => new sfWidgetFormInputText(),
      'm321'                       => new sfWidgetFormInputText(),
      'pt321'                      => new sfWidgetFormInputText(),
      'st321'                      => new sfWidgetFormInputText(),
      'tt321'                      => new sfWidgetFormInputText(),
      'pa321'                      => new sfWidgetFormInputText(),
      're321'                      => new sfWidgetFormInputText(),
      'pf321'                      => new sfWidgetFormInputText(),
    ));

    $this->setValidators(array(
      'id'                         => new sfValidatorDoctrineChoice(array('model' => $this->getModelName(), 'column' => 'id', 'required' => false)),
      'id_inscripcion'             => new sfValidatorInteger(),
      'gestion_id'                 => new sfValidatorInteger(),
      'cod_distrito'               => new sfValidatorInteger(),
      'distrito'                   => new sfValidatorString(array('max_length' => 45)),
      'cod_ue'                     => new sfValidatorString(array('max_length' => 8)),
      'desc_ue'                    => new sfValidatorString(array('max_length' => 70)),
      'codigo_rude'                => new sfValidatorString(array('max_length' => 18)),
      'carnet_identidad'           => new sfValidatorString(array('max_length' => 12, 'required' => false)),
      'paterno'                    => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'materno'                    => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'nombre'                     => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'fecha_nacimiento'           => new sfValidatorDate(array('required' => false)),
      'genero'                     => new sfValidatorString(array('max_length' => 1)),
      'nivel_id'                   => new sfValidatorInteger(),
      'desc_nivel'                 => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'id_grado'                   => new sfValidatorInteger(),
      'desc_grado'                 => new sfValidatorString(array('max_length' => 45)),
      'paralelo'                   => new sfValidatorString(array('max_length' => 2)),
      'desc_abrv'                  => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'estado_matricula_inicio_id' => new sfValidatorInteger(),
      'matricula_inicio'           => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'matricula_fin'              => new sfValidatorInteger(),
      'desc_estado_matricula'      => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'cod_org_curr'               => new sfValidatorInteger(),
      'desc_modalidad'             => new sfValidatorString(array('max_length' => 45)),
      'cod_dependencia'            => new sfValidatorInteger(),
      'desc_dependencia'           => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'm101'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt101'                      => new sfValidatorInteger(array('required' => false)),
      'st101'                      => new sfValidatorInteger(array('required' => false)),
      'tt101'                      => new sfValidatorInteger(array('required' => false)),
      'pa101'                      => new sfValidatorInteger(array('required' => false)),
      're101'                      => new sfValidatorInteger(array('required' => false)),
      'pf101'                      => new sfValidatorInteger(array('required' => false)),
      'm102'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt102'                      => new sfValidatorInteger(array('required' => false)),
      'st102'                      => new sfValidatorInteger(array('required' => false)),
      'tt102'                      => new sfValidatorInteger(array('required' => false)),
      'pa102'                      => new sfValidatorInteger(array('required' => false)),
      're102'                      => new sfValidatorInteger(array('required' => false)),
      'pf102'                      => new sfValidatorInteger(array('required' => false)),
      'm103'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt103'                      => new sfValidatorInteger(array('required' => false)),
      'st103'                      => new sfValidatorInteger(array('required' => false)),
      'tt103'                      => new sfValidatorInteger(array('required' => false)),
      'pa103'                      => new sfValidatorInteger(array('required' => false)),
      're103'                      => new sfValidatorInteger(array('required' => false)),
      'pf103'                      => new sfValidatorInteger(array('required' => false)),
      'm104'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt104'                      => new sfValidatorInteger(array('required' => false)),
      'st104'                      => new sfValidatorInteger(array('required' => false)),
      'tt104'                      => new sfValidatorInteger(array('required' => false)),
      'pa104'                      => new sfValidatorInteger(array('required' => false)),
      're104'                      => new sfValidatorInteger(array('required' => false)),
      'pf104'                      => new sfValidatorInteger(array('required' => false)),
      'm105'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt105'                      => new sfValidatorInteger(array('required' => false)),
      'st105'                      => new sfValidatorInteger(array('required' => false)),
      'tt105'                      => new sfValidatorInteger(array('required' => false)),
      'pa105'                      => new sfValidatorInteger(array('required' => false)),
      're105'                      => new sfValidatorInteger(array('required' => false)),
      'pf105'                      => new sfValidatorInteger(array('required' => false)),
      'm106'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt106'                      => new sfValidatorInteger(array('required' => false)),
      'st106'                      => new sfValidatorInteger(array('required' => false)),
      'tt106'                      => new sfValidatorInteger(array('required' => false)),
      'pa106'                      => new sfValidatorInteger(array('required' => false)),
      're106'                      => new sfValidatorInteger(array('required' => false)),
      'pf106'                      => new sfValidatorInteger(array('required' => false)),
      'm107'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt107'                      => new sfValidatorInteger(array('required' => false)),
      'st107'                      => new sfValidatorInteger(array('required' => false)),
      'tt107'                      => new sfValidatorInteger(array('required' => false)),
      'pa107'                      => new sfValidatorInteger(array('required' => false)),
      're107'                      => new sfValidatorInteger(array('required' => false)),
      'pf107'                      => new sfValidatorInteger(array('required' => false)),
      'm201'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt201'                      => new sfValidatorInteger(array('required' => false)),
      'st201'                      => new sfValidatorInteger(array('required' => false)),
      'tt201'                      => new sfValidatorInteger(array('required' => false)),
      'pa201'                      => new sfValidatorInteger(array('required' => false)),
      're201'                      => new sfValidatorInteger(array('required' => false)),
      'pf201'                      => new sfValidatorInteger(array('required' => false)),
      'm202'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt202'                      => new sfValidatorInteger(array('required' => false)),
      'st202'                      => new sfValidatorInteger(array('required' => false)),
      'tt202'                      => new sfValidatorInteger(array('required' => false)),
      'pa202'                      => new sfValidatorInteger(array('required' => false)),
      're202'                      => new sfValidatorInteger(array('required' => false)),
      'pf202'                      => new sfValidatorInteger(array('required' => false)),
      'm203'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt203'                      => new sfValidatorInteger(array('required' => false)),
      'st203'                      => new sfValidatorInteger(array('required' => false)),
      'tt203'                      => new sfValidatorInteger(array('required' => false)),
      'pa203'                      => new sfValidatorInteger(array('required' => false)),
      're203'                      => new sfValidatorInteger(array('required' => false)),
      'pf203'                      => new sfValidatorInteger(array('required' => false)),
      'm204'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt204'                      => new sfValidatorInteger(array('required' => false)),
      'st204'                      => new sfValidatorInteger(array('required' => false)),
      'tt204'                      => new sfValidatorInteger(array('required' => false)),
      'pa204'                      => new sfValidatorInteger(array('required' => false)),
      're204'                      => new sfValidatorInteger(array('required' => false)),
      'pf204'                      => new sfValidatorInteger(array('required' => false)),
      'm205'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt205'                      => new sfValidatorInteger(array('required' => false)),
      'st205'                      => new sfValidatorInteger(array('required' => false)),
      'tt205'                      => new sfValidatorInteger(array('required' => false)),
      'pa205'                      => new sfValidatorInteger(array('required' => false)),
      're205'                      => new sfValidatorInteger(array('required' => false)),
      'pf205'                      => new sfValidatorInteger(array('required' => false)),
      'm206'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt206'                      => new sfValidatorInteger(array('required' => false)),
      'st206'                      => new sfValidatorInteger(array('required' => false)),
      'tt206'                      => new sfValidatorInteger(array('required' => false)),
      'pa206'                      => new sfValidatorInteger(array('required' => false)),
      're206'                      => new sfValidatorInteger(array('required' => false)),
      'pf206'                      => new sfValidatorInteger(array('required' => false)),
      'm207'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt207'                      => new sfValidatorInteger(array('required' => false)),
      'st207'                      => new sfValidatorInteger(array('required' => false)),
      'tt207'                      => new sfValidatorInteger(array('required' => false)),
      'pa207'                      => new sfValidatorInteger(array('required' => false)),
      're207'                      => new sfValidatorInteger(array('required' => false)),
      'pf207'                      => new sfValidatorInteger(array('required' => false)),
      'm208'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt208'                      => new sfValidatorInteger(array('required' => false)),
      'st208'                      => new sfValidatorInteger(array('required' => false)),
      'tt208'                      => new sfValidatorInteger(array('required' => false)),
      'pa208'                      => new sfValidatorInteger(array('required' => false)),
      're208'                      => new sfValidatorInteger(array('required' => false)),
      'pf208'                      => new sfValidatorInteger(array('required' => false)),
      'm209'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt209'                      => new sfValidatorInteger(array('required' => false)),
      'st209'                      => new sfValidatorInteger(array('required' => false)),
      'tt209'                      => new sfValidatorInteger(array('required' => false)),
      'pa209'                      => new sfValidatorInteger(array('required' => false)),
      're209'                      => new sfValidatorInteger(array('required' => false)),
      'pf209'                      => new sfValidatorInteger(array('required' => false)),
      'm210'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt210'                      => new sfValidatorInteger(array('required' => false)),
      'st210'                      => new sfValidatorInteger(array('required' => false)),
      'tt210'                      => new sfValidatorInteger(array('required' => false)),
      'pa210'                      => new sfValidatorInteger(array('required' => false)),
      're210'                      => new sfValidatorInteger(array('required' => false)),
      'pf210'                      => new sfValidatorInteger(array('required' => false)),
      'm211'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt211'                      => new sfValidatorInteger(array('required' => false)),
      'st211'                      => new sfValidatorInteger(array('required' => false)),
      'tt211'                      => new sfValidatorInteger(array('required' => false)),
      'pa211'                      => new sfValidatorInteger(array('required' => false)),
      're211'                      => new sfValidatorInteger(array('required' => false)),
      'pf211'                      => new sfValidatorInteger(array('required' => false)),
      'm212'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt212'                      => new sfValidatorInteger(array('required' => false)),
      'st212'                      => new sfValidatorInteger(array('required' => false)),
      'tt212'                      => new sfValidatorInteger(array('required' => false)),
      'pa212'                      => new sfValidatorInteger(array('required' => false)),
      're212'                      => new sfValidatorInteger(array('required' => false)),
      'pf212'                      => new sfValidatorInteger(array('required' => false)),
      'm213'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt213'                      => new sfValidatorInteger(array('required' => false)),
      'st213'                      => new sfValidatorInteger(array('required' => false)),
      'tt213'                      => new sfValidatorInteger(array('required' => false)),
      'pa213'                      => new sfValidatorInteger(array('required' => false)),
      're213'                      => new sfValidatorInteger(array('required' => false)),
      'pf213'                      => new sfValidatorInteger(array('required' => false)),
      'm221'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt221'                      => new sfValidatorInteger(array('required' => false)),
      'st221'                      => new sfValidatorInteger(array('required' => false)),
      'tt221'                      => new sfValidatorInteger(array('required' => false)),
      'pa221'                      => new sfValidatorInteger(array('required' => false)),
      're221'                      => new sfValidatorInteger(array('required' => false)),
      'pf221'                      => new sfValidatorInteger(array('required' => false)),
      'm222'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt222'                      => new sfValidatorInteger(array('required' => false)),
      'st222'                      => new sfValidatorInteger(array('required' => false)),
      'tt222'                      => new sfValidatorInteger(array('required' => false)),
      'pa222'                      => new sfValidatorInteger(array('required' => false)),
      're222'                      => new sfValidatorInteger(array('required' => false)),
      'pf222'                      => new sfValidatorInteger(array('required' => false)),
      'm301'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt301'                      => new sfValidatorInteger(array('required' => false)),
      'st301'                      => new sfValidatorInteger(array('required' => false)),
      'tt301'                      => new sfValidatorInteger(array('required' => false)),
      'pa301'                      => new sfValidatorInteger(array('required' => false)),
      're301'                      => new sfValidatorInteger(array('required' => false)),
      'pf301'                      => new sfValidatorInteger(array('required' => false)),
      'm302'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt302'                      => new sfValidatorInteger(array('required' => false)),
      'st302'                      => new sfValidatorInteger(array('required' => false)),
      'tt302'                      => new sfValidatorInteger(array('required' => false)),
      'pa302'                      => new sfValidatorInteger(array('required' => false)),
      're302'                      => new sfValidatorInteger(array('required' => false)),
      'pf302'                      => new sfValidatorInteger(array('required' => false)),
      'm303'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt303'                      => new sfValidatorInteger(array('required' => false)),
      'st303'                      => new sfValidatorInteger(array('required' => false)),
      'tt303'                      => new sfValidatorInteger(array('required' => false)),
      'pa303'                      => new sfValidatorInteger(array('required' => false)),
      're303'                      => new sfValidatorInteger(array('required' => false)),
      'pf303'                      => new sfValidatorInteger(array('required' => false)),
      'm304'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt304'                      => new sfValidatorInteger(array('required' => false)),
      'st304'                      => new sfValidatorInteger(array('required' => false)),
      'tt304'                      => new sfValidatorInteger(array('required' => false)),
      'pa304'                      => new sfValidatorInteger(array('required' => false)),
      're304'                      => new sfValidatorInteger(array('required' => false)),
      'pf304'                      => new sfValidatorInteger(array('required' => false)),
      'm305'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt305'                      => new sfValidatorInteger(array('required' => false)),
      'st305'                      => new sfValidatorInteger(array('required' => false)),
      'tt305'                      => new sfValidatorInteger(array('required' => false)),
      'pa305'                      => new sfValidatorInteger(array('required' => false)),
      're305'                      => new sfValidatorInteger(array('required' => false)),
      'pf305'                      => new sfValidatorInteger(array('required' => false)),
      'm306'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt306'                      => new sfValidatorInteger(array('required' => false)),
      'st306'                      => new sfValidatorInteger(array('required' => false)),
      'tt306'                      => new sfValidatorInteger(array('required' => false)),
      'pa306'                      => new sfValidatorInteger(array('required' => false)),
      're306'                      => new sfValidatorInteger(array('required' => false)),
      'pf306'                      => new sfValidatorInteger(array('required' => false)),
      'm307'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt307'                      => new sfValidatorInteger(array('required' => false)),
      'st307'                      => new sfValidatorInteger(array('required' => false)),
      'tt307'                      => new sfValidatorInteger(array('required' => false)),
      'pa307'                      => new sfValidatorInteger(array('required' => false)),
      're307'                      => new sfValidatorInteger(array('required' => false)),
      'pf307'                      => new sfValidatorInteger(array('required' => false)),
      'm308'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt308'                      => new sfValidatorInteger(array('required' => false)),
      'st308'                      => new sfValidatorInteger(array('required' => false)),
      'tt308'                      => new sfValidatorInteger(array('required' => false)),
      'pa308'                      => new sfValidatorInteger(array('required' => false)),
      're308'                      => new sfValidatorInteger(array('required' => false)),
      'pf308'                      => new sfValidatorInteger(array('required' => false)),
      'm309'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt309'                      => new sfValidatorInteger(array('required' => false)),
      'st309'                      => new sfValidatorInteger(array('required' => false)),
      'tt309'                      => new sfValidatorInteger(array('required' => false)),
      'pa309'                      => new sfValidatorInteger(array('required' => false)),
      're309'                      => new sfValidatorInteger(array('required' => false)),
      'pf309'                      => new sfValidatorInteger(array('required' => false)),
      'm310'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt310'                      => new sfValidatorInteger(array('required' => false)),
      'st310'                      => new sfValidatorInteger(array('required' => false)),
      'tt310'                      => new sfValidatorInteger(array('required' => false)),
      'pa310'                      => new sfValidatorInteger(array('required' => false)),
      're310'                      => new sfValidatorInteger(array('required' => false)),
      'pf310'                      => new sfValidatorInteger(array('required' => false)),
      'm311'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt311'                      => new sfValidatorInteger(array('required' => false)),
      'st311'                      => new sfValidatorInteger(array('required' => false)),
      'tt311'                      => new sfValidatorInteger(array('required' => false)),
      'pa311'                      => new sfValidatorInteger(array('required' => false)),
      're311'                      => new sfValidatorInteger(array('required' => false)),
      'pf311'                      => new sfValidatorInteger(array('required' => false)),
      'm312'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt312'                      => new sfValidatorInteger(array('required' => false)),
      'st312'                      => new sfValidatorInteger(array('required' => false)),
      'tt312'                      => new sfValidatorInteger(array('required' => false)),
      'pa312'                      => new sfValidatorInteger(array('required' => false)),
      're312'                      => new sfValidatorInteger(array('required' => false)),
      'pf312'                      => new sfValidatorInteger(array('required' => false)),
      'm313'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt313'                      => new sfValidatorInteger(array('required' => false)),
      'st313'                      => new sfValidatorInteger(array('required' => false)),
      'tt313'                      => new sfValidatorInteger(array('required' => false)),
      'pa313'                      => new sfValidatorInteger(array('required' => false)),
      're313'                      => new sfValidatorInteger(array('required' => false)),
      'pf313'                      => new sfValidatorInteger(array('required' => false)),
      'm314'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt314'                      => new sfValidatorInteger(array('required' => false)),
      'st314'                      => new sfValidatorInteger(array('required' => false)),
      'tt314'                      => new sfValidatorInteger(array('required' => false)),
      'pa314'                      => new sfValidatorInteger(array('required' => false)),
      're314'                      => new sfValidatorInteger(array('required' => false)),
      'pf314'                      => new sfValidatorInteger(array('required' => false)),
      'm315'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt315'                      => new sfValidatorInteger(array('required' => false)),
      'st315'                      => new sfValidatorInteger(array('required' => false)),
      'tt315'                      => new sfValidatorInteger(array('required' => false)),
      'pa315'                      => new sfValidatorInteger(array('required' => false)),
      're315'                      => new sfValidatorInteger(array('required' => false)),
      'pf315'                      => new sfValidatorInteger(array('required' => false)),
      'm316'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt316'                      => new sfValidatorInteger(array('required' => false)),
      'st316'                      => new sfValidatorInteger(array('required' => false)),
      'tt316'                      => new sfValidatorInteger(array('required' => false)),
      'pa316'                      => new sfValidatorInteger(array('required' => false)),
      're316'                      => new sfValidatorInteger(array('required' => false)),
      'pf316'                      => new sfValidatorInteger(array('required' => false)),
      'm317'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt317'                      => new sfValidatorInteger(array('required' => false)),
      'st317'                      => new sfValidatorInteger(array('required' => false)),
      'tt317'                      => new sfValidatorInteger(array('required' => false)),
      'pa317'                      => new sfValidatorInteger(array('required' => false)),
      're317'                      => new sfValidatorInteger(array('required' => false)),
      'pf317'                      => new sfValidatorInteger(array('required' => false)),
      'm318'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt318'                      => new sfValidatorInteger(array('required' => false)),
      'st318'                      => new sfValidatorInteger(array('required' => false)),
      'tt318'                      => new sfValidatorInteger(array('required' => false)),
      'pa318'                      => new sfValidatorInteger(array('required' => false)),
      're318'                      => new sfValidatorInteger(array('required' => false)),
      'pf318'                      => new sfValidatorInteger(array('required' => false)),
      'm319'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt319'                      => new sfValidatorInteger(array('required' => false)),
      'st319'                      => new sfValidatorInteger(array('required' => false)),
      'tt319'                      => new sfValidatorInteger(array('required' => false)),
      'pa319'                      => new sfValidatorInteger(array('required' => false)),
      're319'                      => new sfValidatorInteger(array('required' => false)),
      'pf319'                      => new sfValidatorInteger(array('required' => false)),
      'm320'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt320'                      => new sfValidatorInteger(array('required' => false)),
      'st320'                      => new sfValidatorInteger(array('required' => false)),
      'tt320'                      => new sfValidatorInteger(array('required' => false)),
      'pa320'                      => new sfValidatorInteger(array('required' => false)),
      're320'                      => new sfValidatorInteger(array('required' => false)),
      'pf320'                      => new sfValidatorInteger(array('required' => false)),
      'm321'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'pt321'                      => new sfValidatorInteger(array('required' => false)),
      'st321'                      => new sfValidatorInteger(array('required' => false)),
      'tt321'                      => new sfValidatorInteger(array('required' => false)),
      'pa321'                      => new sfValidatorInteger(array('required' => false)),
      're321'                      => new sfValidatorInteger(array('required' => false)),
      'pf321'                      => new sfValidatorInteger(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('notas[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Notas';
  }

}
