<?php

/**
 * ClaCursoOferta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Ing. Ivan Callapa Quiroz
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ClaCursoOferta extends BaseClaCursoOferta
{
    public function __toString() {
        return $this->getIdCursoOferta().'-'.$this->getDescCursoOferta();
    }
}