<?php

/**
 * ReporteAlternativa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Ing. Ivan Callapa Quiroz
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ReporteAlternativa extends BaseReporteAlternativa
{

}