<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatSieOfertaCurricular', 'doctrine');

/**
 * BaseDatSieOfertaCurricular
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_oferta_curricular
 * @property integer $gestion_id
 * @property string $cod_ue_id
 * @property integer $cod_asignatura_id
 * @property integer $nivel_id
 * @property integer $ciclo_id
 * @property integer $grado_id
 * @property ClaGestion $ClaGestion
 * @property ClaGrado $ClaGrado
 * @property ClaGrado $ClaGrado_3
 * @property ClaGrado $ClaGrado_4
 * @property DatSlnEstudios $DatSlnEstudios
 * @property DatSlnEstudios $DatSlnEstudios_6
 * @property DatSlnEstudios $DatSlnEstudios_7
 * @property Doctrine_Collection $RelDocenteOfertacurricular
 * @property Doctrine_Collection $RelDocenteOfertacurricular_2
 * 
 * @method integer                getIdOfertaCurricular()           Returns the current record's "id_oferta_curricular" value
 * @method integer                getGestionId()                    Returns the current record's "gestion_id" value
 * @method string                 getCodUeId()                      Returns the current record's "cod_ue_id" value
 * @method integer                getCodAsignaturaId()              Returns the current record's "cod_asignatura_id" value
 * @method integer                getNivelId()                      Returns the current record's "nivel_id" value
 * @method integer                getCicloId()                      Returns the current record's "ciclo_id" value
 * @method integer                getGradoId()                      Returns the current record's "grado_id" value
 * @method ClaGestion             getClaGestion()                   Returns the current record's "ClaGestion" value
 * @method ClaGrado               getClaGrado()                     Returns the current record's "ClaGrado" value
 * @method ClaGrado               getClaGrado3()                    Returns the current record's "ClaGrado_3" value
 * @method ClaGrado               getClaGrado4()                    Returns the current record's "ClaGrado_4" value
 * @method DatSlnEstudios         getDatSlnEstudios()               Returns the current record's "DatSlnEstudios" value
 * @method DatSlnEstudios         getDatSlnEstudios6()              Returns the current record's "DatSlnEstudios_6" value
 * @method DatSlnEstudios         getDatSlnEstudios7()              Returns the current record's "DatSlnEstudios_7" value
 * @method Doctrine_Collection    getRelDocenteOfertacurricular()   Returns the current record's "RelDocenteOfertacurricular" collection
 * @method Doctrine_Collection    getRelDocenteOfertacurricular2()  Returns the current record's "RelDocenteOfertacurricular_2" collection
 * @method DatSieOfertaCurricular setIdOfertaCurricular()           Sets the current record's "id_oferta_curricular" value
 * @method DatSieOfertaCurricular setGestionId()                    Sets the current record's "gestion_id" value
 * @method DatSieOfertaCurricular setCodUeId()                      Sets the current record's "cod_ue_id" value
 * @method DatSieOfertaCurricular setCodAsignaturaId()              Sets the current record's "cod_asignatura_id" value
 * @method DatSieOfertaCurricular setNivelId()                      Sets the current record's "nivel_id" value
 * @method DatSieOfertaCurricular setCicloId()                      Sets the current record's "ciclo_id" value
 * @method DatSieOfertaCurricular setGradoId()                      Sets the current record's "grado_id" value
 * @method DatSieOfertaCurricular setClaGestion()                   Sets the current record's "ClaGestion" value
 * @method DatSieOfertaCurricular setClaGrado()                     Sets the current record's "ClaGrado" value
 * @method DatSieOfertaCurricular setClaGrado3()                    Sets the current record's "ClaGrado_3" value
 * @method DatSieOfertaCurricular setClaGrado4()                    Sets the current record's "ClaGrado_4" value
 * @method DatSieOfertaCurricular setDatSlnEstudios()               Sets the current record's "DatSlnEstudios" value
 * @method DatSieOfertaCurricular setDatSlnEstudios6()              Sets the current record's "DatSlnEstudios_6" value
 * @method DatSieOfertaCurricular setDatSlnEstudios7()              Sets the current record's "DatSlnEstudios_7" value
 * @method DatSieOfertaCurricular setRelDocenteOfertacurricular()   Sets the current record's "RelDocenteOfertacurricular" collection
 * @method DatSieOfertaCurricular setRelDocenteOfertacurricular2()  Sets the current record's "RelDocenteOfertacurricular_2" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatSieOfertaCurricular extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_sie_oferta_curricular');
        $this->hasColumn('id_oferta_curricular', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('cod_asignatura_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('nivel_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('ciclo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('grado_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaGestion', array(
             'local' => 'gestion_id',
             'foreign' => 'id_gestion'));

        $this->hasOne('ClaGrado', array(
             'local' => 'grado_id',
             'foreign' => 'id_grado'));

        $this->hasOne('ClaGrado as ClaGrado_3', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasOne('ClaGrado as ClaGrado_4', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasOne('DatSlnEstudios', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue_id'));

        $this->hasOne('DatSlnEstudios as DatSlnEstudios_6', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasOne('DatSlnEstudios as DatSlnEstudios_7', array(
             'local' => 'cod_asignatura_id',
             'foreign' => 'cod_asignatura_id'));

        $this->hasMany('RelDocenteOfertacurricular', array(
             'local' => 'id_oferta_curricular',
             'foreign' => 'oferta_curricular_id'));

        $this->hasMany('RelDocenteOfertacurricular as RelDocenteOfertacurricular_2', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));
    }
}