<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaOrigendiscapacidad', 'doctrine');

/**
 * BaseClaOrigendiscapacidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_origendiscapacidad
 * @property string $desc_origendiscapacidad
 * @property Doctrine_Collection $DatRdeDiscapacidad
 * @property Doctrine_Collection $DatRdeSocioEconomico
 * @property Doctrine_Collection $SdatRdeSocioEconomico
 * 
 * @method integer               getIdOrigendiscapacidad()    Returns the current record's "id_origendiscapacidad" value
 * @method string                getDescOrigendiscapacidad()  Returns the current record's "desc_origendiscapacidad" value
 * @method Doctrine_Collection   getDatRdeDiscapacidad()      Returns the current record's "DatRdeDiscapacidad" collection
 * @method Doctrine_Collection   getDatRdeSocioEconomico()    Returns the current record's "DatRdeSocioEconomico" collection
 * @method Doctrine_Collection   getSdatRdeSocioEconomico()   Returns the current record's "SdatRdeSocioEconomico" collection
 * @method ClaOrigendiscapacidad setIdOrigendiscapacidad()    Sets the current record's "id_origendiscapacidad" value
 * @method ClaOrigendiscapacidad setDescOrigendiscapacidad()  Sets the current record's "desc_origendiscapacidad" value
 * @method ClaOrigendiscapacidad setDatRdeDiscapacidad()      Sets the current record's "DatRdeDiscapacidad" collection
 * @method ClaOrigendiscapacidad setDatRdeSocioEconomico()    Sets the current record's "DatRdeSocioEconomico" collection
 * @method ClaOrigendiscapacidad setSdatRdeSocioEconomico()   Sets the current record's "SdatRdeSocioEconomico" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaOrigendiscapacidad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_origendiscapacidad');
        $this->hasColumn('id_origendiscapacidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('desc_origendiscapacidad', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DatRdeDiscapacidad', array(
             'local' => 'id_origendiscapacidad',
             'foreign' => 'origendiscapacidad_id'));

        $this->hasMany('DatRdeSocioEconomico', array(
             'local' => 'id_origendiscapacidad',
             'foreign' => 'origendiscapacidad_id'));

        $this->hasMany('SdatRdeSocioEconomico', array(
             'local' => 'id_origendiscapacidad',
             'foreign' => 'origendiscapacidad_id'));
    }
}