<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaEdaEstadoRecursos', 'doctrine');

/**
 * BaseClaEdaEstadoRecursos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_estado_recursos
 * @property string $desc_estado_recursos
 * @property Doctrine_Collection $DatEdaEquipamiento
 * @property Doctrine_Collection $DatEdaMobiliario
 * 
 * @method integer              getIdEstadoRecursos()     Returns the current record's "id_estado_recursos" value
 * @method string               getDescEstadoRecursos()   Returns the current record's "desc_estado_recursos" value
 * @method Doctrine_Collection  getDatEdaEquipamiento()   Returns the current record's "DatEdaEquipamiento" collection
 * @method Doctrine_Collection  getDatEdaMobiliario()     Returns the current record's "DatEdaMobiliario" collection
 * @method ClaEdaEstadoRecursos setIdEstadoRecursos()     Sets the current record's "id_estado_recursos" value
 * @method ClaEdaEstadoRecursos setDescEstadoRecursos()   Sets the current record's "desc_estado_recursos" value
 * @method ClaEdaEstadoRecursos setDatEdaEquipamiento()   Sets the current record's "DatEdaEquipamiento" collection
 * @method ClaEdaEstadoRecursos setDatEdaMobiliario()     Sets the current record's "DatEdaMobiliario" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaEdaEstadoRecursos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_eda_estado_recursos');
        $this->hasColumn('id_estado_recursos', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('desc_estado_recursos', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DatEdaEquipamiento', array(
             'local' => 'id_estado_recursos',
             'foreign' => 'estado_recursos_id'));

        $this->hasMany('DatEdaMobiliario', array(
             'local' => 'id_estado_recursos',
             'foreign' => 'estado_recursos_id'));
    }
}