<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatRdeInscripcionTecnica', 'doctrine');

/**
 * BaseDatRdeInscripcionTecnica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_inscripcion
 * @property integer $gestion_id
 * @property string $codigo_rude_id
 * @property integer $num_matricula
 * @property string $cod_ue_id
 * @property integer $periodo_id
 * @property integer $operativo_id
 * @property integer $sub_cea_id
 * @property integer $nivel_id
 * @property integer $grado_id
 * @property integer $ciclo_id
 * @property string $paralelo
 * @property integer $turno_id
 * @property integer $curso_oferta_id
 * @property integer $estado_matricula_inicio_id
 * @property integer $estado_matricula_fin_id
 * @property date $fecha_inscripcion
 * @property string $apreciacion_final
 * @property integer $postula_acreditacion_n_id
 * @property integer $postula_acreditacion_c_id
 * @property ClaEstadoMatricula $ClaEstadoMatricula
 * @property ClaEstadoMatricula $ClaEstadoMatricula_2
 * @property DatRdeEstudiante $DatRdeEstudiante
 * @property DatAltCursoTecnica $DatAltCursoTecnica
 * @property DatAltCursoTecnica $DatAltCursoTecnica_5
 * @property DatAltCursoTecnica $DatAltCursoTecnica_6
 * @property DatAltCursoTecnica $DatAltCursoTecnica_7
 * @property DatAltCursoTecnica $DatAltCursoTecnica_8
 * @property DatAltCursoTecnica $DatAltCursoTecnica_9
 * @property DatAltCursoTecnica $DatAltCursoTecnica_10
 * @property DatAltCursoTecnica $DatAltCursoTecnica_11
 * @property DatAltCursoTecnica $DatAltCursoTecnica_12
 * @property DatAltCursoTecnica $DatAltCursoTecnica_13
 * @property DatAltCursoTecnica $DatAltCursoTecnica_14
 * @property ClaCiclo $ClaCiclo
 * @property ClaCiclo $ClaCiclo_16
 * @property Doctrine_Collection $CtrRdeExtemporaneoTecnica
 * @property Doctrine_Collection $CtrRdeExtemporaneoTecnica_2
 * 
 * @method integer                  getIdInscripcion()               Returns the current record's "id_inscripcion" value
 * @method integer                  getGestionId()                   Returns the current record's "gestion_id" value
 * @method string                   getCodigoRudeId()                Returns the current record's "codigo_rude_id" value
 * @method integer                  getNumMatricula()                Returns the current record's "num_matricula" value
 * @method string                   getCodUeId()                     Returns the current record's "cod_ue_id" value
 * @method integer                  getPeriodoId()                   Returns the current record's "periodo_id" value
 * @method integer                  getOperativoId()                 Returns the current record's "operativo_id" value
 * @method integer                  getSubCeaId()                    Returns the current record's "sub_cea_id" value
 * @method integer                  getNivelId()                     Returns the current record's "nivel_id" value
 * @method integer                  getGradoId()                     Returns the current record's "grado_id" value
 * @method integer                  getCicloId()                     Returns the current record's "ciclo_id" value
 * @method string                   getParalelo()                    Returns the current record's "paralelo" value
 * @method integer                  getTurnoId()                     Returns the current record's "turno_id" value
 * @method integer                  getCursoOfertaId()               Returns the current record's "curso_oferta_id" value
 * @method integer                  getEstadoMatriculaInicioId()     Returns the current record's "estado_matricula_inicio_id" value
 * @method integer                  getEstadoMatriculaFinId()        Returns the current record's "estado_matricula_fin_id" value
 * @method date                     getFechaInscripcion()            Returns the current record's "fecha_inscripcion" value
 * @method string                   getApreciacionFinal()            Returns the current record's "apreciacion_final" value
 * @method integer                  getPostulaAcreditacionNId()      Returns the current record's "postula_acreditacion_n_id" value
 * @method integer                  getPostulaAcreditacionCId()      Returns the current record's "postula_acreditacion_c_id" value
 * @method ClaEstadoMatricula       getClaEstadoMatricula()          Returns the current record's "ClaEstadoMatricula" value
 * @method ClaEstadoMatricula       getClaEstadoMatricula2()         Returns the current record's "ClaEstadoMatricula_2" value
 * @method DatRdeEstudiante         getDatRdeEstudiante()            Returns the current record's "DatRdeEstudiante" value
 * @method DatAltCursoTecnica       getDatAltCursoTecnica()          Returns the current record's "DatAltCursoTecnica" value
 * @method DatAltCursoTecnica       getDatAltCursoTecnica5()         Returns the current record's "DatAltCursoTecnica_5" value
 * @method DatAltCursoTecnica       getDatAltCursoTecnica6()         Returns the current record's "DatAltCursoTecnica_6" value
 * @method DatAltCursoTecnica       getDatAltCursoTecnica7()         Returns the current record's "DatAltCursoTecnica_7" value
 * @method DatAltCursoTecnica       getDatAltCursoTecnica8()         Returns the current record's "DatAltCursoTecnica_8" value
 * @method DatAltCursoTecnica       getDatAltCursoTecnica9()         Returns the current record's "DatAltCursoTecnica_9" value
 * @method DatAltCursoTecnica       getDatAltCursoTecnica10()        Returns the current record's "DatAltCursoTecnica_10" value
 * @method DatAltCursoTecnica       getDatAltCursoTecnica11()        Returns the current record's "DatAltCursoTecnica_11" value
 * @method DatAltCursoTecnica       getDatAltCursoTecnica12()        Returns the current record's "DatAltCursoTecnica_12" value
 * @method DatAltCursoTecnica       getDatAltCursoTecnica13()        Returns the current record's "DatAltCursoTecnica_13" value
 * @method DatAltCursoTecnica       getDatAltCursoTecnica14()        Returns the current record's "DatAltCursoTecnica_14" value
 * @method ClaCiclo                 getClaCiclo()                    Returns the current record's "ClaCiclo" value
 * @method ClaCiclo                 getClaCiclo16()                  Returns the current record's "ClaCiclo_16" value
 * @method Doctrine_Collection      getCtrRdeExtemporaneoTecnica()   Returns the current record's "CtrRdeExtemporaneoTecnica" collection
 * @method Doctrine_Collection      getCtrRdeExtemporaneoTecnica2()  Returns the current record's "CtrRdeExtemporaneoTecnica_2" collection
 * @method DatRdeInscripcionTecnica setIdInscripcion()               Sets the current record's "id_inscripcion" value
 * @method DatRdeInscripcionTecnica setGestionId()                   Sets the current record's "gestion_id" value
 * @method DatRdeInscripcionTecnica setCodigoRudeId()                Sets the current record's "codigo_rude_id" value
 * @method DatRdeInscripcionTecnica setNumMatricula()                Sets the current record's "num_matricula" value
 * @method DatRdeInscripcionTecnica setCodUeId()                     Sets the current record's "cod_ue_id" value
 * @method DatRdeInscripcionTecnica setPeriodoId()                   Sets the current record's "periodo_id" value
 * @method DatRdeInscripcionTecnica setOperativoId()                 Sets the current record's "operativo_id" value
 * @method DatRdeInscripcionTecnica setSubCeaId()                    Sets the current record's "sub_cea_id" value
 * @method DatRdeInscripcionTecnica setNivelId()                     Sets the current record's "nivel_id" value
 * @method DatRdeInscripcionTecnica setGradoId()                     Sets the current record's "grado_id" value
 * @method DatRdeInscripcionTecnica setCicloId()                     Sets the current record's "ciclo_id" value
 * @method DatRdeInscripcionTecnica setParalelo()                    Sets the current record's "paralelo" value
 * @method DatRdeInscripcionTecnica setTurnoId()                     Sets the current record's "turno_id" value
 * @method DatRdeInscripcionTecnica setCursoOfertaId()               Sets the current record's "curso_oferta_id" value
 * @method DatRdeInscripcionTecnica setEstadoMatriculaInicioId()     Sets the current record's "estado_matricula_inicio_id" value
 * @method DatRdeInscripcionTecnica setEstadoMatriculaFinId()        Sets the current record's "estado_matricula_fin_id" value
 * @method DatRdeInscripcionTecnica setFechaInscripcion()            Sets the current record's "fecha_inscripcion" value
 * @method DatRdeInscripcionTecnica setApreciacionFinal()            Sets the current record's "apreciacion_final" value
 * @method DatRdeInscripcionTecnica setPostulaAcreditacionNId()      Sets the current record's "postula_acreditacion_n_id" value
 * @method DatRdeInscripcionTecnica setPostulaAcreditacionCId()      Sets the current record's "postula_acreditacion_c_id" value
 * @method DatRdeInscripcionTecnica setClaEstadoMatricula()          Sets the current record's "ClaEstadoMatricula" value
 * @method DatRdeInscripcionTecnica setClaEstadoMatricula2()         Sets the current record's "ClaEstadoMatricula_2" value
 * @method DatRdeInscripcionTecnica setDatRdeEstudiante()            Sets the current record's "DatRdeEstudiante" value
 * @method DatRdeInscripcionTecnica setDatAltCursoTecnica()          Sets the current record's "DatAltCursoTecnica" value
 * @method DatRdeInscripcionTecnica setDatAltCursoTecnica5()         Sets the current record's "DatAltCursoTecnica_5" value
 * @method DatRdeInscripcionTecnica setDatAltCursoTecnica6()         Sets the current record's "DatAltCursoTecnica_6" value
 * @method DatRdeInscripcionTecnica setDatAltCursoTecnica7()         Sets the current record's "DatAltCursoTecnica_7" value
 * @method DatRdeInscripcionTecnica setDatAltCursoTecnica8()         Sets the current record's "DatAltCursoTecnica_8" value
 * @method DatRdeInscripcionTecnica setDatAltCursoTecnica9()         Sets the current record's "DatAltCursoTecnica_9" value
 * @method DatRdeInscripcionTecnica setDatAltCursoTecnica10()        Sets the current record's "DatAltCursoTecnica_10" value
 * @method DatRdeInscripcionTecnica setDatAltCursoTecnica11()        Sets the current record's "DatAltCursoTecnica_11" value
 * @method DatRdeInscripcionTecnica setDatAltCursoTecnica12()        Sets the current record's "DatAltCursoTecnica_12" value
 * @method DatRdeInscripcionTecnica setDatAltCursoTecnica13()        Sets the current record's "DatAltCursoTecnica_13" value
 * @method DatRdeInscripcionTecnica setDatAltCursoTecnica14()        Sets the current record's "DatAltCursoTecnica_14" value
 * @method DatRdeInscripcionTecnica setClaCiclo()                    Sets the current record's "ClaCiclo" value
 * @method DatRdeInscripcionTecnica setClaCiclo16()                  Sets the current record's "ClaCiclo_16" value
 * @method DatRdeInscripcionTecnica setCtrRdeExtemporaneoTecnica()   Sets the current record's "CtrRdeExtemporaneoTecnica" collection
 * @method DatRdeInscripcionTecnica setCtrRdeExtemporaneoTecnica2()  Sets the current record's "CtrRdeExtemporaneoTecnica_2" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatRdeInscripcionTecnica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_rde_inscripcion_tecnica');
        $this->hasColumn('id_inscripcion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('codigo_rude_id', 'string', 18, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '18',
             ));
        $this->hasColumn('num_matricula', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('periodo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('operativo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('sub_cea_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('nivel_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('grado_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('ciclo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('paralelo', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('turno_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('curso_oferta_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('estado_matricula_inicio_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('estado_matricula_fin_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('fecha_inscripcion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('apreciacion_final', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('postula_acreditacion_n_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('postula_acreditacion_c_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaEstadoMatricula', array(
             'local' => 'estado_matricula_inicio_id',
             'foreign' => 'id_estado_matricula'));

        $this->hasOne('ClaEstadoMatricula as ClaEstadoMatricula_2', array(
             'local' => 'estado_matricula_fin_id',
             'foreign' => 'id_estado_matricula'));

        $this->hasOne('DatRdeEstudiante', array(
             'local' => 'codigo_rude_id',
             'foreign' => 'codigo_rude'));

        $this->hasOne('DatAltCursoTecnica', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue_id'));

        $this->hasOne('DatAltCursoTecnica as DatAltCursoTecnica_5', array(
             'local' => 'periodo_id',
             'foreign' => 'periodo_id'));

        $this->hasOne('DatAltCursoTecnica as DatAltCursoTecnica_6', array(
             'local' => 'operativo_id',
             'foreign' => 'operativo_id'));

        $this->hasOne('DatAltCursoTecnica as DatAltCursoTecnica_7', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasOne('DatAltCursoTecnica as DatAltCursoTecnica_8', array(
             'local' => 'sub_cea_id',
             'foreign' => 'sub_cea_id'));

        $this->hasOne('DatAltCursoTecnica as DatAltCursoTecnica_9', array(
             'local' => 'grado_id',
             'foreign' => 'grado_id'));

        $this->hasOne('DatAltCursoTecnica as DatAltCursoTecnica_10', array(
             'local' => 'ciclo_id',
             'foreign' => 'ciclo_id'));

        $this->hasOne('DatAltCursoTecnica as DatAltCursoTecnica_11', array(
             'local' => 'nivel_id',
             'foreign' => 'nivel_id'));

        $this->hasOne('DatAltCursoTecnica as DatAltCursoTecnica_12', array(
             'local' => 'paralelo',
             'foreign' => 'paralelo'));

        $this->hasOne('DatAltCursoTecnica as DatAltCursoTecnica_13', array(
             'local' => 'turno_id',
             'foreign' => 'turno_id'));

        $this->hasOne('DatAltCursoTecnica as DatAltCursoTecnica_14', array(
             'local' => 'curso_oferta_id',
             'foreign' => 'curso_oferta_id'));

        $this->hasOne('ClaCiclo', array(
             'local' => 'postula_acreditacion_n_id',
             'foreign' => 'nivel_id'));

        $this->hasOne('ClaCiclo as ClaCiclo_16', array(
             'local' => 'postula_acreditacion_c_id',
             'foreign' => 'id_ciclo'));

        $this->hasMany('CtrRdeExtemporaneoTecnica', array(
             'local' => 'id_inscripcion',
             'foreign' => 'inscripcion_id'));

        $this->hasMany('CtrRdeExtemporaneoTecnica as CtrRdeExtemporaneoTecnica_2', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));
    }
}