<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaEstadoCivil', 'doctrine');

/**
 * BaseClaEstadoCivil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_estado_civil
 * @property string $estado_civil
 * @property Doctrine_Collection $HisRdeEstudiante
 * 
 * @method integer             getIdEstadoCivil()    Returns the current record's "id_estado_civil" value
 * @method string              getEstadoCivil()      Returns the current record's "estado_civil" value
 * @method Doctrine_Collection getHisRdeEstudiante() Returns the current record's "HisRdeEstudiante" collection
 * @method ClaEstadoCivil      setIdEstadoCivil()    Sets the current record's "id_estado_civil" value
 * @method ClaEstadoCivil      setEstadoCivil()      Sets the current record's "estado_civil" value
 * @method ClaEstadoCivil      setHisRdeEstudiante() Sets the current record's "HisRdeEstudiante" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaEstadoCivil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_estado_civil');
        $this->hasColumn('id_estado_civil', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('estado_civil', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('HisRdeEstudiante', array(
             'local' => 'id_estado_civil',
             'foreign' => 'estado_civil_id'));
    }
}