<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaEstadoMatricula', 'doctrine');

/**
 * BaseClaEstadoMatricula
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_estado_matricula
 * @property string $desc_estado_matricula
 * @property integer $operativo
 * @property Doctrine_Collection $ClaEstadoDiplomas
 * @property Doctrine_Collection $CtrRdeInscripcion
 * @property Doctrine_Collection $CtrRdeInscripcion_3
 * @property Doctrine_Collection $CtrSlnCambioEstado
 * @property Doctrine_Collection $CtrSlnCambioEstado_4
 * @property Doctrine_Collection $DatRdeInscripcion
 * @property Doctrine_Collection $DatRdeInscripcion_2
 * @property Doctrine_Collection $DatRdeInscripcionEspecial
 * @property Doctrine_Collection $DatRdeInscripcionEspecial_2
 * @property Doctrine_Collection $DatRdeInscripcionTecnica
 * @property Doctrine_Collection $DatRdeInscripcionTecnica_2
 * @property Doctrine_Collection $DatRueInscripcionTramite
 * @property Doctrine_Collection $DatRueInscripcionTramite_11
 * @property Doctrine_Collection $HisRdeInscripcion
 * @property Doctrine_Collection $HisRdeInscripcion_3
 * @property Doctrine_Collection $SdatRdeInscripcion
 * @property Doctrine_Collection $SdatRdeInscripcion_3
 * @property Doctrine_Collection $SdatRdeInscripcionTmp
 * @property Doctrine_Collection $SdatRdeInscripcionTmp_3
 * 
 * @method integer             getIdEstadoMatricula()           Returns the current record's "id_estado_matricula" value
 * @method string              getDescEstadoMatricula()         Returns the current record's "desc_estado_matricula" value
 * @method integer             getOperativo()                   Returns the current record's "operativo" value
 * @method Doctrine_Collection getClaEstadoDiplomas()           Returns the current record's "ClaEstadoDiplomas" collection
 * @method Doctrine_Collection getCtrRdeInscripcion()           Returns the current record's "CtrRdeInscripcion" collection
 * @method Doctrine_Collection getCtrRdeInscripcion3()          Returns the current record's "CtrRdeInscripcion_3" collection
 * @method Doctrine_Collection getCtrSlnCambioEstado()          Returns the current record's "CtrSlnCambioEstado" collection
 * @method Doctrine_Collection getCtrSlnCambioEstado4()         Returns the current record's "CtrSlnCambioEstado_4" collection
 * @method Doctrine_Collection getDatRdeInscripcion()           Returns the current record's "DatRdeInscripcion" collection
 * @method Doctrine_Collection getDatRdeInscripcion2()          Returns the current record's "DatRdeInscripcion_2" collection
 * @method Doctrine_Collection getDatRdeInscripcionEspecial()   Returns the current record's "DatRdeInscripcionEspecial" collection
 * @method Doctrine_Collection getDatRdeInscripcionEspecial2()  Returns the current record's "DatRdeInscripcionEspecial_2" collection
 * @method Doctrine_Collection getDatRdeInscripcionTecnica()    Returns the current record's "DatRdeInscripcionTecnica" collection
 * @method Doctrine_Collection getDatRdeInscripcionTecnica2()   Returns the current record's "DatRdeInscripcionTecnica_2" collection
 * @method Doctrine_Collection getDatRueInscripcionTramite()    Returns the current record's "DatRueInscripcionTramite" collection
 * @method Doctrine_Collection getDatRueInscripcionTramite11()  Returns the current record's "DatRueInscripcionTramite_11" collection
 * @method Doctrine_Collection getHisRdeInscripcion()           Returns the current record's "HisRdeInscripcion" collection
 * @method Doctrine_Collection getHisRdeInscripcion3()          Returns the current record's "HisRdeInscripcion_3" collection
 * @method Doctrine_Collection getSdatRdeInscripcion()          Returns the current record's "SdatRdeInscripcion" collection
 * @method Doctrine_Collection getSdatRdeInscripcion3()         Returns the current record's "SdatRdeInscripcion_3" collection
 * @method Doctrine_Collection getSdatRdeInscripcionTmp()       Returns the current record's "SdatRdeInscripcionTmp" collection
 * @method Doctrine_Collection getSdatRdeInscripcionTmp3()      Returns the current record's "SdatRdeInscripcionTmp_3" collection
 * @method ClaEstadoMatricula  setIdEstadoMatricula()           Sets the current record's "id_estado_matricula" value
 * @method ClaEstadoMatricula  setDescEstadoMatricula()         Sets the current record's "desc_estado_matricula" value
 * @method ClaEstadoMatricula  setOperativo()                   Sets the current record's "operativo" value
 * @method ClaEstadoMatricula  setClaEstadoDiplomas()           Sets the current record's "ClaEstadoDiplomas" collection
 * @method ClaEstadoMatricula  setCtrRdeInscripcion()           Sets the current record's "CtrRdeInscripcion" collection
 * @method ClaEstadoMatricula  setCtrRdeInscripcion3()          Sets the current record's "CtrRdeInscripcion_3" collection
 * @method ClaEstadoMatricula  setCtrSlnCambioEstado()          Sets the current record's "CtrSlnCambioEstado" collection
 * @method ClaEstadoMatricula  setCtrSlnCambioEstado4()         Sets the current record's "CtrSlnCambioEstado_4" collection
 * @method ClaEstadoMatricula  setDatRdeInscripcion()           Sets the current record's "DatRdeInscripcion" collection
 * @method ClaEstadoMatricula  setDatRdeInscripcion2()          Sets the current record's "DatRdeInscripcion_2" collection
 * @method ClaEstadoMatricula  setDatRdeInscripcionEspecial()   Sets the current record's "DatRdeInscripcionEspecial" collection
 * @method ClaEstadoMatricula  setDatRdeInscripcionEspecial2()  Sets the current record's "DatRdeInscripcionEspecial_2" collection
 * @method ClaEstadoMatricula  setDatRdeInscripcionTecnica()    Sets the current record's "DatRdeInscripcionTecnica" collection
 * @method ClaEstadoMatricula  setDatRdeInscripcionTecnica2()   Sets the current record's "DatRdeInscripcionTecnica_2" collection
 * @method ClaEstadoMatricula  setDatRueInscripcionTramite()    Sets the current record's "DatRueInscripcionTramite" collection
 * @method ClaEstadoMatricula  setDatRueInscripcionTramite11()  Sets the current record's "DatRueInscripcionTramite_11" collection
 * @method ClaEstadoMatricula  setHisRdeInscripcion()           Sets the current record's "HisRdeInscripcion" collection
 * @method ClaEstadoMatricula  setHisRdeInscripcion3()          Sets the current record's "HisRdeInscripcion_3" collection
 * @method ClaEstadoMatricula  setSdatRdeInscripcion()          Sets the current record's "SdatRdeInscripcion" collection
 * @method ClaEstadoMatricula  setSdatRdeInscripcion3()         Sets the current record's "SdatRdeInscripcion_3" collection
 * @method ClaEstadoMatricula  setSdatRdeInscripcionTmp()       Sets the current record's "SdatRdeInscripcionTmp" collection
 * @method ClaEstadoMatricula  setSdatRdeInscripcionTmp3()      Sets the current record's "SdatRdeInscripcionTmp_3" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaEstadoMatricula extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_estado_matricula');
        $this->hasColumn('id_estado_matricula', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('desc_estado_matricula', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('operativo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClaEstadoDiplomas', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_id'));

        $this->hasMany('CtrRdeInscripcion', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_inicio_id'));

        $this->hasMany('CtrRdeInscripcion as CtrRdeInscripcion_3', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_fin_id'));

        $this->hasMany('CtrSlnCambioEstado', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_anterior'));

        $this->hasMany('CtrSlnCambioEstado as CtrSlnCambioEstado_4', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_actual'));

        $this->hasMany('DatRdeInscripcion', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_inicio_id'));

        $this->hasMany('DatRdeInscripcion as DatRdeInscripcion_2', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_fin_id'));

        $this->hasMany('DatRdeInscripcionEspecial', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_inicio_id'));

        $this->hasMany('DatRdeInscripcionEspecial as DatRdeInscripcionEspecial_2', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_fin_id'));

        $this->hasMany('DatRdeInscripcionTecnica', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_inicio_id'));

        $this->hasMany('DatRdeInscripcionTecnica as DatRdeInscripcionTecnica_2', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_fin_id'));

        $this->hasMany('DatRueInscripcionTramite', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_inicio_id'));

        $this->hasMany('DatRueInscripcionTramite as DatRueInscripcionTramite_11', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_fin_id'));

        $this->hasMany('HisRdeInscripcion', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_inicio_id'));

        $this->hasMany('HisRdeInscripcion as HisRdeInscripcion_3', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_fin_id'));

        $this->hasMany('SdatRdeInscripcion', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_fin_id'));

        $this->hasMany('SdatRdeInscripcion as SdatRdeInscripcion_3', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_inicio_id'));

        $this->hasMany('SdatRdeInscripcionTmp', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_fin_id'));

        $this->hasMany('SdatRdeInscripcionTmp as SdatRdeInscripcionTmp_3', array(
             'local' => 'id_estado_matricula',
             'foreign' => 'estado_matricula_inicio_id'));
    }
}