<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TmpSieAdministrativo', 'doctrine');

/**
 * BaseTmpSieAdministrativo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ci_administrativo_id
 * @property string $cod_ue_id
 * @property integer $sub_cea
 * @property integer $gestion_id
 * @property integer $periodo_id
 * @property integer $operativo_id
 * @property integer $financiamiento_id
 * @property integer $cargo_id
 * @property string $servicio
 * @property string $item
 * @property string $formacion
 * 
 * @method string               getCiAdministrativoId()   Returns the current record's "ci_administrativo_id" value
 * @method string               getCodUeId()              Returns the current record's "cod_ue_id" value
 * @method integer              getSubCea()               Returns the current record's "sub_cea" value
 * @method integer              getGestionId()            Returns the current record's "gestion_id" value
 * @method integer              getPeriodoId()            Returns the current record's "periodo_id" value
 * @method integer              getOperativoId()          Returns the current record's "operativo_id" value
 * @method integer              getFinanciamientoId()     Returns the current record's "financiamiento_id" value
 * @method integer              getCargoId()              Returns the current record's "cargo_id" value
 * @method string               getServicio()             Returns the current record's "servicio" value
 * @method string               getItem()                 Returns the current record's "item" value
 * @method string               getFormacion()            Returns the current record's "formacion" value
 * @method TmpSieAdministrativo setCiAdministrativoId()   Sets the current record's "ci_administrativo_id" value
 * @method TmpSieAdministrativo setCodUeId()              Sets the current record's "cod_ue_id" value
 * @method TmpSieAdministrativo setSubCea()               Sets the current record's "sub_cea" value
 * @method TmpSieAdministrativo setGestionId()            Sets the current record's "gestion_id" value
 * @method TmpSieAdministrativo setPeriodoId()            Sets the current record's "periodo_id" value
 * @method TmpSieAdministrativo setOperativoId()          Sets the current record's "operativo_id" value
 * @method TmpSieAdministrativo setFinanciamientoId()     Sets the current record's "financiamiento_id" value
 * @method TmpSieAdministrativo setCargoId()              Sets the current record's "cargo_id" value
 * @method TmpSieAdministrativo setServicio()             Sets the current record's "servicio" value
 * @method TmpSieAdministrativo setItem()                 Sets the current record's "item" value
 * @method TmpSieAdministrativo setFormacion()            Sets the current record's "formacion" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTmpSieAdministrativo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tmp_sie_administrativo');
        $this->hasColumn('ci_administrativo_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('sub_cea', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('periodo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('operativo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('financiamiento_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('cargo_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('servicio', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('item', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('formacion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}