<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatAltConsolidacion', 'doctrine');

/**
 * BaseDatAltConsolidacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $cod_ue_id
 * @property string $path_file
 * @property timestamp $fecha_consolidacion
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getCodUeId()             Returns the current record's "cod_ue_id" value
 * @method string              getPathFile()            Returns the current record's "path_file" value
 * @method timestamp           getFechaConsolidacion()  Returns the current record's "fecha_consolidacion" value
 * @method DatAltConsolidacion setId()                  Sets the current record's "id" value
 * @method DatAltConsolidacion setCodUeId()             Sets the current record's "cod_ue_id" value
 * @method DatAltConsolidacion setPathFile()            Sets the current record's "path_file" value
 * @method DatAltConsolidacion setFechaConsolidacion()  Sets the current record's "fecha_consolidacion" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatAltConsolidacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_alt_consolidacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('path_file', 'string', 5000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '5000',
             ));
        $this->hasColumn('fecha_consolidacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}