<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatSieAdministrativo', 'doctrine');

/**
 * BaseDatSieAdministrativo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ci_docente_id
 * @property integer $gestion_id
 * @property string $cod_ue_id
 * @property integer $periodo_id
 * @property integer $operativo_id
 * @property integer $sub_cea_id
 * @property integer $cargo_id
 * @property integer $mes
 * @property integer $financiamiento_id
 * @property ClaFinanciamiento $ClaFinanciamiento
 * @property DatSieDocenteadministrativo $DatSieDocenteadministrativo
 * @property ClaCargo $ClaCargo
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa_5
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa_6
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa_7
 * @property DatSieUnidadEducativa $DatSieUnidadEducativa_8
 * @property Doctrine_Collection $RelAdministrativoItems
 * @property Doctrine_Collection $RelAdministrativoItems_5
 * @property Doctrine_Collection $RelAdministrativoItems_6
 * @property Doctrine_Collection $RelAdministrativoItems_7
 * @property Doctrine_Collection $RelAdministrativoItems_8
 * @property Doctrine_Collection $RelAdministrativoItems_9
 * 
 * @method integer                     getCiDocenteId()                 Returns the current record's "ci_docente_id" value
 * @method integer                     getGestionId()                   Returns the current record's "gestion_id" value
 * @method string                      getCodUeId()                     Returns the current record's "cod_ue_id" value
 * @method integer                     getPeriodoId()                   Returns the current record's "periodo_id" value
 * @method integer                     getOperativoId()                 Returns the current record's "operativo_id" value
 * @method integer                     getSubCeaId()                    Returns the current record's "sub_cea_id" value
 * @method integer                     getCargoId()                     Returns the current record's "cargo_id" value
 * @method integer                     getMes()                         Returns the current record's "mes" value
 * @method integer                     getFinanciamientoId()            Returns the current record's "financiamiento_id" value
 * @method ClaFinanciamiento           getClaFinanciamiento()           Returns the current record's "ClaFinanciamiento" value
 * @method DatSieDocenteadministrativo getDatSieDocenteadministrativo() Returns the current record's "DatSieDocenteadministrativo" value
 * @method ClaCargo                    getClaCargo()                    Returns the current record's "ClaCargo" value
 * @method DatSieUnidadEducativa       getDatSieUnidadEducativa()       Returns the current record's "DatSieUnidadEducativa" value
 * @method DatSieUnidadEducativa       getDatSieUnidadEducativa5()      Returns the current record's "DatSieUnidadEducativa_5" value
 * @method DatSieUnidadEducativa       getDatSieUnidadEducativa6()      Returns the current record's "DatSieUnidadEducativa_6" value
 * @method DatSieUnidadEducativa       getDatSieUnidadEducativa7()      Returns the current record's "DatSieUnidadEducativa_7" value
 * @method DatSieUnidadEducativa       getDatSieUnidadEducativa8()      Returns the current record's "DatSieUnidadEducativa_8" value
 * @method Doctrine_Collection         getRelAdministrativoItems()      Returns the current record's "RelAdministrativoItems" collection
 * @method Doctrine_Collection         getRelAdministrativoItems5()     Returns the current record's "RelAdministrativoItems_5" collection
 * @method Doctrine_Collection         getRelAdministrativoItems6()     Returns the current record's "RelAdministrativoItems_6" collection
 * @method Doctrine_Collection         getRelAdministrativoItems7()     Returns the current record's "RelAdministrativoItems_7" collection
 * @method Doctrine_Collection         getRelAdministrativoItems8()     Returns the current record's "RelAdministrativoItems_8" collection
 * @method Doctrine_Collection         getRelAdministrativoItems9()     Returns the current record's "RelAdministrativoItems_9" collection
 * @method DatSieAdministrativo        setCiDocenteId()                 Sets the current record's "ci_docente_id" value
 * @method DatSieAdministrativo        setGestionId()                   Sets the current record's "gestion_id" value
 * @method DatSieAdministrativo        setCodUeId()                     Sets the current record's "cod_ue_id" value
 * @method DatSieAdministrativo        setPeriodoId()                   Sets the current record's "periodo_id" value
 * @method DatSieAdministrativo        setOperativoId()                 Sets the current record's "operativo_id" value
 * @method DatSieAdministrativo        setSubCeaId()                    Sets the current record's "sub_cea_id" value
 * @method DatSieAdministrativo        setCargoId()                     Sets the current record's "cargo_id" value
 * @method DatSieAdministrativo        setMes()                         Sets the current record's "mes" value
 * @method DatSieAdministrativo        setFinanciamientoId()            Sets the current record's "financiamiento_id" value
 * @method DatSieAdministrativo        setClaFinanciamiento()           Sets the current record's "ClaFinanciamiento" value
 * @method DatSieAdministrativo        setDatSieDocenteadministrativo() Sets the current record's "DatSieDocenteadministrativo" value
 * @method DatSieAdministrativo        setClaCargo()                    Sets the current record's "ClaCargo" value
 * @method DatSieAdministrativo        setDatSieUnidadEducativa()       Sets the current record's "DatSieUnidadEducativa" value
 * @method DatSieAdministrativo        setDatSieUnidadEducativa5()      Sets the current record's "DatSieUnidadEducativa_5" value
 * @method DatSieAdministrativo        setDatSieUnidadEducativa6()      Sets the current record's "DatSieUnidadEducativa_6" value
 * @method DatSieAdministrativo        setDatSieUnidadEducativa7()      Sets the current record's "DatSieUnidadEducativa_7" value
 * @method DatSieAdministrativo        setDatSieUnidadEducativa8()      Sets the current record's "DatSieUnidadEducativa_8" value
 * @method DatSieAdministrativo        setRelAdministrativoItems()      Sets the current record's "RelAdministrativoItems" collection
 * @method DatSieAdministrativo        setRelAdministrativoItems5()     Sets the current record's "RelAdministrativoItems_5" collection
 * @method DatSieAdministrativo        setRelAdministrativoItems6()     Sets the current record's "RelAdministrativoItems_6" collection
 * @method DatSieAdministrativo        setRelAdministrativoItems7()     Sets the current record's "RelAdministrativoItems_7" collection
 * @method DatSieAdministrativo        setRelAdministrativoItems8()     Sets the current record's "RelAdministrativoItems_8" collection
 * @method DatSieAdministrativo        setRelAdministrativoItems9()     Sets the current record's "RelAdministrativoItems_9" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatSieAdministrativo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_sie_administrativo');
        $this->hasColumn('ci_docente_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('periodo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('operativo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('sub_cea_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('cargo_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('mes', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('financiamiento_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaFinanciamiento', array(
             'local' => 'financiamiento_id',
             'foreign' => 'id_financiamiento'));

        $this->hasOne('DatSieDocenteadministrativo', array(
             'local' => 'ci_docente_id',
             'foreign' => 'ci'));

        $this->hasOne('ClaCargo', array(
             'local' => 'cargo_id',
             'foreign' => 'id_cargo'));

        $this->hasOne('DatSieUnidadEducativa', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue_id'));

        $this->hasOne('DatSieUnidadEducativa as DatSieUnidadEducativa_5', array(
             'local' => 'periodo_id',
             'foreign' => 'periodo_id'));

        $this->hasOne('DatSieUnidadEducativa as DatSieUnidadEducativa_6', array(
             'local' => 'operativo_id',
             'foreign' => 'operativo_id'));

        $this->hasOne('DatSieUnidadEducativa as DatSieUnidadEducativa_7', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasOne('DatSieUnidadEducativa as DatSieUnidadEducativa_8', array(
             'local' => 'sub_cea_id',
             'foreign' => 'sub_cea'));

        $this->hasMany('RelAdministrativoItems', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasMany('RelAdministrativoItems as RelAdministrativoItems_5', array(
             'local' => 'ci_docente_id',
             'foreign' => 'ci_docente_id'));

        $this->hasMany('RelAdministrativoItems as RelAdministrativoItems_6', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue_id'));

        $this->hasMany('RelAdministrativoItems as RelAdministrativoItems_7', array(
             'local' => 'periodo_id',
             'foreign' => 'periodo_id'));

        $this->hasMany('RelAdministrativoItems as RelAdministrativoItems_8', array(
             'local' => 'operativo_id',
             'foreign' => 'operativo_id'));

        $this->hasMany('RelAdministrativoItems as RelAdministrativoItems_9', array(
             'local' => 'sub_cea_id',
             'foreign' => 'sub_cea_id'));
    }
}