<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaConvenios', 'doctrine');

/**
 * BaseClaConvenios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cod_convenios
 * @property string $desc_convenio
 * @property timestamp $fecha_inicio
 * @property timestamp $fecha_finalizacion
 * @property integer $duracion
 * @property string $tipo_convenio
 * @property integer $cod_dependencia_id
 * @property ClaDependencia $ClaDependencia
 * @property Doctrine_Collection $DatRueUnidadEducativa
 * @property Doctrine_Collection $DatRueUnidadEducativaTramite
 * @property Doctrine_Collection $SdatRueUnidadEducativa
 * 
 * @method integer             getCodConvenios()                 Returns the current record's "cod_convenios" value
 * @method string              getDescConvenio()                 Returns the current record's "desc_convenio" value
 * @method timestamp           getFechaInicio()                  Returns the current record's "fecha_inicio" value
 * @method timestamp           getFechaFinalizacion()            Returns the current record's "fecha_finalizacion" value
 * @method integer             getDuracion()                     Returns the current record's "duracion" value
 * @method string              getTipoConvenio()                 Returns the current record's "tipo_convenio" value
 * @method integer             getCodDependenciaId()             Returns the current record's "cod_dependencia_id" value
 * @method ClaDependencia      getClaDependencia()               Returns the current record's "ClaDependencia" value
 * @method Doctrine_Collection getDatRueUnidadEducativa()        Returns the current record's "DatRueUnidadEducativa" collection
 * @method Doctrine_Collection getDatRueUnidadEducativaTramite() Returns the current record's "DatRueUnidadEducativaTramite" collection
 * @method Doctrine_Collection getSdatRueUnidadEducativa()       Returns the current record's "SdatRueUnidadEducativa" collection
 * @method ClaConvenios        setCodConvenios()                 Sets the current record's "cod_convenios" value
 * @method ClaConvenios        setDescConvenio()                 Sets the current record's "desc_convenio" value
 * @method ClaConvenios        setFechaInicio()                  Sets the current record's "fecha_inicio" value
 * @method ClaConvenios        setFechaFinalizacion()            Sets the current record's "fecha_finalizacion" value
 * @method ClaConvenios        setDuracion()                     Sets the current record's "duracion" value
 * @method ClaConvenios        setTipoConvenio()                 Sets the current record's "tipo_convenio" value
 * @method ClaConvenios        setCodDependenciaId()             Sets the current record's "cod_dependencia_id" value
 * @method ClaConvenios        setClaDependencia()               Sets the current record's "ClaDependencia" value
 * @method ClaConvenios        setDatRueUnidadEducativa()        Sets the current record's "DatRueUnidadEducativa" collection
 * @method ClaConvenios        setDatRueUnidadEducativaTramite() Sets the current record's "DatRueUnidadEducativaTramite" collection
 * @method ClaConvenios        setSdatRueUnidadEducativa()       Sets the current record's "SdatRueUnidadEducativa" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseClaConvenios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cla_convenios');
        $this->hasColumn('cod_convenios', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('desc_convenio', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('fecha_inicio', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('fecha_finalizacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('duracion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('tipo_convenio', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('cod_dependencia_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaDependencia', array(
             'local' => 'cod_dependencia_id',
             'foreign' => 'cod_dependencia'));

        $this->hasMany('DatRueUnidadEducativa', array(
             'local' => 'cod_convenios',
             'foreign' => 'cod_convenio_id'));

        $this->hasMany('DatRueUnidadEducativaTramite', array(
             'local' => 'cod_convenios',
             'foreign' => 'cod_convenio_id'));

        $this->hasMany('SdatRueUnidadEducativa', array(
             'local' => 'cod_convenios',
             'foreign' => 'cod_convenio_id'));
    }
}