<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ErrOpeArchivos', 'doctrine');

/**
 * BaseErrOpeArchivos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $cod_ue
 * @property string $query
 * @property string $err0
 * @property string $err1
 * 
 * @method integer        getId()     Returns the current record's "id" value
 * @method string         getCodUe()  Returns the current record's "cod_ue" value
 * @method string         getQuery()  Returns the current record's "query" value
 * @method string         getErr0()   Returns the current record's "err0" value
 * @method string         getErr1()   Returns the current record's "err1" value
 * @method ErrOpeArchivos setId()     Sets the current record's "id" value
 * @method ErrOpeArchivos setCodUe()  Sets the current record's "cod_ue" value
 * @method ErrOpeArchivos setQuery()  Sets the current record's "query" value
 * @method ErrOpeArchivos setErr0()   Sets the current record's "err0" value
 * @method ErrOpeArchivos setErr1()   Sets the current record's "err1" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseErrOpeArchivos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('err_ope_archivos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('cod_ue', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('query', 'string', 550, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '550',
             ));
        $this->hasColumn('err0', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '200',
             ));
        $this->hasColumn('err1', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '200',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}