<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CtrPlaItems', 'doctrine');

/**
 * BaseCtrPlaItems
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $servicio
 * @property string $item
 * @property integer $gestion_id
 * @property integer $cargo_id
 * @property string $programa
 * @property integer $horas
 * @property integer $mes
 * @property ClaCargo $ClaCargo
 * @property DatPlaItems $DatPlaItems
 * @property DatPlaItems $DatPlaItems_3
 * @property DatPlaItems $DatPlaItems_4
 * 
 * @method string      getServicio()      Returns the current record's "servicio" value
 * @method string      getItem()          Returns the current record's "item" value
 * @method integer     getGestionId()     Returns the current record's "gestion_id" value
 * @method integer     getCargoId()       Returns the current record's "cargo_id" value
 * @method string      getPrograma()      Returns the current record's "programa" value
 * @method integer     getHoras()         Returns the current record's "horas" value
 * @method integer     getMes()           Returns the current record's "mes" value
 * @method ClaCargo    getClaCargo()      Returns the current record's "ClaCargo" value
 * @method DatPlaItems getDatPlaItems()   Returns the current record's "DatPlaItems" value
 * @method DatPlaItems getDatPlaItems3()  Returns the current record's "DatPlaItems_3" value
 * @method DatPlaItems getDatPlaItems4()  Returns the current record's "DatPlaItems_4" value
 * @method CtrPlaItems setServicio()      Sets the current record's "servicio" value
 * @method CtrPlaItems setItem()          Sets the current record's "item" value
 * @method CtrPlaItems setGestionId()     Sets the current record's "gestion_id" value
 * @method CtrPlaItems setCargoId()       Sets the current record's "cargo_id" value
 * @method CtrPlaItems setPrograma()      Sets the current record's "programa" value
 * @method CtrPlaItems setHoras()         Sets the current record's "horas" value
 * @method CtrPlaItems setMes()           Sets the current record's "mes" value
 * @method CtrPlaItems setClaCargo()      Sets the current record's "ClaCargo" value
 * @method CtrPlaItems setDatPlaItems()   Sets the current record's "DatPlaItems" value
 * @method CtrPlaItems setDatPlaItems3()  Sets the current record's "DatPlaItems_3" value
 * @method CtrPlaItems setDatPlaItems4()  Sets the current record's "DatPlaItems_4" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCtrPlaItems extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ctr_pla_items');
        $this->hasColumn('servicio', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('item', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '5',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('cargo_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('programa', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('horas', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('mes', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaCargo', array(
             'local' => 'cargo_id',
             'foreign' => 'id_cargo'));

        $this->hasOne('DatPlaItems', array(
             'local' => 'servicio',
             'foreign' => 'servicio'));

        $this->hasOne('DatPlaItems as DatPlaItems_3', array(
             'local' => 'item',
             'foreign' => 'item'));

        $this->hasOne('DatPlaItems as DatPlaItems_4', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));
    }
}