<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatRdeApoderado', 'doctrine');

/**
 * BaseDatRdeApoderado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_apoderado
 * @property string $carnet_identidad
 * @property string $paterno
 * @property string $materno
 * @property string $nombre
 * @property timestamp $fecha_nacimiento
 * @property Doctrine_Collection $DatRdeDatosapoderado
 * @property Doctrine_Collection $SdatRdeDatosapoderado
 * 
 * @method integer             getIdApoderado()           Returns the current record's "id_apoderado" value
 * @method string              getCarnetIdentidad()       Returns the current record's "carnet_identidad" value
 * @method string              getPaterno()               Returns the current record's "paterno" value
 * @method string              getMaterno()               Returns the current record's "materno" value
 * @method string              getNombre()                Returns the current record's "nombre" value
 * @method timestamp           getFechaNacimiento()       Returns the current record's "fecha_nacimiento" value
 * @method Doctrine_Collection getDatRdeDatosapoderado()  Returns the current record's "DatRdeDatosapoderado" collection
 * @method Doctrine_Collection getSdatRdeDatosapoderado() Returns the current record's "SdatRdeDatosapoderado" collection
 * @method DatRdeApoderado     setIdApoderado()           Sets the current record's "id_apoderado" value
 * @method DatRdeApoderado     setCarnetIdentidad()       Sets the current record's "carnet_identidad" value
 * @method DatRdeApoderado     setPaterno()               Sets the current record's "paterno" value
 * @method DatRdeApoderado     setMaterno()               Sets the current record's "materno" value
 * @method DatRdeApoderado     setNombre()                Sets the current record's "nombre" value
 * @method DatRdeApoderado     setFechaNacimiento()       Sets the current record's "fecha_nacimiento" value
 * @method DatRdeApoderado     setDatRdeDatosapoderado()  Sets the current record's "DatRdeDatosapoderado" collection
 * @method DatRdeApoderado     setSdatRdeDatosapoderado() Sets the current record's "SdatRdeDatosapoderado" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatRdeApoderado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_rde_apoderado');
        $this->hasColumn('id_apoderado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('carnet_identidad', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('paterno', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('materno', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('fecha_nacimiento', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DatRdeDatosapoderado', array(
             'local' => 'id_apoderado',
             'foreign' => 'apoderado_id'));

        $this->hasMany('SdatRdeDatosapoderado', array(
             'local' => 'id_apoderado',
             'foreign' => 'apoderado_id'));
    }
}