<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TmpTablaSiecliente', 'doctrine');

/**
 * BaseTmpTablaSiecliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $tabla
 * @property integer $order
 * 
 * @method integer            getId()    Returns the current record's "id" value
 * @method string             getTabla() Returns the current record's "tabla" value
 * @method integer            getOrder() Returns the current record's "order" value
 * @method TmpTablaSiecliente setId()    Sets the current record's "id" value
 * @method TmpTablaSiecliente setTabla() Sets the current record's "tabla" value
 * @method TmpTablaSiecliente setOrder() Sets the current record's "order" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTmpTablaSiecliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tmp_tabla_siecliente');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('tabla', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('order', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}