<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatSieOperativos', 'doctrine');

/**
 * BaseDatSieOperativos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gestion_id
 * @property integer $operativo_id
 * @property integer $cerrada
 * @property integer $cerrada_infraestructura
 * @property date $fecha_inicio
 * @property date $fecha_finalizacion
 * @property ClaGestion $ClaGestion
 * @property ClaOperativo $ClaOperativo
 * @property Doctrine_Collection $CtrSieUnidadEducativa
 * @property Doctrine_Collection $CtrSieUnidadEducativa_2
 * @property Doctrine_Collection $CtrSieUnidadEducativaConsolidado
 * @property Doctrine_Collection $CtrSieUnidadEducativaConsolidado_7
 * @property Doctrine_Collection $DatSieUnidadEducativa
 * @property Doctrine_Collection $DatSieUnidadEducativa_4
 * 
 * @method integer             getGestionId()                          Returns the current record's "gestion_id" value
 * @method integer             getOperativoId()                        Returns the current record's "operativo_id" value
 * @method integer             getCerrada()                            Returns the current record's "cerrada" value
 * @method integer             getCerradaInfraestructura()             Returns the current record's "cerrada_infraestructura" value
 * @method date                getFechaInicio()                        Returns the current record's "fecha_inicio" value
 * @method date                getFechaFinalizacion()                  Returns the current record's "fecha_finalizacion" value
 * @method ClaGestion          getClaGestion()                         Returns the current record's "ClaGestion" value
 * @method ClaOperativo        getClaOperativo()                       Returns the current record's "ClaOperativo" value
 * @method Doctrine_Collection getCtrSieUnidadEducativa()              Returns the current record's "CtrSieUnidadEducativa" collection
 * @method Doctrine_Collection getCtrSieUnidadEducativa2()             Returns the current record's "CtrSieUnidadEducativa_2" collection
 * @method Doctrine_Collection getCtrSieUnidadEducativaConsolidado()   Returns the current record's "CtrSieUnidadEducativaConsolidado" collection
 * @method Doctrine_Collection getCtrSieUnidadEducativaConsolidado7()  Returns the current record's "CtrSieUnidadEducativaConsolidado_7" collection
 * @method Doctrine_Collection getDatSieUnidadEducativa()              Returns the current record's "DatSieUnidadEducativa" collection
 * @method Doctrine_Collection getDatSieUnidadEducativa4()             Returns the current record's "DatSieUnidadEducativa_4" collection
 * @method DatSieOperativos    setGestionId()                          Sets the current record's "gestion_id" value
 * @method DatSieOperativos    setOperativoId()                        Sets the current record's "operativo_id" value
 * @method DatSieOperativos    setCerrada()                            Sets the current record's "cerrada" value
 * @method DatSieOperativos    setCerradaInfraestructura()             Sets the current record's "cerrada_infraestructura" value
 * @method DatSieOperativos    setFechaInicio()                        Sets the current record's "fecha_inicio" value
 * @method DatSieOperativos    setFechaFinalizacion()                  Sets the current record's "fecha_finalizacion" value
 * @method DatSieOperativos    setClaGestion()                         Sets the current record's "ClaGestion" value
 * @method DatSieOperativos    setClaOperativo()                       Sets the current record's "ClaOperativo" value
 * @method DatSieOperativos    setCtrSieUnidadEducativa()              Sets the current record's "CtrSieUnidadEducativa" collection
 * @method DatSieOperativos    setCtrSieUnidadEducativa2()             Sets the current record's "CtrSieUnidadEducativa_2" collection
 * @method DatSieOperativos    setCtrSieUnidadEducativaConsolidado()   Sets the current record's "CtrSieUnidadEducativaConsolidado" collection
 * @method DatSieOperativos    setCtrSieUnidadEducativaConsolidado7()  Sets the current record's "CtrSieUnidadEducativaConsolidado_7" collection
 * @method DatSieOperativos    setDatSieUnidadEducativa()              Sets the current record's "DatSieUnidadEducativa" collection
 * @method DatSieOperativos    setDatSieUnidadEducativa4()             Sets the current record's "DatSieUnidadEducativa_4" collection
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatSieOperativos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_sie_operativos');
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('operativo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('cerrada', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('cerrada_infraestructura', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('fecha_inicio', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('fecha_finalizacion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClaGestion', array(
             'local' => 'gestion_id',
             'foreign' => 'id_gestion'));

        $this->hasOne('ClaOperativo', array(
             'local' => 'operativo_id',
             'foreign' => 'id_operativo'));

        $this->hasMany('CtrSieUnidadEducativa', array(
             'local' => 'operativo_id',
             'foreign' => 'operativo_id'));

        $this->hasMany('CtrSieUnidadEducativa as CtrSieUnidadEducativa_2', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasMany('CtrSieUnidadEducativaConsolidado', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));

        $this->hasMany('CtrSieUnidadEducativaConsolidado as CtrSieUnidadEducativaConsolidado_7', array(
             'local' => 'operativo_id',
             'foreign' => 'operativo_id'));

        $this->hasMany('DatSieUnidadEducativa', array(
             'local' => 'operativo_id',
             'foreign' => 'operativo_id'));

        $this->hasMany('DatSieUnidadEducativa as DatSieUnidadEducativa_4', array(
             'local' => 'gestion_id',
             'foreign' => 'gestion_id'));
    }
}