<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatOpeUnidadEducativa', 'doctrine');

/**
 * BaseDatOpeUnidadEducativa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cod_ue_id
 * @property integer $sub_cea_id
 * @property integer $gestion_id
 * @property integer $operativo_id
 * @property integer $periodo_id
 * @property string $desc_ue
 * @property string $cod_le_id
 * @property string $desc_dependencia
 * @property string $telefono1
 * @property string $telefono2
 * @property string $referencia_telefono2
 * @property string $fax
 * @property string $email
 * @property string $casilla
 * @property string $ci_director
 * @property string $director
 * @property integer $item_director
 * @property integer $cod_cerrada_id
 * @property integer $turno_id
 * @property string $desc_localidad
 * @property string $id_localidad
 * @property integer $id_canton
 * @property string $desc_canton
 * @property integer $id_seccion
 * @property string $desc_seccion
 * @property integer $id_provincia
 * @property string $desc_provincia
 * @property integer $id_departamento
 * @property string $desc_departamento
 * @property integer $cod_distrito_id
 * @property string $distrito
 * @property string $zona
 * @property string $direccion
 * @property string $tipo_area
 * @property string $desc_abrv
 * @property integer $cod_org_curr
 * @property string $desc_modalidad
 * @property DatRueUnidadEducativa $DatRueUnidadEducativa
 * 
 * @method string                getCodUeId()               Returns the current record's "cod_ue_id" value
 * @method integer               getSubCeaId()              Returns the current record's "sub_cea_id" value
 * @method integer               getGestionId()             Returns the current record's "gestion_id" value
 * @method integer               getOperativoId()           Returns the current record's "operativo_id" value
 * @method integer               getPeriodoId()             Returns the current record's "periodo_id" value
 * @method string                getDescUe()                Returns the current record's "desc_ue" value
 * @method string                getCodLeId()               Returns the current record's "cod_le_id" value
 * @method string                getDescDependencia()       Returns the current record's "desc_dependencia" value
 * @method string                getTelefono1()             Returns the current record's "telefono1" value
 * @method string                getTelefono2()             Returns the current record's "telefono2" value
 * @method string                getReferenciaTelefono2()   Returns the current record's "referencia_telefono2" value
 * @method string                getFax()                   Returns the current record's "fax" value
 * @method string                getEmail()                 Returns the current record's "email" value
 * @method string                getCasilla()               Returns the current record's "casilla" value
 * @method string                getCiDirector()            Returns the current record's "ci_director" value
 * @method string                getDirector()              Returns the current record's "director" value
 * @method integer               getItemDirector()          Returns the current record's "item_director" value
 * @method integer               getCodCerradaId()          Returns the current record's "cod_cerrada_id" value
 * @method integer               getTurnoId()               Returns the current record's "turno_id" value
 * @method string                getDescLocalidad()         Returns the current record's "desc_localidad" value
 * @method string                getIdLocalidad()           Returns the current record's "id_localidad" value
 * @method integer               getIdCanton()              Returns the current record's "id_canton" value
 * @method string                getDescCanton()            Returns the current record's "desc_canton" value
 * @method integer               getIdSeccion()             Returns the current record's "id_seccion" value
 * @method string                getDescSeccion()           Returns the current record's "desc_seccion" value
 * @method integer               getIdProvincia()           Returns the current record's "id_provincia" value
 * @method string                getDescProvincia()         Returns the current record's "desc_provincia" value
 * @method integer               getIdDepartamento()        Returns the current record's "id_departamento" value
 * @method string                getDescDepartamento()      Returns the current record's "desc_departamento" value
 * @method integer               getCodDistritoId()         Returns the current record's "cod_distrito_id" value
 * @method string                getDistrito()              Returns the current record's "distrito" value
 * @method string                getZona()                  Returns the current record's "zona" value
 * @method string                getDireccion()             Returns the current record's "direccion" value
 * @method string                getTipoArea()              Returns the current record's "tipo_area" value
 * @method string                getDescAbrv()              Returns the current record's "desc_abrv" value
 * @method integer               getCodOrgCurr()            Returns the current record's "cod_org_curr" value
 * @method string                getDescModalidad()         Returns the current record's "desc_modalidad" value
 * @method DatRueUnidadEducativa getDatRueUnidadEducativa() Returns the current record's "DatRueUnidadEducativa" value
 * @method DatOpeUnidadEducativa setCodUeId()               Sets the current record's "cod_ue_id" value
 * @method DatOpeUnidadEducativa setSubCeaId()              Sets the current record's "sub_cea_id" value
 * @method DatOpeUnidadEducativa setGestionId()             Sets the current record's "gestion_id" value
 * @method DatOpeUnidadEducativa setOperativoId()           Sets the current record's "operativo_id" value
 * @method DatOpeUnidadEducativa setPeriodoId()             Sets the current record's "periodo_id" value
 * @method DatOpeUnidadEducativa setDescUe()                Sets the current record's "desc_ue" value
 * @method DatOpeUnidadEducativa setCodLeId()               Sets the current record's "cod_le_id" value
 * @method DatOpeUnidadEducativa setDescDependencia()       Sets the current record's "desc_dependencia" value
 * @method DatOpeUnidadEducativa setTelefono1()             Sets the current record's "telefono1" value
 * @method DatOpeUnidadEducativa setTelefono2()             Sets the current record's "telefono2" value
 * @method DatOpeUnidadEducativa setReferenciaTelefono2()   Sets the current record's "referencia_telefono2" value
 * @method DatOpeUnidadEducativa setFax()                   Sets the current record's "fax" value
 * @method DatOpeUnidadEducativa setEmail()                 Sets the current record's "email" value
 * @method DatOpeUnidadEducativa setCasilla()               Sets the current record's "casilla" value
 * @method DatOpeUnidadEducativa setCiDirector()            Sets the current record's "ci_director" value
 * @method DatOpeUnidadEducativa setDirector()              Sets the current record's "director" value
 * @method DatOpeUnidadEducativa setItemDirector()          Sets the current record's "item_director" value
 * @method DatOpeUnidadEducativa setCodCerradaId()          Sets the current record's "cod_cerrada_id" value
 * @method DatOpeUnidadEducativa setTurnoId()               Sets the current record's "turno_id" value
 * @method DatOpeUnidadEducativa setDescLocalidad()         Sets the current record's "desc_localidad" value
 * @method DatOpeUnidadEducativa setIdLocalidad()           Sets the current record's "id_localidad" value
 * @method DatOpeUnidadEducativa setIdCanton()              Sets the current record's "id_canton" value
 * @method DatOpeUnidadEducativa setDescCanton()            Sets the current record's "desc_canton" value
 * @method DatOpeUnidadEducativa setIdSeccion()             Sets the current record's "id_seccion" value
 * @method DatOpeUnidadEducativa setDescSeccion()           Sets the current record's "desc_seccion" value
 * @method DatOpeUnidadEducativa setIdProvincia()           Sets the current record's "id_provincia" value
 * @method DatOpeUnidadEducativa setDescProvincia()         Sets the current record's "desc_provincia" value
 * @method DatOpeUnidadEducativa setIdDepartamento()        Sets the current record's "id_departamento" value
 * @method DatOpeUnidadEducativa setDescDepartamento()      Sets the current record's "desc_departamento" value
 * @method DatOpeUnidadEducativa setCodDistritoId()         Sets the current record's "cod_distrito_id" value
 * @method DatOpeUnidadEducativa setDistrito()              Sets the current record's "distrito" value
 * @method DatOpeUnidadEducativa setZona()                  Sets the current record's "zona" value
 * @method DatOpeUnidadEducativa setDireccion()             Sets the current record's "direccion" value
 * @method DatOpeUnidadEducativa setTipoArea()              Sets the current record's "tipo_area" value
 * @method DatOpeUnidadEducativa setDescAbrv()              Sets the current record's "desc_abrv" value
 * @method DatOpeUnidadEducativa setCodOrgCurr()            Sets the current record's "cod_org_curr" value
 * @method DatOpeUnidadEducativa setDescModalidad()         Sets the current record's "desc_modalidad" value
 * @method DatOpeUnidadEducativa setDatRueUnidadEducativa() Sets the current record's "DatRueUnidadEducativa" value
 * 
 * @package    alternativa
 * @subpackage model
 * @author     Lic. Remberto Quispe Gutierrez
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDatOpeUnidadEducativa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dat_ope_unidad_educativa');
        $this->hasColumn('cod_ue_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('sub_cea_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('gestion_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('operativo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('periodo_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('desc_ue', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '80',
             ));
        $this->hasColumn('cod_le_id', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('desc_dependencia', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('telefono1', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('telefono2', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('referencia_telefono2', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('fax', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('casilla', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('ci_director', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('director', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '80',
             ));
        $this->hasColumn('item_director', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('cod_cerrada_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('turno_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('desc_localidad', 'string', 125, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '125',
             ));
        $this->hasColumn('id_localidad', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('id_canton', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('desc_canton', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('id_seccion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('desc_seccion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('id_provincia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('desc_provincia', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('id_departamento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('desc_departamento', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('cod_distrito_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('distrito', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('zona', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('direccion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '100',
             ));
        $this->hasColumn('tipo_area', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '6',
             ));
        $this->hasColumn('desc_abrv', 'string', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('cod_org_curr', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('desc_modalidad', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DatRueUnidadEducativa', array(
             'local' => 'cod_ue_id',
             'foreign' => 'cod_ue'));
    }
}